#!/usr/bin/env python3
"""pqse_sram_lib.py - Liberty stub for the SRAM macros of make se-power RAM_MACRO=1 (pqse_ram_macro.v).

    python3 scripts/power/pqse_sram_lib.py <out.lib> [--models <out.sv>]

--models: also behavioural models for gate-level simulation (access counts -> sram_access.txt)
"""
import sys

# (11, 25): polynomial RAM (DEPTH may be < 2048; modelled with 2048 words)
SHAPES = [(11, 25), (10, 25), (10, 16), (8, 17), (8, 16), (7, 7), (9, 32), (6, 65), (6, 64)]

T_CLK_Q = 2.0      # ns, clock to rdata
T_SETUP = 0.5      # ns
T_HOLD = 0.1       # ns
C_IN = 0.005       # pF
T_OUT = 0.2        # ns, output transition


def setup_hold():
    s = []
    for kind, v in (("setup_rising", T_SETUP), ("hold_rising", T_HOLD)):
        s.append(f"""      timing () {{
        related_pin : "clk";
        timing_type : {kind};
        rise_constraint (scalar) {{ values ("{v}"); }}
        fall_constraint (scalar) {{ values ("{v}"); }}
      }}""")
    return "\n".join(s)


def cell(a, d):
    sh = setup_hold()
    return f"""  cell (pqse_sram_a{a}_d{d}) {{
    area : 0;
    dont_use : true;
    dont_touch : true;
    interface_timing : true;
    pin (clk) {{
      direction : input;
      clock : true;
      capacitance : {C_IN};
    }}
    pin (we) {{
      direction : input;
      capacitance : {C_IN};
{sh}
    }}
    pin (re) {{
      direction : input;
      capacitance : {C_IN};
{sh}
    }}
    bus (waddr) {{
      bus_type : bus{a};
      direction : input;
      capacitance : {C_IN};
{sh}
    }}
    bus (raddr) {{
      bus_type : bus{a};
      direction : input;
      capacitance : {C_IN};
{sh}
    }}
    bus (wdata) {{
      bus_type : bus{d};
      direction : input;
      capacitance : {C_IN};
{sh}
    }}
    bus (rdata) {{
      bus_type : bus{d};
      direction : output;
      timing () {{
        related_pin : "clk";
        timing_type : rising_edge;
        timing_sense : non_unate;
        cell_rise (scalar) {{ values ("{T_CLK_Q}"); }}
        cell_fall (scalar) {{ values ("{T_CLK_Q}"); }}
        rise_transition (scalar) {{ values ("{T_OUT}"); }}
        fall_transition (scalar) {{ values ("{T_OUT}"); }}
      }}
    }}
  }}
"""


def models(path):
    # not traced: the arrays would swamp the dump, and the stub has no macro
    # power (energy comes from the access counts)
    out = ["// generated by scripts/power/pqse_sram_lib.py - SRAM macro models for the",
           "// gate-level power simulation (tb_pqse_gate.sv); not synthesizable",
           "// verilator tracing_off", ""]
    for a, d in SHAPES:
        out.append(f"""module pqse_sram_a{a}_d{d} (
  input  wire          clk,
  input  wire          we,
  input  wire [{a-1}:0]  waddr,
  input  wire [{d-1}:0] wdata,
  input  wire          re,
  input  wire [{a-1}:0]  raddr,
  output reg  [{d-1}:0] rdata
);
  reg [{d-1}:0] mem [0:{(1 << a) - 1}];
  longint nr = 0, nw = 0;
  initial begin
    for (int i = 0; i < {1 << a}; i++) mem[i] = '0;
    rdata = '0;
  end
  always @(posedge clk) begin
    if (we) mem[waddr] <= wdata;
    if (re) rdata <= mem[raddr];
    if ($root.tb_pqse_gate.win) begin
      if (re) nr <= nr + 1;
      if (we) nw <= nw + 1;
    end
  end
  final begin
    int f;
    f = $fopen("sram_access.txt", "a");
    $fdisplay(f, "a{a}_d{d} %0d %0d", nr, nw);
    $fclose(f);
  end
endmodule
""")
    out.append("// verilator tracing_on")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"pqse_sram_lib: {len(SHAPES)} macro models -> {path}")


def main():
    args = sys.argv[1:]
    mpath = None
    if "--models" in args:
        i = args.index("--models")
        mpath = args[i + 1]
        del args[i:i + 2]
    if len(args) != 1:
        sys.exit(__doc__)
    if mpath:
        models(mpath)
    sys.argv = [sys.argv[0]] + args
    widths = sorted({w for s in SHAPES for w in s})
    types = "".join(f"""  type (bus{w}) {{
    base_type : array;
    data_type : bit;
    bit_width : {w};
    bit_from : {w - 1};
    bit_to : 0;
    downto : true;
  }}
""" for w in widths)
    cells = "".join(cell(a, d) for a, d in SHAPES)
    with open(sys.argv[1], "w") as f:
        f.write(f"""/* generated by scripts/power/pqse_sram_lib.py - SRAM macro stubs, no power */
library (pqse_sram) {{
  delay_model : table_lookup;
  time_unit : "1ns";
  voltage_unit : "1V";
  current_unit : "1mA";
  pulling_resistance_unit : "1kohm";
  leakage_power_unit : "1nW";
  capacitive_load_unit (1, pf);
  nom_process : 1.0;
  nom_voltage : 1.8;
  nom_temperature : 25.0;
  default_cell_leakage_power : 0;
  default_inout_pin_cap : {C_IN};
  default_input_pin_cap : {C_IN};
  default_output_pin_cap : 0;
  default_fanout_load : 1;
  input_threshold_pct_rise : 50;
  input_threshold_pct_fall : 50;
  output_threshold_pct_rise : 50;
  output_threshold_pct_fall : 50;
  slew_lower_threshold_pct_rise : 20;
  slew_lower_threshold_pct_fall : 20;
  slew_upper_threshold_pct_rise : 80;
  slew_upper_threshold_pct_fall : 80;
  slew_derate_from_library : 1.0;
{types}{cells}}}
""")
    print(f"pqse_sram_lib: {len(SHAPES)} macro stubs -> {sys.argv[1]}")


if __name__ == "__main__":
    main()
