// pqse_aes.v - first-order masked AES-256-GCM engine (PQSE_AES)
// pqse_aes_sbox: Boyar-Peralta S-box, HPC2 ANDs, 1 byte / 2 clocks, latency 9.
// pqse_aes: C_AES ops (AO_*, pqse_defs.vh), results in seed lanes. Key, round
// keys, state, H, GHASH sum in two shares. ~700 clocks per block; GHASH in two
// 128-clock passes (H0, then H1). Only the CTR keystream leaves unmasked.
// Faults: op, state, round, busy complemented copies; data faults not detected.
`ifdef PQSE_AES
module pqse_aes_sbox (
  input  wire       clk,
  input  wire       en,         // advance (SubBytes / SubWord)
  input  wire       ph,         // 1: input and a stages, 0: b stages (randomness)
  input  wire [7:0] x0,         // ph 1: input byte, shares
  input  wire [7:0] x1,
  input  wire [33:0] r,         // ph 0: fresh bits, one per AND gate
  output wire [7:0] y0,         // ph 0: result for the byte input 9 clocks earlier
  output wire [7:0] y1
);
  // ---- generated by scripts/pqse_gcm.py gen: begin ----
  // 34 HPC2 AND gates (one random bit each: r[33:0]); 210 registers per share
  reg [7:0] xa_0, xa_1;
  reg [7:0] xd1_0, xd1_1;
  reg [7:0] xd2_0, xd2_1;
  reg [7:0] xd3_0, xd3_1;
  reg m1_hb_0, m1_hb_1;
  reg m1_hr_0, m1_hr_1;
  reg m1_hp0_0, m1_hp0_1;
  reg m1_hpr_0, m1_hpr_1;
  reg m1_hpx_0, m1_hpx_1;
  reg m1_hR;
  reg m2_hb_0, m2_hb_1;
  reg m2_hr_0, m2_hr_1;
  reg m2_hp0_0, m2_hp0_1;
  reg m2_hpr_0, m2_hpr_1;
  reg m2_hpx_0, m2_hpx_1;
  reg m2_hR;
  reg m4_hb_0, m4_hb_1;
  reg m4_hr_0, m4_hr_1;
  reg m4_hp0_0, m4_hp0_1;
  reg m4_hpr_0, m4_hpr_1;
  reg m4_hpx_0, m4_hpx_1;
  reg m4_hR;
  reg m6_hb_0, m6_hb_1;
  reg m6_hr_0, m6_hr_1;
  reg m6_hp0_0, m6_hp0_1;
  reg m6_hpr_0, m6_hpr_1;
  reg m6_hpx_0, m6_hpx_1;
  reg m6_hR;
  reg m7_hb_0, m7_hb_1;
  reg m7_hr_0, m7_hr_1;
  reg m7_hp0_0, m7_hp0_1;
  reg m7_hpr_0, m7_hpr_1;
  reg m7_hpx_0, m7_hpx_1;
  reg m7_hR;
  reg m9_hb_0, m9_hb_1;
  reg m9_hr_0, m9_hr_1;
  reg m9_hp0_0, m9_hp0_1;
  reg m9_hpr_0, m9_hpr_1;
  reg m9_hpx_0, m9_hpx_1;
  reg m9_hR;
  reg m11_hb_0, m11_hb_1;
  reg m11_hr_0, m11_hr_1;
  reg m11_hp0_0, m11_hp0_1;
  reg m11_hpr_0, m11_hpr_1;
  reg m11_hpx_0, m11_hpx_1;
  reg m11_hR;
  reg m12_hb_0, m12_hb_1;
  reg m12_hr_0, m12_hr_1;
  reg m12_hp0_0, m12_hp0_1;
  reg m12_hpr_0, m12_hpr_1;
  reg m12_hpx_0, m12_hpx_1;
  reg m12_hR;
  reg m14_hb_0, m14_hb_1;
  reg m14_hr_0, m14_hr_1;
  reg m14_hp0_0, m14_hp0_1;
  reg m14_hpr_0, m14_hpr_1;
  reg m14_hpx_0, m14_hpx_1;
  reg m14_hR;
  reg m25_hb_0, m25_hb_1;
  reg m25_hr_0, m25_hr_1;
  reg m25_hp0_0, m25_hp0_1;
  reg m25_hpr_0, m25_hpr_1;
  reg m25_hpx_0, m25_hpx_1;
  reg m25_hR;
  reg m31_hb_0, m31_hb_1;
  reg m31_hr_0, m31_hr_1;
  reg m31_hp0_0, m31_hp0_1;
  reg m31_hpr_0, m31_hpr_1;
  reg m31_hpx_0, m31_hpx_1;
  reg m31_hR;
  reg m34_hb_0, m34_hb_1;
  reg m34_hr_0, m34_hr_1;
  reg m34_hp0_0, m34_hp0_1;
  reg m34_hpr_0, m34_hpr_1;
  reg m34_hpx_0, m34_hpx_1;
  reg m34_hR;
  reg p2_M21_0, p2_M21_1;
  reg p2_M23_0, p2_M23_1;
  reg p2_M24_0, p2_M24_1;
  reg p2_M27_0, p2_M27_1;
  reg m29_hb_0, m29_hb_1;
  reg m29_hr_0, m29_hr_1;
  reg m29_hp0_0, m29_hp0_1;
  reg m29_hpr_0, m29_hpr_1;
  reg m29_hpx_0, m29_hpx_1;
  reg m29_hR;
  reg m30_hb_0, m30_hb_1;
  reg m30_hr_0, m30_hr_1;
  reg m30_hp0_0, m30_hp0_1;
  reg m30_hpr_0, m30_hpr_1;
  reg m30_hpx_0, m30_hpx_1;
  reg m30_hR;
  reg m32_hb_0, m32_hb_1;
  reg m32_hr_0, m32_hr_1;
  reg m32_hp0_0, m32_hp0_1;
  reg m32_hpr_0, m32_hpr_1;
  reg m32_hpx_0, m32_hpx_1;
  reg m32_hR;
  reg m35_hb_0, m35_hb_1;
  reg m35_hr_0, m35_hr_1;
  reg m35_hp0_0, m35_hp0_1;
  reg m35_hpr_0, m35_hpr_1;
  reg m35_hpx_0, m35_hpx_1;
  reg m35_hR;
  reg p3_M21_0, p3_M21_1;
  reg p3_M23_0, p3_M23_1;
  reg p3_M33_0, p3_M33_1;
  reg p3_M36_0, p3_M36_1;
  reg m46_hb_0, m46_hb_1;
  reg m46_hr_0, m46_hr_1;
  reg m46_hp0_0, m46_hp0_1;
  reg m46_hpr_0, m46_hpr_1;
  reg m46_hpx_0, m46_hpx_1;
  reg m46_hR;
  reg m47_hb_0, m47_hb_1;
  reg m47_hr_0, m47_hr_1;
  reg m47_hp0_0, m47_hp0_1;
  reg m47_hpr_0, m47_hpr_1;
  reg m47_hpx_0, m47_hpx_1;
  reg m47_hR;
  reg m48_hb_0, m48_hb_1;
  reg m48_hr_0, m48_hr_1;
  reg m48_hp0_0, m48_hp0_1;
  reg m48_hpr_0, m48_hpr_1;
  reg m48_hpx_0, m48_hpx_1;
  reg m48_hR;
  reg m49_hb_0, m49_hb_1;
  reg m49_hr_0, m49_hr_1;
  reg m49_hp0_0, m49_hp0_1;
  reg m49_hpr_0, m49_hpr_1;
  reg m49_hpx_0, m49_hpx_1;
  reg m49_hR;
  reg m50_hb_0, m50_hb_1;
  reg m50_hr_0, m50_hr_1;
  reg m50_hp0_0, m50_hp0_1;
  reg m50_hpr_0, m50_hpr_1;
  reg m50_hpx_0, m50_hpx_1;
  reg m50_hR;
  reg m51_hb_0, m51_hb_1;
  reg m51_hr_0, m51_hr_1;
  reg m51_hp0_0, m51_hp0_1;
  reg m51_hpr_0, m51_hpr_1;
  reg m51_hpx_0, m51_hpx_1;
  reg m51_hR;
  reg m52_hb_0, m52_hb_1;
  reg m52_hr_0, m52_hr_1;
  reg m52_hp0_0, m52_hp0_1;
  reg m52_hpr_0, m52_hpr_1;
  reg m52_hpx_0, m52_hpx_1;
  reg m52_hR;
  reg m53_hb_0, m53_hb_1;
  reg m53_hr_0, m53_hr_1;
  reg m53_hp0_0, m53_hp0_1;
  reg m53_hpr_0, m53_hpr_1;
  reg m53_hpx_0, m53_hpx_1;
  reg m53_hR;
  reg m54_hb_0, m54_hb_1;
  reg m54_hr_0, m54_hr_1;
  reg m54_hp0_0, m54_hp0_1;
  reg m54_hpr_0, m54_hpr_1;
  reg m54_hpx_0, m54_hpx_1;
  reg m54_hR;
  reg m55_hb_0, m55_hb_1;
  reg m55_hr_0, m55_hr_1;
  reg m55_hp0_0, m55_hp0_1;
  reg m55_hpr_0, m55_hpr_1;
  reg m55_hpx_0, m55_hpx_1;
  reg m55_hR;
  reg m56_hb_0, m56_hb_1;
  reg m56_hr_0, m56_hr_1;
  reg m56_hp0_0, m56_hp0_1;
  reg m56_hpr_0, m56_hpr_1;
  reg m56_hpx_0, m56_hpx_1;
  reg m56_hR;
  reg m57_hb_0, m57_hb_1;
  reg m57_hr_0, m57_hr_1;
  reg m57_hp0_0, m57_hp0_1;
  reg m57_hpr_0, m57_hpr_1;
  reg m57_hpx_0, m57_hpx_1;
  reg m57_hR;
  reg m58_hb_0, m58_hb_1;
  reg m58_hr_0, m58_hr_1;
  reg m58_hp0_0, m58_hp0_1;
  reg m58_hpr_0, m58_hpr_1;
  reg m58_hpx_0, m58_hpx_1;
  reg m58_hR;
  reg m59_hb_0, m59_hb_1;
  reg m59_hr_0, m59_hr_1;
  reg m59_hp0_0, m59_hp0_1;
  reg m59_hpr_0, m59_hpr_1;
  reg m59_hpx_0, m59_hpx_1;
  reg m59_hR;
  reg m60_hb_0, m60_hb_1;
  reg m60_hr_0, m60_hr_1;
  reg m60_hp0_0, m60_hp0_1;
  reg m60_hpr_0, m60_hpr_1;
  reg m60_hpx_0, m60_hpx_1;
  reg m60_hR;
  reg m61_hb_0, m61_hb_1;
  reg m61_hr_0, m61_hr_1;
  reg m61_hp0_0, m61_hp0_1;
  reg m61_hpr_0, m61_hpr_1;
  reg m61_hpx_0, m61_hpx_1;
  reg m61_hR;
  reg m62_hb_0, m62_hb_1;
  reg m62_hr_0, m62_hr_1;
  reg m62_hp0_0, m62_hp0_1;
  reg m62_hpr_0, m62_hpr_1;
  reg m62_hpx_0, m62_hpx_1;
  reg m62_hR;
  reg m63_hb_0, m63_hb_1;
  reg m63_hr_0, m63_hr_1;
  reg m63_hp0_0, m63_hp0_1;
  reg m63_hpr_0, m63_hpr_1;
  reg m63_hpx_0, m63_hpx_1;
  reg m63_hR;
  wire sA_T3_0 = xa_0[7] ^ xa_0[1];
  wire sA_T3_1 = xa_1[7] ^ xa_1[1];
  wire sA_T4_0 = xa_0[4] ^ xa_0[2];
  wire sA_T4_1 = xa_1[4] ^ xa_1[2];
  wire sA_T13_0 = sA_T3_0 ^ sA_T4_0;
  wire sA_T13_1 = sA_T3_1 ^ sA_T4_1;
  wire sA_T1_0 = xa_0[7] ^ xa_0[4];
  wire sA_T1_1 = xa_1[7] ^ xa_1[4];
  wire sA_T5_0 = xa_0[3] ^ xa_0[1];
  wire sA_T5_1 = xa_1[3] ^ xa_1[1];
  wire sA_T6_0 = sA_T1_0 ^ sA_T5_0;
  wire sA_T6_1 = sA_T1_1 ^ sA_T5_1;
  wire sA_T2_0 = xa_0[7] ^ xa_0[2];
  wire sA_T2_1 = xa_1[7] ^ xa_1[2];
  wire sA_T7_0 = xa_0[6] ^ xa_0[5];
  wire sA_T7_1 = xa_1[6] ^ xa_1[5];
  wire sA_T21_0 = xa_0[1] ^ xa_0[0];
  wire sA_T21_1 = xa_1[1] ^ xa_1[0];
  wire sA_T22_0 = sA_T7_0 ^ sA_T21_0;
  wire sA_T22_1 = sA_T7_1 ^ sA_T21_1;
  wire sA_T23_0 = sA_T2_0 ^ sA_T22_0;
  wire sA_T23_1 = sA_T2_1 ^ sA_T22_1;
  wire sA_T8_0 = xa_0[0] ^ sA_T6_0;
  wire sA_T8_1 = xa_1[0] ^ sA_T6_1;
  wire sA_T18_0 = xa_0[4] ^ xa_0[0];
  wire sA_T18_1 = xa_1[4] ^ xa_1[0];
  wire sA_T19_0 = sA_T7_0 ^ sA_T18_0;
  wire sA_T19_1 = sA_T7_1 ^ sA_T18_1;
  wire sA_T12_0 = xa_0[5] ^ xa_0[2];
  wire sA_T12_1 = xa_1[5] ^ xa_1[2];
  wire sA_T16_0 = sA_T5_0 ^ sA_T12_0;
  wire sA_T16_1 = sA_T5_1 ^ sA_T12_1;
  wire sA_T9_0 = xa_0[0] ^ sA_T7_0;
  wire sA_T9_1 = xa_1[0] ^ sA_T7_1;
  wire sA_T20_0 = sA_T1_0 ^ sA_T19_0;
  wire sA_T20_1 = sA_T1_1 ^ sA_T19_1;
  wire sA_T17_0 = sA_T9_0 ^ sA_T16_0;
  wire sA_T17_1 = sA_T9_1 ^ sA_T16_1;
  wire sA_T11_0 = xa_0[6] ^ xa_0[2];
  wire sA_T11_1 = xa_1[6] ^ xa_1[2];
  wire sA_T15_0 = sA_T5_0 ^ sA_T11_0;
  wire sA_T15_1 = sA_T5_1 ^ sA_T11_1;
  wire sA_T27_0 = sA_T1_0 ^ sA_T12_0;
  wire sA_T27_1 = sA_T1_1 ^ sA_T12_1;
  wire sA_T10_0 = sA_T6_0 ^ sA_T7_0;
  wire sA_T10_1 = sA_T6_1 ^ sA_T7_1;
  wire sB_T3_0 = xd1_0[7] ^ xd1_0[1];
  wire sB_T3_1 = xd1_1[7] ^ xd1_1[1];
  wire sB_T5_0 = xd1_0[3] ^ xd1_0[1];
  wire sB_T5_1 = xd1_1[3] ^ xd1_1[1];
  wire sB_T12_0 = xd1_0[5] ^ xd1_0[2];
  wire sB_T12_1 = xd1_1[5] ^ xd1_1[2];
  wire sB_T16_0 = sB_T5_0 ^ sB_T12_0;
  wire sB_T16_1 = sB_T5_1 ^ sB_T12_1;
  wire sB_T26_0 = sB_T3_0 ^ sB_T16_0;
  wire sB_T26_1 = sB_T3_1 ^ sB_T16_1;
  wire sB_M8_0 = sB_T26_0 ^ (m6_hp0_0 ^ m6_hpr_0 ^ m6_hpx_0);
  wire sB_M8_1 = sB_T26_1 ^ (m6_hp0_1 ^ m6_hpr_1 ^ m6_hpx_1);
  wire sB_M18_0 = sB_M8_0 ^ (m7_hp0_0 ^ m7_hpr_0 ^ m7_hpx_0);
  wire sB_M18_1 = sB_M8_1 ^ (m7_hp0_1 ^ m7_hpr_1 ^ m7_hpx_1);
  wire sB_M13_0 = (m12_hp0_0 ^ m12_hpr_0 ^ m12_hpx_0) ^ (m11_hp0_0 ^ m11_hpr_0 ^ m11_hpx_0);
  wire sB_M13_1 = (m12_hp0_1 ^ m12_hpr_1 ^ m12_hpx_1) ^ (m11_hp0_1 ^ m11_hpr_1 ^ m11_hpx_1);
  wire sB_M22_0 = sB_M18_0 ^ sB_M13_0;
  wire sB_M22_1 = sB_M18_1 ^ sB_M13_1;
  wire sB_T1_0 = xd1_0[7] ^ xd1_0[4];
  wire sB_T1_1 = xd1_1[7] ^ xd1_1[4];
  wire sB_T6_0 = sB_T1_0 ^ sB_T5_0;
  wire sB_T6_1 = sB_T1_1 ^ sB_T5_1;
  wire sB_T11_0 = xd1_0[6] ^ xd1_0[2];
  wire sB_T11_1 = xd1_1[6] ^ xd1_1[2];
  wire sB_T14_0 = sB_T6_0 ^ sB_T11_0;
  wire sB_T14_1 = sB_T6_1 ^ sB_T11_1;
  wire sB_M3_0 = sB_T14_0 ^ (m1_hp0_0 ^ m1_hpr_0 ^ m1_hpx_0);
  wire sB_M3_1 = sB_T14_1 ^ (m1_hp0_1 ^ m1_hpr_1 ^ m1_hpx_1);
  wire sB_M16_0 = sB_M3_0 ^ (m2_hp0_0 ^ m2_hpr_0 ^ m2_hpx_0);
  wire sB_M16_1 = sB_M3_1 ^ (m2_hp0_1 ^ m2_hpr_1 ^ m2_hpx_1);
  wire sB_M20_0 = sB_M16_0 ^ sB_M13_0;
  wire sB_M20_1 = sB_M16_1 ^ sB_M13_1;
  wire sB_M10_0 = (m9_hp0_0 ^ m9_hpr_0 ^ m9_hpx_0) ^ (m6_hp0_0 ^ m6_hpr_0 ^ m6_hpx_0);
  wire sB_M10_1 = (m9_hp0_1 ^ m9_hpr_1 ^ m9_hpx_1) ^ (m6_hp0_1 ^ m6_hpr_1 ^ m6_hpx_1);
  wire sB_M15_0 = (m14_hp0_0 ^ m14_hpr_0 ^ m14_hpx_0) ^ (m11_hp0_0 ^ m11_hpr_0 ^ m11_hpx_0);
  wire sB_M15_1 = (m14_hp0_1 ^ m14_hpr_1 ^ m14_hpx_1) ^ (m11_hp0_1 ^ m11_hpr_1 ^ m11_hpx_1);
  wire sB_M19_0 = sB_M10_0 ^ sB_M15_0;
  wire sB_M19_1 = sB_M10_1 ^ sB_M15_1;
  wire sB_T7_0 = xd1_0[6] ^ xd1_0[5];
  wire sB_T7_1 = xd1_1[6] ^ xd1_1[5];
  wire sB_T18_0 = xd1_0[4] ^ xd1_0[0];
  wire sB_T18_1 = xd1_1[4] ^ xd1_1[0];
  wire sB_T19_0 = sB_T7_0 ^ sB_T18_0;
  wire sB_T19_1 = sB_T7_1 ^ sB_T18_1;
  wire sB_T20_0 = sB_T1_0 ^ sB_T19_0;
  wire sB_T20_1 = sB_T1_1 ^ sB_T19_1;
  wire sB_T9_0 = xd1_0[0] ^ sB_T7_0;
  wire sB_T9_1 = xd1_1[0] ^ sB_T7_1;
  wire sB_T17_0 = sB_T9_0 ^ sB_T16_0;
  wire sB_T17_1 = sB_T9_1 ^ sB_T16_1;
  wire sB_T25_0 = sB_T20_0 ^ sB_T17_0;
  wire sB_T25_1 = sB_T20_1 ^ sB_T17_1;
  wire sB_M23_0 = sB_M19_0 ^ sB_T25_0;
  wire sB_M23_1 = sB_M19_1 ^ sB_T25_1;
  wire sB_M5_0 = (m4_hp0_0 ^ m4_hpr_0 ^ m4_hpx_0) ^ (m1_hp0_0 ^ m1_hpr_0 ^ m1_hpx_0);
  wire sB_M5_1 = (m4_hp0_1 ^ m4_hpr_1 ^ m4_hpx_1) ^ (m1_hp0_1 ^ m1_hpr_1 ^ m1_hpx_1);
  wire sB_T2_0 = xd1_0[7] ^ xd1_0[2];
  wire sB_T2_1 = xd1_1[7] ^ xd1_1[2];
  wire sB_T10_0 = sB_T6_0 ^ sB_T7_0;
  wire sB_T10_1 = sB_T6_1 ^ sB_T7_1;
  wire sB_T24_0 = sB_T2_0 ^ sB_T10_0;
  wire sB_T24_1 = sB_T2_1 ^ sB_T10_1;
  wire sB_M17_0 = sB_M5_0 ^ sB_T24_0;
  wire sB_M17_1 = sB_M5_1 ^ sB_T24_1;
  wire sB_M21_0 = sB_M17_0 ^ sB_M15_0;
  wire sB_M21_1 = sB_M17_1 ^ sB_M15_1;
  wire sB_M24_0 = sB_M22_0 ^ sB_M23_0;
  wire sB_M24_1 = sB_M22_1 ^ sB_M23_1;
  wire sB_M27_0 = sB_M20_0 ^ sB_M21_0;
  wire sB_M27_1 = sB_M20_1 ^ sB_M21_1;
  wire sC_M28_0 = p2_M23_0 ^ (m25_hp0_0 ^ m25_hpr_0 ^ m25_hpx_0);
  wire sC_M28_1 = p2_M23_1 ^ (m25_hp0_1 ^ m25_hpr_1 ^ m25_hpx_1);
  wire sC_M26_0 = p2_M21_0 ^ (m25_hp0_0 ^ m25_hpr_0 ^ m25_hpx_0);
  wire sC_M26_1 = p2_M21_1 ^ (m25_hp0_1 ^ m25_hpr_1 ^ m25_hpx_1);
  wire sC_M33_0 = p2_M27_0 ^ (m25_hp0_0 ^ m25_hpr_0 ^ m25_hpx_0);
  wire sC_M33_1 = p2_M27_1 ^ (m25_hp0_1 ^ m25_hpr_1 ^ m25_hpx_1);
  wire sC_M36_0 = p2_M24_0 ^ (m25_hp0_0 ^ m25_hpr_0 ^ m25_hpx_0);
  wire sC_M36_1 = p2_M24_1 ^ (m25_hp0_1 ^ m25_hpr_1 ^ m25_hpx_1);
  wire sD_M39_0 = p3_M23_0 ^ (m30_hp0_0 ^ m30_hpr_0 ^ m30_hpx_0);
  wire sD_M39_1 = p3_M23_1 ^ (m30_hp0_1 ^ m30_hpr_1 ^ m30_hpx_1);
  wire sD_M40_0 = (m35_hp0_0 ^ m35_hpr_0 ^ m35_hpx_0) ^ p3_M36_0;
  wire sD_M40_1 = (m35_hp0_1 ^ m35_hpr_1 ^ m35_hpx_1) ^ p3_M36_1;
  wire sD_M44_0 = sD_M39_0 ^ sD_M40_0;
  wire sD_M44_1 = sD_M39_1 ^ sD_M40_1;
  wire sD_T1_0 = xd3_0[7] ^ xd3_0[4];
  wire sD_T1_1 = xd3_1[7] ^ xd3_1[4];
  wire sD_T5_0 = xd3_0[3] ^ xd3_0[1];
  wire sD_T5_1 = xd3_1[3] ^ xd3_1[1];
  wire sD_T6_0 = sD_T1_0 ^ sD_T5_0;
  wire sD_T6_1 = sD_T1_1 ^ sD_T5_1;
  wire sD_T8_0 = xd3_0[0] ^ sD_T6_0;
  wire sD_T8_1 = xd3_1[0] ^ sD_T6_1;
  wire sD_M37_0 = p3_M21_0 ^ (m29_hp0_0 ^ m29_hpr_0 ^ m29_hpx_0);
  wire sD_M37_1 = p3_M21_1 ^ (m29_hp0_1 ^ m29_hpr_1 ^ m29_hpx_1);
  wire sD_M38_0 = (m32_hp0_0 ^ m32_hpr_0 ^ m32_hpx_0) ^ p3_M33_0;
  wire sD_M38_1 = (m32_hp0_1 ^ m32_hpr_1 ^ m32_hpx_1) ^ p3_M33_1;
  wire sD_M43_0 = sD_M37_0 ^ sD_M38_0;
  wire sD_M43_1 = sD_M37_1 ^ sD_M38_1;
  wire sD_T12_0 = xd3_0[5] ^ xd3_0[2];
  wire sD_T12_1 = xd3_1[5] ^ xd3_1[2];
  wire sD_T16_0 = sD_T5_0 ^ sD_T12_0;
  wire sD_T16_1 = sD_T5_1 ^ sD_T12_1;
  wire sD_T7_0 = xd3_0[6] ^ xd3_0[5];
  wire sD_T7_1 = xd3_1[6] ^ xd3_1[5];
  wire sD_T9_0 = xd3_0[0] ^ sD_T7_0;
  wire sD_T9_1 = xd3_1[0] ^ sD_T7_1;
  wire sD_T17_0 = sD_T9_0 ^ sD_T16_0;
  wire sD_T17_1 = sD_T9_1 ^ sD_T16_1;
  wire sD_M42_0 = sD_M37_0 ^ sD_M39_0;
  wire sD_M42_1 = sD_M37_1 ^ sD_M39_1;
  wire sD_T11_0 = xd3_0[6] ^ xd3_0[2];
  wire sD_T11_1 = xd3_1[6] ^ xd3_1[2];
  wire sD_T15_0 = sD_T5_0 ^ sD_T11_0;
  wire sD_T15_1 = sD_T5_1 ^ sD_T11_1;
  wire sD_M41_0 = sD_M38_0 ^ sD_M40_0;
  wire sD_M41_1 = sD_M38_1 ^ sD_M40_1;
  wire sD_M45_0 = sD_M42_0 ^ sD_M41_0;
  wire sD_M45_1 = sD_M42_1 ^ sD_M41_1;
  wire sD_T27_0 = sD_T1_0 ^ sD_T12_0;
  wire sD_T27_1 = sD_T1_1 ^ sD_T12_1;
  wire sD_T10_0 = sD_T6_0 ^ sD_T7_0;
  wire sD_T10_1 = sD_T6_1 ^ sD_T7_1;
  wire sD_T3_0 = xd3_0[7] ^ xd3_0[1];
  wire sD_T3_1 = xd3_1[7] ^ xd3_1[1];
  wire sD_T4_0 = xd3_0[4] ^ xd3_0[2];
  wire sD_T4_1 = xd3_1[4] ^ xd3_1[2];
  wire sD_T13_0 = sD_T3_0 ^ sD_T4_0;
  wire sD_T13_1 = sD_T3_1 ^ sD_T4_1;
  wire sD_T2_0 = xd3_0[7] ^ xd3_0[2];
  wire sD_T2_1 = xd3_1[7] ^ xd3_1[2];
  wire sD_T21_0 = xd3_0[1] ^ xd3_0[0];
  wire sD_T21_1 = xd3_1[1] ^ xd3_1[0];
  wire sD_T22_0 = sD_T7_0 ^ sD_T21_0;
  wire sD_T22_1 = sD_T7_1 ^ sD_T21_1;
  wire sD_T23_0 = sD_T2_0 ^ sD_T22_0;
  wire sD_T23_1 = sD_T2_1 ^ sD_T22_1;
  wire sD_T18_0 = xd3_0[4] ^ xd3_0[0];
  wire sD_T18_1 = xd3_1[4] ^ xd3_1[0];
  wire sD_T19_0 = sD_T7_0 ^ sD_T18_0;
  wire sD_T19_1 = sD_T7_1 ^ sD_T18_1;
  wire sD_T20_0 = sD_T1_0 ^ sD_T19_0;
  wire sD_T20_1 = sD_T1_1 ^ sD_T19_1;
  wire sE_L5_0 = (m49_hp0_0 ^ m49_hpr_0 ^ m49_hpx_0) ^ (m61_hp0_0 ^ m61_hpr_0 ^ m61_hpx_0);
  wire sE_L5_1 = (m49_hp0_1 ^ m49_hpr_1 ^ m49_hpx_1) ^ (m61_hp0_1 ^ m61_hpr_1 ^ m61_hpx_1);
  wire sE_L6_0 = (m62_hp0_0 ^ m62_hpr_0 ^ m62_hpx_0) ^ sE_L5_0;
  wire sE_L6_1 = (m62_hp0_1 ^ m62_hpr_1 ^ m62_hpx_1) ^ sE_L5_1;
  wire sE_L1_0 = (m50_hp0_0 ^ m50_hpr_0 ^ m50_hpx_0) ^ (m56_hp0_0 ^ m56_hpr_0 ^ m56_hpx_0);
  wire sE_L1_1 = (m50_hp0_1 ^ m50_hpr_1 ^ m50_hpx_1) ^ (m56_hp0_1 ^ m56_hpr_1 ^ m56_hpx_1);
  wire sE_L15_0 = (m55_hp0_0 ^ m55_hpr_0 ^ m55_hpx_0) ^ sE_L1_0;
  wire sE_L15_1 = (m55_hp0_1 ^ m55_hpr_1 ^ m55_hpx_1) ^ sE_L1_1;
  wire sE_L9_0 = (m52_hp0_0 ^ m52_hpr_0 ^ m52_hpx_0) ^ (m53_hp0_0 ^ m53_hpr_0 ^ m53_hpx_0);
  wire sE_L9_1 = (m52_hp0_1 ^ m52_hpr_1 ^ m52_hpx_1) ^ (m53_hp0_1 ^ m53_hpr_1 ^ m53_hpx_1);
  wire sE_L24_0 = sE_L15_0 ^ sE_L9_0;
  wire sE_L24_1 = sE_L15_1 ^ sE_L9_1;
  wire sE_S0_0 = sE_L6_0 ^ sE_L24_0;
  wire sE_S0_1 = sE_L6_1 ^ sE_L24_1;
  wire sE_L0_0 = (m61_hp0_0 ^ m61_hpr_0 ^ m61_hpx_0) ^ (m62_hp0_0 ^ m62_hpr_0 ^ m62_hpx_0);
  wire sE_L0_1 = (m61_hp0_1 ^ m61_hpr_1 ^ m61_hpx_1) ^ (m62_hp0_1 ^ m62_hpr_1 ^ m62_hpx_1);
  wire sE_L16_0 = (m56_hp0_0 ^ m56_hpr_0 ^ m56_hpx_0) ^ sE_L0_0;
  wire sE_L16_1 = (m56_hp0_1 ^ m56_hpr_1 ^ m56_hpx_1) ^ sE_L0_1;
  wire sE_L3_0 = (m47_hp0_0 ^ m47_hpr_0 ^ m47_hpx_0) ^ (m55_hp0_0 ^ m55_hpr_0 ^ m55_hpx_0);
  wire sE_L3_1 = (m47_hp0_1 ^ m47_hpr_1 ^ m47_hpx_1) ^ (m55_hp0_1 ^ m55_hpr_1 ^ m55_hpx_1);
  wire sE_L7_0 = (m46_hp0_0 ^ m46_hpr_0 ^ m46_hpx_0) ^ sE_L3_0;
  wire sE_L7_1 = (m46_hp0_1 ^ m46_hpr_1 ^ m46_hpx_1) ^ sE_L3_1;
  wire sE_L26_0 = sE_L7_0 ^ sE_L9_0;
  wire sE_L26_1 = sE_L7_1 ^ sE_L9_1;
  wire sE_S1_0 = ~(sE_L16_0 ^ sE_L26_0);
  wire sE_S1_1 = (sE_L16_1 ^ sE_L26_1);
  wire sE_L4_0 = (m54_hp0_0 ^ m54_hpr_0 ^ m54_hpx_0) ^ (m58_hp0_0 ^ m58_hpr_0 ^ m58_hpx_0);
  wire sE_L4_1 = (m54_hp0_1 ^ m54_hpr_1 ^ m54_hpx_1) ^ (m58_hp0_1 ^ m58_hpr_1 ^ m58_hpx_1);
  wire sE_L19_0 = (m63_hp0_0 ^ m63_hpr_0 ^ m63_hpx_0) ^ sE_L4_0;
  wire sE_L19_1 = (m63_hp0_1 ^ m63_hpr_1 ^ m63_hpx_1) ^ sE_L4_1;
  wire sE_L2_0 = (m46_hp0_0 ^ m46_hpr_0 ^ m46_hpx_0) ^ (m48_hp0_0 ^ m48_hpr_0 ^ m48_hpx_0);
  wire sE_L2_1 = (m46_hp0_1 ^ m46_hpr_1 ^ m46_hpx_1) ^ (m48_hp0_1 ^ m48_hpr_1 ^ m48_hpx_1);
  wire sE_L11_0 = (m60_hp0_0 ^ m60_hpr_0 ^ m60_hpx_0) ^ sE_L2_0;
  wire sE_L11_1 = (m60_hp0_1 ^ m60_hpr_1 ^ m60_hpx_1) ^ sE_L2_1;
  wire sE_L14_0 = (m52_hp0_0 ^ m52_hpr_0 ^ m52_hpx_0) ^ (m61_hp0_0 ^ m61_hpr_0 ^ m61_hpx_0);
  wire sE_L14_1 = (m52_hp0_1 ^ m52_hpr_1 ^ m52_hpx_1) ^ (m61_hp0_1 ^ m61_hpr_1 ^ m61_hpx_1);
  wire sE_L28_0 = sE_L11_0 ^ sE_L14_0;
  wire sE_L28_1 = sE_L11_1 ^ sE_L14_1;
  wire sE_S2_0 = ~(sE_L19_0 ^ sE_L28_0);
  wire sE_S2_1 = (sE_L19_1 ^ sE_L28_1);
  wire sE_L21_0 = sE_L1_0 ^ sE_L7_0;
  wire sE_L21_1 = sE_L1_1 ^ sE_L7_1;
  wire sE_S3_0 = sE_L6_0 ^ sE_L21_0;
  wire sE_S3_1 = sE_L6_1 ^ sE_L21_1;
  wire sE_L20_0 = sE_L0_0 ^ sE_L1_0;
  wire sE_L20_1 = sE_L0_1 ^ sE_L1_1;
  wire sE_L12_0 = (m48_hp0_0 ^ m48_hpr_0 ^ m48_hpx_0) ^ (m51_hp0_0 ^ m51_hpr_0 ^ m51_hpx_0);
  wire sE_L12_1 = (m48_hp0_1 ^ m48_hpr_1 ^ m48_hpx_1) ^ (m51_hp0_1 ^ m51_hpr_1 ^ m51_hpx_1);
  wire sE_L22_0 = sE_L3_0 ^ sE_L12_0;
  wire sE_L22_1 = sE_L3_1 ^ sE_L12_1;
  wire sE_S4_0 = sE_L20_0 ^ sE_L22_0;
  wire sE_S4_1 = sE_L20_1 ^ sE_L22_1;
  wire sE_L10_0 = (m53_hp0_0 ^ m53_hpr_0 ^ m53_hpx_0) ^ sE_L4_0;
  wire sE_L10_1 = (m53_hp0_1 ^ m53_hpr_1 ^ m53_hpx_1) ^ sE_L4_1;
  wire sE_L25_0 = sE_L6_0 ^ sE_L10_0;
  wire sE_L25_1 = sE_L6_1 ^ sE_L10_1;
  wire sE_L17_0 = (m57_hp0_0 ^ m57_hpr_0 ^ m57_hpx_0) ^ sE_L1_0;
  wire sE_L17_1 = (m57_hp0_1 ^ m57_hpr_1 ^ m57_hpx_1) ^ sE_L1_1;
  wire sE_L29_0 = sE_L11_0 ^ sE_L17_0;
  wire sE_L29_1 = sE_L11_1 ^ sE_L17_1;
  wire sE_S5_0 = sE_L25_0 ^ sE_L29_0;
  wire sE_S5_1 = sE_L25_1 ^ sE_L29_1;
  wire sE_L13_0 = (m50_hp0_0 ^ m50_hpr_0 ^ m50_hpx_0) ^ sE_L0_0;
  wire sE_L13_1 = (m50_hp0_1 ^ m50_hpr_1 ^ m50_hpx_1) ^ sE_L0_1;
  wire sE_L8_0 = (m51_hp0_0 ^ m51_hpr_0 ^ m51_hpx_0) ^ (m59_hp0_0 ^ m59_hpr_0 ^ m59_hpx_0);
  wire sE_L8_1 = (m51_hp0_1 ^ m51_hpr_1 ^ m51_hpx_1) ^ (m59_hp0_1 ^ m59_hpr_1 ^ m59_hpx_1);
  wire sE_L27_0 = sE_L8_0 ^ sE_L10_0;
  wire sE_L27_1 = sE_L8_1 ^ sE_L10_1;
  wire sE_S6_0 = ~(sE_L13_0 ^ sE_L27_0);
  wire sE_S6_1 = (sE_L13_1 ^ sE_L27_1);
  wire sE_L18_0 = (m58_hp0_0 ^ m58_hpr_0 ^ m58_hpx_0) ^ sE_L8_0;
  wire sE_L18_1 = (m58_hp0_1 ^ m58_hpr_1 ^ m58_hpx_1) ^ sE_L8_1;
  wire sE_L23_0 = sE_L18_0 ^ sE_L2_0;
  wire sE_L23_1 = sE_L18_1 ^ sE_L2_1;
  wire sE_S7_0 = ~(sE_L6_0 ^ sE_L23_0);
  wire sE_S7_1 = (sE_L6_1 ^ sE_L23_1);
  assign y0[7] = sE_S0_0;
  assign y1[7] = sE_S0_1;
  assign y0[6] = sE_S1_0;
  assign y1[6] = sE_S1_1;
  assign y0[5] = sE_S2_0;
  assign y1[5] = sE_S2_1;
  assign y0[4] = sE_S3_0;
  assign y1[4] = sE_S3_1;
  assign y0[3] = sE_S4_0;
  assign y1[3] = sE_S4_1;
  assign y0[2] = sE_S5_0;
  assign y1[2] = sE_S5_1;
  assign y0[1] = sE_S6_0;
  assign y1[1] = sE_S6_1;
  assign y0[0] = sE_S7_0;
  assign y1[0] = sE_S7_1;
  always @(posedge clk) if (en) begin
    if (!ph) begin                                   // b stages: B, b ^ r, r
      m1_hb_0 <= sA_T6_0;
      m1_hb_1 <= sA_T6_1;
      m1_hr_0 <= sA_T6_1 ^ r[0];
      m1_hr_1 <= sA_T6_0 ^ r[0];
      m1_hR <= r[0];
      m2_hb_0 <= sA_T8_0;
      m2_hb_1 <= sA_T8_1;
      m2_hr_0 <= sA_T8_1 ^ r[1];
      m2_hr_1 <= sA_T8_0 ^ r[1];
      m2_hR <= r[1];
      m4_hb_0 <= xa_0[0];
      m4_hb_1 <= xa_1[0];
      m4_hr_0 <= xa_1[0] ^ r[2];
      m4_hr_1 <= xa_0[0] ^ r[2];
      m4_hR <= r[2];
      m6_hb_0 <= sA_T16_0;
      m6_hb_1 <= sA_T16_1;
      m6_hr_0 <= sA_T16_1 ^ r[3];
      m6_hr_1 <= sA_T16_0 ^ r[3];
      m6_hR <= r[3];
      m7_hb_0 <= sA_T9_0;
      m7_hb_1 <= sA_T9_1;
      m7_hr_0 <= sA_T9_1 ^ r[4];
      m7_hr_1 <= sA_T9_0 ^ r[4];
      m7_hR <= r[4];
      m9_hb_0 <= sA_T17_0;
      m9_hb_1 <= sA_T17_1;
      m9_hr_0 <= sA_T17_1 ^ r[5];
      m9_hr_1 <= sA_T17_0 ^ r[5];
      m9_hR <= r[5];
      m11_hb_0 <= sA_T15_0;
      m11_hb_1 <= sA_T15_1;
      m11_hr_0 <= sA_T15_1 ^ r[6];
      m11_hr_1 <= sA_T15_0 ^ r[6];
      m11_hR <= r[6];
      m12_hb_0 <= sA_T27_0;
      m12_hb_1 <= sA_T27_1;
      m12_hr_0 <= sA_T27_1 ^ r[7];
      m12_hr_1 <= sA_T27_0 ^ r[7];
      m12_hR <= r[7];
      m14_hb_0 <= sA_T10_0;
      m14_hb_1 <= sA_T10_1;
      m14_hr_0 <= sA_T10_1 ^ r[8];
      m14_hr_1 <= sA_T10_0 ^ r[8];
      m14_hR <= r[8];
      m25_hb_0 <= sB_M20_0;
      m25_hb_1 <= sB_M20_1;
      m25_hr_0 <= sB_M20_1 ^ r[9];
      m25_hr_1 <= sB_M20_0 ^ r[9];
      m25_hR <= r[9];
      m31_hb_0 <= sB_M23_0;
      m31_hb_1 <= sB_M23_1;
      m31_hr_0 <= sB_M23_1 ^ r[10];
      m31_hr_1 <= sB_M23_0 ^ r[10];
      m31_hR <= r[10];
      m34_hb_0 <= sB_M22_0;
      m34_hb_1 <= sB_M22_1;
      m34_hr_0 <= sB_M22_1 ^ r[11];
      m34_hr_1 <= sB_M22_0 ^ r[11];
      m34_hR <= r[11];
      m29_hb_0 <= p2_M27_0;
      m29_hb_1 <= p2_M27_1;
      m29_hr_0 <= p2_M27_1 ^ r[12];
      m29_hr_1 <= p2_M27_0 ^ r[12];
      m29_hR <= r[12];
      m30_hb_0 <= p2_M24_0;
      m30_hb_1 <= p2_M24_1;
      m30_hr_0 <= p2_M24_1 ^ r[13];
      m30_hr_1 <= p2_M24_0 ^ r[13];
      m30_hR <= r[13];
      m32_hb_0 <= (m31_hp0_0 ^ m31_hpr_0 ^ m31_hpx_0);
      m32_hb_1 <= (m31_hp0_1 ^ m31_hpr_1 ^ m31_hpx_1);
      m32_hr_0 <= (m31_hp0_1 ^ m31_hpr_1 ^ m31_hpx_1) ^ r[14];
      m32_hr_1 <= (m31_hp0_0 ^ m31_hpr_0 ^ m31_hpx_0) ^ r[14];
      m32_hR <= r[14];
      m35_hb_0 <= (m34_hp0_0 ^ m34_hpr_0 ^ m34_hpx_0);
      m35_hb_1 <= (m34_hp0_1 ^ m34_hpr_1 ^ m34_hpx_1);
      m35_hr_0 <= (m34_hp0_1 ^ m34_hpr_1 ^ m34_hpx_1) ^ r[15];
      m35_hr_1 <= (m34_hp0_0 ^ m34_hpr_0 ^ m34_hpx_0) ^ r[15];
      m35_hR <= r[15];
      m46_hb_0 <= sD_T6_0;
      m46_hb_1 <= sD_T6_1;
      m46_hr_0 <= sD_T6_1 ^ r[16];
      m46_hr_1 <= sD_T6_0 ^ r[16];
      m46_hR <= r[16];
      m47_hb_0 <= sD_T8_0;
      m47_hb_1 <= sD_T8_1;
      m47_hr_0 <= sD_T8_1 ^ r[17];
      m47_hr_1 <= sD_T8_0 ^ r[17];
      m47_hR <= r[17];
      m48_hb_0 <= xd3_0[0];
      m48_hb_1 <= xd3_1[0];
      m48_hr_0 <= xd3_1[0] ^ r[18];
      m48_hr_1 <= xd3_0[0] ^ r[18];
      m48_hR <= r[18];
      m49_hb_0 <= sD_T16_0;
      m49_hb_1 <= sD_T16_1;
      m49_hr_0 <= sD_T16_1 ^ r[19];
      m49_hr_1 <= sD_T16_0 ^ r[19];
      m49_hR <= r[19];
      m50_hb_0 <= sD_T9_0;
      m50_hb_1 <= sD_T9_1;
      m50_hr_0 <= sD_T9_1 ^ r[20];
      m50_hr_1 <= sD_T9_0 ^ r[20];
      m50_hR <= r[20];
      m51_hb_0 <= sD_T17_0;
      m51_hb_1 <= sD_T17_1;
      m51_hr_0 <= sD_T17_1 ^ r[21];
      m51_hr_1 <= sD_T17_0 ^ r[21];
      m51_hR <= r[21];
      m52_hb_0 <= sD_T15_0;
      m52_hb_1 <= sD_T15_1;
      m52_hr_0 <= sD_T15_1 ^ r[22];
      m52_hr_1 <= sD_T15_0 ^ r[22];
      m52_hR <= r[22];
      m53_hb_0 <= sD_T27_0;
      m53_hb_1 <= sD_T27_1;
      m53_hr_0 <= sD_T27_1 ^ r[23];
      m53_hr_1 <= sD_T27_0 ^ r[23];
      m53_hR <= r[23];
      m54_hb_0 <= sD_T10_0;
      m54_hb_1 <= sD_T10_1;
      m54_hr_0 <= sD_T10_1 ^ r[24];
      m54_hr_1 <= sD_T10_0 ^ r[24];
      m54_hR <= r[24];
      m55_hb_0 <= sD_T13_0;
      m55_hb_1 <= sD_T13_1;
      m55_hr_0 <= sD_T13_1 ^ r[25];
      m55_hr_1 <= sD_T13_0 ^ r[25];
      m55_hR <= r[25];
      m56_hb_0 <= sD_T23_0;
      m56_hb_1 <= sD_T23_1;
      m56_hr_0 <= sD_T23_1 ^ r[26];
      m56_hr_1 <= sD_T23_0 ^ r[26];
      m56_hR <= r[26];
      m57_hb_0 <= sD_T19_0;
      m57_hb_1 <= sD_T19_1;
      m57_hr_0 <= sD_T19_1 ^ r[27];
      m57_hr_1 <= sD_T19_0 ^ r[27];
      m57_hR <= r[27];
      m58_hb_0 <= sD_T3_0;
      m58_hb_1 <= sD_T3_1;
      m58_hr_0 <= sD_T3_1 ^ r[28];
      m58_hr_1 <= sD_T3_0 ^ r[28];
      m58_hR <= r[28];
      m59_hb_0 <= sD_T22_0;
      m59_hb_1 <= sD_T22_1;
      m59_hr_0 <= sD_T22_1 ^ r[29];
      m59_hr_1 <= sD_T22_0 ^ r[29];
      m59_hR <= r[29];
      m60_hb_0 <= sD_T20_0;
      m60_hb_1 <= sD_T20_1;
      m60_hr_0 <= sD_T20_1 ^ r[30];
      m60_hr_1 <= sD_T20_0 ^ r[30];
      m60_hR <= r[30];
      m61_hb_0 <= sD_T1_0;
      m61_hb_1 <= sD_T1_1;
      m61_hr_0 <= sD_T1_1 ^ r[31];
      m61_hr_1 <= sD_T1_0 ^ r[31];
      m61_hR <= r[31];
      m62_hb_0 <= sD_T4_0;
      m62_hb_1 <= sD_T4_1;
      m62_hr_0 <= sD_T4_1 ^ r[32];
      m62_hr_1 <= sD_T4_0 ^ r[32];
      m62_hR <= r[32];
      m63_hb_0 <= sD_T2_0;
      m63_hb_1 <= sD_T2_1;
      m63_hr_0 <= sD_T2_1 ^ r[33];
      m63_hr_1 <= sD_T2_0 ^ r[33];
      m63_hR <= r[33];
    end else begin                                   // a stages, the input, the pass registers
      xa_0 <= x0;
      xa_1 <= x1;
      xd1_0 <= xa_0;
      xd1_1 <= xa_1;
      xd2_0 <= xd1_0;
      xd2_1 <= xd1_1;
      xd3_0 <= xd2_0;
      xd3_1 <= xd2_1;
      m1_hp0_0 <= sA_T13_0 & m1_hb_0;
      m1_hp0_1 <= sA_T13_1 & m1_hb_1;
      m1_hpr_0 <= (~sA_T13_0) & m1_hR;
      m1_hpr_1 <= (~sA_T13_1) & m1_hR;
      m1_hpx_0 <= sA_T13_0 & m1_hr_0;
      m1_hpx_1 <= sA_T13_1 & m1_hr_1;
      m2_hp0_0 <= sA_T23_0 & m2_hb_0;
      m2_hp0_1 <= sA_T23_1 & m2_hb_1;
      m2_hpr_0 <= (~sA_T23_0) & m2_hR;
      m2_hpr_1 <= (~sA_T23_1) & m2_hR;
      m2_hpx_0 <= sA_T23_0 & m2_hr_0;
      m2_hpx_1 <= sA_T23_1 & m2_hr_1;
      m4_hp0_0 <= sA_T19_0 & m4_hb_0;
      m4_hp0_1 <= sA_T19_1 & m4_hb_1;
      m4_hpr_0 <= (~sA_T19_0) & m4_hR;
      m4_hpr_1 <= (~sA_T19_1) & m4_hR;
      m4_hpx_0 <= sA_T19_0 & m4_hr_0;
      m4_hpx_1 <= sA_T19_1 & m4_hr_1;
      m6_hp0_0 <= sA_T3_0 & m6_hb_0;
      m6_hp0_1 <= sA_T3_1 & m6_hb_1;
      m6_hpr_0 <= (~sA_T3_0) & m6_hR;
      m6_hpr_1 <= (~sA_T3_1) & m6_hR;
      m6_hpx_0 <= sA_T3_0 & m6_hr_0;
      m6_hpx_1 <= sA_T3_1 & m6_hr_1;
      m7_hp0_0 <= sA_T22_0 & m7_hb_0;
      m7_hp0_1 <= sA_T22_1 & m7_hb_1;
      m7_hpr_0 <= (~sA_T22_0) & m7_hR;
      m7_hpr_1 <= (~sA_T22_1) & m7_hR;
      m7_hpx_0 <= sA_T22_0 & m7_hr_0;
      m7_hpx_1 <= sA_T22_1 & m7_hr_1;
      m9_hp0_0 <= sA_T20_0 & m9_hb_0;
      m9_hp0_1 <= sA_T20_1 & m9_hb_1;
      m9_hpr_0 <= (~sA_T20_0) & m9_hR;
      m9_hpr_1 <= (~sA_T20_1) & m9_hR;
      m9_hpx_0 <= sA_T20_0 & m9_hr_0;
      m9_hpx_1 <= sA_T20_1 & m9_hr_1;
      m11_hp0_0 <= sA_T1_0 & m11_hb_0;
      m11_hp0_1 <= sA_T1_1 & m11_hb_1;
      m11_hpr_0 <= (~sA_T1_0) & m11_hR;
      m11_hpr_1 <= (~sA_T1_1) & m11_hR;
      m11_hpx_0 <= sA_T1_0 & m11_hr_0;
      m11_hpx_1 <= sA_T1_1 & m11_hr_1;
      m12_hp0_0 <= sA_T4_0 & m12_hb_0;
      m12_hp0_1 <= sA_T4_1 & m12_hb_1;
      m12_hpr_0 <= (~sA_T4_0) & m12_hR;
      m12_hpr_1 <= (~sA_T4_1) & m12_hR;
      m12_hpx_0 <= sA_T4_0 & m12_hr_0;
      m12_hpx_1 <= sA_T4_1 & m12_hr_1;
      m14_hp0_0 <= sA_T2_0 & m14_hb_0;
      m14_hp0_1 <= sA_T2_1 & m14_hb_1;
      m14_hpr_0 <= (~sA_T2_0) & m14_hR;
      m14_hpr_1 <= (~sA_T2_1) & m14_hR;
      m14_hpx_0 <= sA_T2_0 & m14_hr_0;
      m14_hpx_1 <= sA_T2_1 & m14_hr_1;
      m25_hp0_0 <= sB_M22_0 & m25_hb_0;
      m25_hp0_1 <= sB_M22_1 & m25_hb_1;
      m25_hpr_0 <= (~sB_M22_0) & m25_hR;
      m25_hpr_1 <= (~sB_M22_1) & m25_hR;
      m25_hpx_0 <= sB_M22_0 & m25_hr_0;
      m25_hpx_1 <= sB_M22_1 & m25_hr_1;
      m31_hp0_0 <= sB_M20_0 & m31_hb_0;
      m31_hp0_1 <= sB_M20_1 & m31_hb_1;
      m31_hpr_0 <= (~sB_M20_0) & m31_hR;
      m31_hpr_1 <= (~sB_M20_1) & m31_hR;
      m31_hpx_0 <= sB_M20_0 & m31_hr_0;
      m31_hpx_1 <= sB_M20_1 & m31_hr_1;
      m34_hp0_0 <= sB_M21_0 & m34_hb_0;
      m34_hp0_1 <= sB_M21_1 & m34_hb_1;
      m34_hpr_0 <= (~sB_M21_0) & m34_hR;
      m34_hpr_1 <= (~sB_M21_1) & m34_hR;
      m34_hpx_0 <= sB_M21_0 & m34_hr_0;
      m34_hpx_1 <= sB_M21_1 & m34_hr_1;
      p2_M21_0 <= sB_M21_0;
      p2_M21_1 <= sB_M21_1;
      p2_M23_0 <= sB_M23_0;
      p2_M23_1 <= sB_M23_1;
      p2_M24_0 <= sB_M24_0;
      p2_M24_1 <= sB_M24_1;
      p2_M27_0 <= sB_M27_0;
      p2_M27_1 <= sB_M27_1;
      m29_hp0_0 <= sC_M28_0 & m29_hb_0;
      m29_hp0_1 <= sC_M28_1 & m29_hb_1;
      m29_hpr_0 <= (~sC_M28_0) & m29_hR;
      m29_hpr_1 <= (~sC_M28_1) & m29_hR;
      m29_hpx_0 <= sC_M28_0 & m29_hr_0;
      m29_hpx_1 <= sC_M28_1 & m29_hr_1;
      m30_hp0_0 <= sC_M26_0 & m30_hb_0;
      m30_hp0_1 <= sC_M26_1 & m30_hb_1;
      m30_hpr_0 <= (~sC_M26_0) & m30_hR;
      m30_hpr_1 <= (~sC_M26_1) & m30_hR;
      m30_hpx_0 <= sC_M26_0 & m30_hr_0;
      m30_hpx_1 <= sC_M26_1 & m30_hr_1;
      m32_hp0_0 <= p2_M27_0 & m32_hb_0;
      m32_hp0_1 <= p2_M27_1 & m32_hb_1;
      m32_hpr_0 <= (~p2_M27_0) & m32_hR;
      m32_hpr_1 <= (~p2_M27_1) & m32_hR;
      m32_hpx_0 <= p2_M27_0 & m32_hr_0;
      m32_hpx_1 <= p2_M27_1 & m32_hr_1;
      m35_hp0_0 <= p2_M24_0 & m35_hb_0;
      m35_hp0_1 <= p2_M24_1 & m35_hb_1;
      m35_hpr_0 <= (~p2_M24_0) & m35_hR;
      m35_hpr_1 <= (~p2_M24_1) & m35_hR;
      m35_hpx_0 <= p2_M24_0 & m35_hr_0;
      m35_hpx_1 <= p2_M24_1 & m35_hr_1;
      p3_M21_0 <= p2_M21_0;
      p3_M21_1 <= p2_M21_1;
      p3_M23_0 <= p2_M23_0;
      p3_M23_1 <= p2_M23_1;
      p3_M33_0 <= sC_M33_0;
      p3_M33_1 <= sC_M33_1;
      p3_M36_0 <= sC_M36_0;
      p3_M36_1 <= sC_M36_1;
      m46_hp0_0 <= sD_M44_0 & m46_hb_0;
      m46_hp0_1 <= sD_M44_1 & m46_hb_1;
      m46_hpr_0 <= (~sD_M44_0) & m46_hR;
      m46_hpr_1 <= (~sD_M44_1) & m46_hR;
      m46_hpx_0 <= sD_M44_0 & m46_hr_0;
      m46_hpx_1 <= sD_M44_1 & m46_hr_1;
      m47_hp0_0 <= sD_M40_0 & m47_hb_0;
      m47_hp0_1 <= sD_M40_1 & m47_hb_1;
      m47_hpr_0 <= (~sD_M40_0) & m47_hR;
      m47_hpr_1 <= (~sD_M40_1) & m47_hR;
      m47_hpx_0 <= sD_M40_0 & m47_hr_0;
      m47_hpx_1 <= sD_M40_1 & m47_hr_1;
      m48_hp0_0 <= sD_M39_0 & m48_hb_0;
      m48_hp0_1 <= sD_M39_1 & m48_hb_1;
      m48_hpr_0 <= (~sD_M39_0) & m48_hR;
      m48_hpr_1 <= (~sD_M39_1) & m48_hR;
      m48_hpx_0 <= sD_M39_0 & m48_hr_0;
      m48_hpx_1 <= sD_M39_1 & m48_hr_1;
      m49_hp0_0 <= sD_M43_0 & m49_hb_0;
      m49_hp0_1 <= sD_M43_1 & m49_hb_1;
      m49_hpr_0 <= (~sD_M43_0) & m49_hR;
      m49_hpr_1 <= (~sD_M43_1) & m49_hR;
      m49_hpx_0 <= sD_M43_0 & m49_hr_0;
      m49_hpx_1 <= sD_M43_1 & m49_hr_1;
      m50_hp0_0 <= sD_M38_0 & m50_hb_0;
      m50_hp0_1 <= sD_M38_1 & m50_hb_1;
      m50_hpr_0 <= (~sD_M38_0) & m50_hR;
      m50_hpr_1 <= (~sD_M38_1) & m50_hR;
      m50_hpx_0 <= sD_M38_0 & m50_hr_0;
      m50_hpx_1 <= sD_M38_1 & m50_hr_1;
      m51_hp0_0 <= sD_M37_0 & m51_hb_0;
      m51_hp0_1 <= sD_M37_1 & m51_hb_1;
      m51_hpr_0 <= (~sD_M37_0) & m51_hR;
      m51_hpr_1 <= (~sD_M37_1) & m51_hR;
      m51_hpx_0 <= sD_M37_0 & m51_hr_0;
      m51_hpx_1 <= sD_M37_1 & m51_hr_1;
      m52_hp0_0 <= sD_M42_0 & m52_hb_0;
      m52_hp0_1 <= sD_M42_1 & m52_hb_1;
      m52_hpr_0 <= (~sD_M42_0) & m52_hR;
      m52_hpr_1 <= (~sD_M42_1) & m52_hR;
      m52_hpx_0 <= sD_M42_0 & m52_hr_0;
      m52_hpx_1 <= sD_M42_1 & m52_hr_1;
      m53_hp0_0 <= sD_M45_0 & m53_hb_0;
      m53_hp0_1 <= sD_M45_1 & m53_hb_1;
      m53_hpr_0 <= (~sD_M45_0) & m53_hR;
      m53_hpr_1 <= (~sD_M45_1) & m53_hR;
      m53_hpx_0 <= sD_M45_0 & m53_hr_0;
      m53_hpx_1 <= sD_M45_1 & m53_hr_1;
      m54_hp0_0 <= sD_M41_0 & m54_hb_0;
      m54_hp0_1 <= sD_M41_1 & m54_hb_1;
      m54_hpr_0 <= (~sD_M41_0) & m54_hR;
      m54_hpr_1 <= (~sD_M41_1) & m54_hR;
      m54_hpx_0 <= sD_M41_0 & m54_hr_0;
      m54_hpx_1 <= sD_M41_1 & m54_hr_1;
      m55_hp0_0 <= sD_M44_0 & m55_hb_0;
      m55_hp0_1 <= sD_M44_1 & m55_hb_1;
      m55_hpr_0 <= (~sD_M44_0) & m55_hR;
      m55_hpr_1 <= (~sD_M44_1) & m55_hR;
      m55_hpx_0 <= sD_M44_0 & m55_hr_0;
      m55_hpx_1 <= sD_M44_1 & m55_hr_1;
      m56_hp0_0 <= sD_M40_0 & m56_hb_0;
      m56_hp0_1 <= sD_M40_1 & m56_hb_1;
      m56_hpr_0 <= (~sD_M40_0) & m56_hR;
      m56_hpr_1 <= (~sD_M40_1) & m56_hR;
      m56_hpx_0 <= sD_M40_0 & m56_hr_0;
      m56_hpx_1 <= sD_M40_1 & m56_hr_1;
      m57_hp0_0 <= sD_M39_0 & m57_hb_0;
      m57_hp0_1 <= sD_M39_1 & m57_hb_1;
      m57_hpr_0 <= (~sD_M39_0) & m57_hR;
      m57_hpr_1 <= (~sD_M39_1) & m57_hR;
      m57_hpx_0 <= sD_M39_0 & m57_hr_0;
      m57_hpx_1 <= sD_M39_1 & m57_hr_1;
      m58_hp0_0 <= sD_M43_0 & m58_hb_0;
      m58_hp0_1 <= sD_M43_1 & m58_hb_1;
      m58_hpr_0 <= (~sD_M43_0) & m58_hR;
      m58_hpr_1 <= (~sD_M43_1) & m58_hR;
      m58_hpx_0 <= sD_M43_0 & m58_hr_0;
      m58_hpx_1 <= sD_M43_1 & m58_hr_1;
      m59_hp0_0 <= sD_M38_0 & m59_hb_0;
      m59_hp0_1 <= sD_M38_1 & m59_hb_1;
      m59_hpr_0 <= (~sD_M38_0) & m59_hR;
      m59_hpr_1 <= (~sD_M38_1) & m59_hR;
      m59_hpx_0 <= sD_M38_0 & m59_hr_0;
      m59_hpx_1 <= sD_M38_1 & m59_hr_1;
      m60_hp0_0 <= sD_M37_0 & m60_hb_0;
      m60_hp0_1 <= sD_M37_1 & m60_hb_1;
      m60_hpr_0 <= (~sD_M37_0) & m60_hR;
      m60_hpr_1 <= (~sD_M37_1) & m60_hR;
      m60_hpx_0 <= sD_M37_0 & m60_hr_0;
      m60_hpx_1 <= sD_M37_1 & m60_hr_1;
      m61_hp0_0 <= sD_M42_0 & m61_hb_0;
      m61_hp0_1 <= sD_M42_1 & m61_hb_1;
      m61_hpr_0 <= (~sD_M42_0) & m61_hR;
      m61_hpr_1 <= (~sD_M42_1) & m61_hR;
      m61_hpx_0 <= sD_M42_0 & m61_hr_0;
      m61_hpx_1 <= sD_M42_1 & m61_hr_1;
      m62_hp0_0 <= sD_M45_0 & m62_hb_0;
      m62_hp0_1 <= sD_M45_1 & m62_hb_1;
      m62_hpr_0 <= (~sD_M45_0) & m62_hR;
      m62_hpr_1 <= (~sD_M45_1) & m62_hR;
      m62_hpx_0 <= sD_M45_0 & m62_hr_0;
      m62_hpx_1 <= sD_M45_1 & m62_hr_1;
      m63_hp0_0 <= sD_M41_0 & m63_hb_0;
      m63_hp0_1 <= sD_M41_1 & m63_hb_1;
      m63_hpr_0 <= (~sD_M41_0) & m63_hR;
      m63_hpr_1 <= (~sD_M41_1) & m63_hR;
      m63_hpx_0 <= sD_M41_0 & m63_hr_0;
      m63_hpx_1 <= sD_M41_1 & m63_hr_1;
    end
  end
  // ---- generated by scripts/pqse_gcm.py gen: end ----
endmodule


`ifndef PQSE_AES_SMALL   // else pqse_aes_small.v
module pqse_aes (
  input  wire        clk,
  input  wire        rst,
  input  wire        start,
  input  wire [3:0]  op_in,
  output wire        busy,
  output reg         bad_set,
  output wire        fault,       // a complemented copy disagrees
  // I/O buffer (read latency 1)
  output reg         bre,
  output reg  [8:0]  braddr,
  input  wire [63:0] brdata,
  output reg         bwe,
  output reg  [8:0]  bwaddr,
  output reg  [63:0] bwdata,
  // seed RAM (read latency 1): one RAM per share
  output reg         sre,
  output reg  [5:0]  sraddr,
  input  wire [63:0] srd0,
  input  wire [63:0] srd1,
  output reg         swe,
  output reg  [5:0]  swaddr,
  output reg  [63:0] swd0,
  output reg  [63:0] swd1,
  // PRNG: at most one take per 2 clocks, fresh word each
  input  wire [63:0] rnd,
  output wire        rnd_take
);
  `include "pqse_defs.vh"

  localparam [5:0] S_IDLE = 6'd0,
                   // block encryption: rounds 0..14, then back to ret
                   S_ARK0 = 6'd1,  S_ARK1 = 6'd2,  S_ARK2 = 6'd3,  S_SB  = 6'd4,  S_SR  = 6'd5,
                   S_MC   = 6'd6,
                   S_HD0  = 6'd7,  S_HD1  = 6'd8,  S_ONE = 6'd9,
                   // key expansion
                   S_KC   = 6'd10, S_KR   = 6'd11, S_KL  = 6'd12, S_KS  = 6'd13, S_KX  = 6'd14,
                   S_KY   = 6'd15, S_KW   = 6'd16,
                   // H, E(K, J0), CTR
                   S_BL0  = 6'd17, S_BL1  = 6'd18, S_BL2 = 6'd19, S_OH  = 6'd20, S_CK0 = 6'd21,
                   S_CK1  = 6'd22, S_CK2  = 6'd23, S_CZ  = 6'd24,
                   // GHASH
                   S_GI   = 6'd25, S_GX0  = 6'd26, S_GX1 = 6'd27, S_GX2 = 6'd28, S_GHA = 6'd29,
                   S_GPA  = 6'd30, S_GWA  = 6'd31, S_GHB = 6'd32, S_GPB = 6'd33, S_GYB = 6'd34,
                   S_GWB  = 6'd35,
                   // TAG, WIPE
                   S_TG   = 6'd36, S_WP   = 6'd37;
  // seed lanes: H0 (48, 49), H1 (50, 51), GHASH / T (52, 53), E(K, J0) (54, 55), the key (52..55)
  localparam [5:0] A_H0 = 6'd48, A_H1 = 6'd50, A_Y = 6'd52, A_EJ = 6'd54, A_KEY = 6'd52;

  // ---- control ----
  reg         busy_r, busy_n;
  reg  [3:0]  op, op_n;
  reg  [5:0]  s, s_n;          // state, complemented copy
  reg  [5:0]  ret;             // return state after block encryption
  reg  [3:0]  rd, rd_n;        // round, complemented copy
  reg         ph;              // S-box phase (free-running)
  reg  [4:0]  bi, wi;          // S-box: bytes in, bytes written back
  reg  [2:0]  cnt;             // step within a state
  reg  [1:0]  col;             // MixColumns column
  reg  [6:0]  blk;             // block of the payload (CTR) or of the GHASH source
  reg  [6:0]  gi;              // GHASH: bit of X
  reg  [1:0]  gsrc;            // GHASH source: 0 AAD, 1 payload, 2 lengths, 3 done
  reg  [4:0]  kl;              // key expansion: lane 4..29 (words 2 kl, 2 kl + 1)
  reg  [6:0]  zl;              // zero fill / wipe: lane
  reg  [10:0] plen;            // P (bytes)
  reg  [8:0]  alen;            // A (bytes)
  reg         ksrc;
  assign busy = start | busy_r;

  // ---- data ----
  reg  [127:0] st0, st1;       // AES state / key-expansion words / GHASH X, per share
  reg  [63:0]  ks0, ks1;       // keystream lane, per share (CTR only)
  reg  [127:0] VA, VB;         // GHASH: H0 x^i (pass A), H1 x^i (pass B); one of them 0
  reg  [127:0] Z0, Z1;         // GHASH: X0 H.., X1 H..
  reg  [63:0]  wz0, wz1;       // GHASH: Z0 / Z1 lane staged for the seed RAM

  // ---- helpers ----
  function [7:0] xt(input [7:0] a);
    xt = {a[6:0], 1'b0} ^ (a[7] ? 8'h1B : 8'h00);
  endfunction
  function [31:0] mixcol(input [31:0] c);           // bytes: row r at [8r +: 8]
    reg [7:0] a0, a1, a2, a3;
    begin
      a0 = c[7:0]; a1 = c[15:8]; a2 = c[23:16]; a3 = c[31:24];
      mixcol = {xt(a0) ^ a0 ^ a1 ^ a2 ^ xt(a3),
                a0 ^ a1 ^ xt(a2) ^ xt(a3) ^ a3,
                a0 ^ xt(a1) ^ xt(a2) ^ a2 ^ a3,
                xt(a0) ^ xt(a1) ^ a1 ^ a2 ^ a3};
    end
  endfunction
  function [127:0] shrows(input [127:0] a);         // byte 4c + r := byte 4((c + r) mod 4) + r
    integer c, r;
    begin
      for (c = 0; c < 4; c = c + 1)
        for (r = 0; r < 4; r = r + 1)
          shrows[8 * (4 * c + r) +: 8] = a[8 * (4 * ((c + r) % 4) + r) +: 8];
    end
  endfunction
  // lane <-> GCM bit string: bits reversed per byte (string bit 8j + t = bit 7 - t of byte j)
  function [63:0] lg(input [63:0] l);
    integer j, t;
    begin
      for (j = 0; j < 8; j = j + 1)
        for (t = 0; t < 8; t = t + 1)
          lg[8 * j + t] = l[8 * j + 7 - t];
    end
  endfunction
  // V x in GCM's bit order (SP 800-38D 6.3): V >> 1, xor R = 11100001 || 0^120 if V_127
  function [127:0] mulx(input [127:0] v);
    begin
      mulx = {v[126:0], 1'b0};
      mulx[0] = v[127];
      mulx[1] = v[0] ^ v[127];
      mulx[2] = v[1] ^ v[127];
      mulx[7] = v[6] ^ v[127];
    end
  endfunction
  // mask for lane ln of an n-byte buffer: FF where byte index < n
  function [63:0] bmask(input [10:0] n, input [6:0] ln);
    integer b;
    begin
      for (b = 0; b < 8; b = b + 1)
        bmask[8 * b +: 8] = ({1'b0, ln, 3'd0} + b < {1'b0, n}) ? 8'hFF : 8'h00;
    end
  endfunction
  // round-key lane L (0..29) -> seed address: entries 3..7, then 9..11 (8 is E_SK)
  function [5:0] rkl(input [4:0] L);
    rkl = (L < 5'd20) ? 6'd12 + {1'b0, L} : 6'd16 + {1'b0, L};
  endfunction

  wire [6:0]  nblk  = ({1'b0, plen} + 12'd15) >> 4;         // payload blocks (<= 64)
  wire [4:0]  ablk  = ({1'b0, alen} + 10'd15) >> 4;         // AAD blocks (<= 16)
  wire [6:0]  gnb   = (gsrc == 2'd0) ? {2'd0, ablk} : (gsrc == 2'd1) ? nblk : 7'd1;
  wire [15:0] abits = {4'd0, alen, 3'd0};
  wire [15:0] pbits = {2'd0, plen, 3'd0};
  wire [63:0] len0  = {abits[7:0], abits[15:8], 48'd0};    // [len(A)]_64, big-endian
  wire [63:0] len1  = {pbits[7:0], pbits[15:8], 48'd0};    // [len(C)]_64
  wire [8:0]  gla   = (gsrc == 2'd0) ? B_GAAD : B_GMSG;     // GHASH data lanes
  wire [63:0] gm0   = (gsrc == 2'd0) ? bmask({2'd0, alen}, {blk[5:0], 1'b0}) : bmask(plen, {blk[5:0], 1'b0});
  wire [63:0] gm1   = (gsrc == 2'd0) ? bmask({2'd0, alen}, {blk[5:0], 1'b1}) : bmask(plen, {blk[5:0], 1'b1});
  wire [31:0] ctr   = (op == AO_J0) ? 32'd1 : 32'd2 + {25'd0, blk};
  wire        rot   = (kl[1:0] == 2'd0);                     // key expansion: i mod 8 = 0
  wire [7:0]  rcon  = 8'd1 << (kl[4:2] - 3'd1);
  wire [127:0] V    = VA ^ VB;
  wire        xb0   = st0[{gi[6:3], ~gi[2:0]}];             // GCM string bit gi of X0, X1
  wire        xb1   = st1[{gi[6:3], ~gi[2:0]}];

  // ---- the masked S-box ----
  wire        sb_en = busy_r && ((s == S_SB) || (s == S_KS));
  wire        sb_ks = (s == S_KS);
  wire [1:0]  kb    = rot ? bi[1:0] + 2'd1 : bi[1:0];      // SubWord(RotWord): byte j from j + 1
  wire [3:0]  sbs   = sb_ks ? {2'b00, kb} : bi[3:0];        // the byte that goes in
  wire        iss   = sb_ks ? (bi < 5'd4) : (bi < 5'd16);
  wire [3:0]  dst   = sb_ks ? {2'b01, bi[1:0]} : bi[3:0];   // where its result goes
  wire [7:0]  y0, y1;
  pqse_aes_sbox u_sb (.clk(clk), .en(sb_en), .ph(ph), .x0(st0[{sbs, 3'd0} +: 8]),
                      .x1(st1[{sbs, 3'd0} +: 8]), .r(rnd[33:0]), .y0(y0), .y1(y1));
  reg  [4:0]  qv;              // in flight: valid, at ph 1 clocks (out after 4 shifts)
  reg  [19:0] qd;              // ... and their destination bytes
  wire        wb    = sb_en && !ph && qv[4];                  // a result to write back
  wire [3:0]  wdst  = qd[19:16];
  // GHASH: R for the accumulators, two takes 2 clocks apart, before each pass
  assign rnd_take = (sb_en && !ph) || (((s == S_GHA) || (s == S_GHB)) && ((cnt == 3'd2) || (cnt == 3'd4)));

  // ---- faults ----
  assign fault = (busy_r != ~busy_n) || (busy_r && (op != ~op_n)) || (s != ~s_n) || (rd != ~rd_n);

  // ---- combinational: buffer, seed RAM, BAD ----
  always @* begin
    bre = 1'b0; braddr = 9'd0; bwe = 1'b0; bwaddr = 9'd0; bwdata = 64'd0;
    sre = 1'b0; sraddr = 6'd0; swe = 1'b0; swaddr = 6'd0; swd0 = 64'd0; swd1 = 64'd0;
    bad_set = 1'b0;
    if (busy_r)
      case (s)
        S_HD0: begin bre = 1'b1; braddr = B_GHDR; end
        S_HD1: bad_set = (brdata[15:0] > 16'd1024) || (brdata[31:16] > 16'd256) ||
                         (brdata[63:33] != 31'd0);
        S_ONE: bad_set = (op == AO_KSRC) && ksrc;
        S_ARK0: begin sre = 1'b1; sraddr = rkl({rd, 1'b0}); end
        S_ARK1: begin sre = 1'b1; sraddr = rkl({rd, 1'b1}); end
        // key expansion: key lanes -> round keys 0, 1
        S_KC: begin
          if (cnt <= 3'd3) begin sre = 1'b1; sraddr = A_KEY + {3'd0, cnt}; end
          if (cnt >= 3'd1) begin swe = 1'b1; swaddr = rkl({2'd0, cnt - 3'd1}); swd0 = srd0; swd1 = srd1; end
        end
        S_KR: begin sre = 1'b1; sraddr = rkl(kl - 5'd4); end
        S_KW: begin swe = 1'b1; swaddr = rkl(kl); swd0 = st0[127:64]; swd1 = st1[127:64]; end
        // block loads, results
        S_BL0: if ((op != AO_H) && !((op == AO_CTR) && (blk == nblk))) begin bre = 1'b1; braddr = B_GIV; end
        S_BL1: begin bre = 1'b1; braddr = B_GIV + 9'd1; end
        S_OH: begin                                           // H: share 0, then share 1
          swe = 1'b1; swaddr = ((op == AO_H) ? A_H0 : A_EJ) + {4'd0, cnt[1:0]};
          if ((op != AO_H) || !cnt[1]) swd0 = cnt[0] ? st0[127:64] : st0[63:0];
          if ((op != AO_H) || cnt[1])  swd1 = cnt[0] ? st1[127:64] : st1[63:0];
        end
        S_CK0: begin bre = 1'b1; braddr = B_GMSG + {1'b0, blk, 1'b0}; end
        S_CK1: begin
          bwe = 1'b1; bwaddr = B_GMSG + {1'b0, blk, 1'b0};
          bwdata = (brdata ^ ks0 ^ ks1) & bmask(plen, {blk[5:0], 1'b0});
          bre = 1'b1; braddr = B_GMSG + {1'b0, blk, 1'b1};
        end
        S_CK2: begin
          bwe = 1'b1; bwaddr = B_GMSG + {1'b0, blk, 1'b1};
          bwdata = (brdata ^ ks0 ^ ks1) & bmask(plen, {blk[5:0], 1'b1});
        end
        S_CZ: begin bwe = 1'b1; bwaddr = B_GMSG + {2'd0, zl}; end
        // GHASH
        S_GI: begin swe = 1'b1; swaddr = A_Y + {5'd0, cnt[0]}; end
        S_GX0: if ((gsrc != 2'd3) && (blk != gnb)) begin
          sre = 1'b1; sraddr = A_Y;
          bre = 1'b1; braddr = gla + {1'b0, blk, 1'b0};
        end
        S_GX1: begin
          sre = 1'b1; sraddr = A_Y + 6'd1;
          bre = 1'b1; braddr = gla + {1'b0, blk, 1'b1};
        end
        S_GHA, S_GHB: if (cnt <= 3'd1) begin
          sre = 1'b1; sraddr = ((s == S_GHA) ? A_H0 : A_H1) + {5'd0, cnt[0]};
        end
        S_GWA, S_GWB: if (cnt != 3'd0) begin                  // from the staging registers
          swe = 1'b1; swaddr = A_Y + {5'd0, cnt[1]}; swd0 = wz0; swd1 = wz1;
        end
        S_GYB: if (cnt <= 3'd1) begin sre = 1'b1; sraddr = A_Y + {5'd0, cnt[0]}; end
        // T = E(K, J0) ^ GHASH
        S_TG: begin
          case (cnt)
            3'd0: begin sre = 1'b1; sraddr = A_EJ; end
            3'd1: begin sre = 1'b1; sraddr = A_Y; end
            3'd2: begin sre = 1'b1; sraddr = A_EJ + 6'd1; end
            3'd3: begin sre = 1'b1; sraddr = A_Y + 6'd1; end
            3'd5: begin swe = 1'b1; swaddr = A_Y; swd0 = st0[63:0]; swd1 = st1[63:0]; end
            3'd6: begin swe = 1'b1; swaddr = A_Y + 6'd1; swd0 = st0[127:64]; swd1 = st1[127:64]; end
            default: ;
          endcase
        end
        S_WP: begin swe = 1'b1; swaddr = (zl < 7'd20) ? 6'd12 + zl[5:0] : 6'd16 + zl[5:0]; end   // 12..31, 36..55
        default: ;
      endcase
  end

  // ---- sequential ----
  task go(input [5:0] t);
    begin s <= t; s_n <= ~t; end
  endtask
  task setrd(input [3:0] r);
    begin rd <= r; rd_n <= ~r; end
  endtask
  task done;
    begin busy_r <= 1'b0; busy_n <= 1'b1; s <= S_IDLE; s_n <= ~S_IDLE; end
  endtask

  always @(posedge clk) begin
    if (rst) ph <= 1'b0;
    else     ph <= ~ph;
  end

  always @(posedge clk) begin
    if (rst) begin
      busy_r <= 1'b0; busy_n <= 1'b1; op <= 4'd0; op_n <= 4'hF;
      s <= S_IDLE; s_n <= ~S_IDLE; rd <= 4'd0; rd_n <= 4'hF;
      qv <= 5'd0; cnt <= 3'd0;
    end else begin
      // S-box queue shifts with the pipeline (enabled ph 1 clocks)
      if (sb_en && ph) begin
        qv <= {qv[3:0], iss};
        qd <= {qd[15:0], dst};
      end
      if (start) begin
        op <= op_in; op_n <= ~op_in; busy_r <= 1'b1; busy_n <= 1'b0; cnt <= 3'd0;
        blk <= 7'd0; zl <= 7'd0; qv <= 5'd0;
        case (op_in)
          AO_HDR:  go(S_HD0);
          AO_KEXP: go(S_KC);
          AO_H, AO_J0, AO_CTR: go(S_BL0);
          AO_GH:   go(S_GI);
          AO_TAG:  go(S_TG);
          AO_WIPE: go(S_WP);
          default: go(S_ONE);                                 // KSRC; unknown op ends
        endcase
      end else if (busy_r) begin
        case (s)
          S_HD0: go(S_HD1);
          S_HD1: begin plen <= brdata[10:0]; alen <= brdata[24:16]; ksrc <= brdata[32]; done; end
          S_ONE: done;
          // ======== block encryption ========
          S_ARK0: go(S_ARK1);
          S_ARK1: begin st0[63:0] <= st0[63:0] ^ srd0; st1[63:0] <= st1[63:0] ^ srd1; go(S_ARK2); end
          S_ARK2: begin
            st0[127:64] <= st0[127:64] ^ srd0; st1[127:64] <= st1[127:64] ^ srd1;
            if (rd == 4'd14) go(ret);
            else begin setrd(rd + 4'd1); bi <= 5'd0; wi <= 5'd0; go(S_SB); end
          end
          S_SB: begin                                         // SubBytes, in place
            if (ph && iss) bi <= bi + 5'd1;
            if (wb) begin
              st0[{wdst, 3'd0} +: 8] <= y0; st1[{wdst, 3'd0} +: 8] <= y1;
              wi <= wi + 5'd1;
              if (wi == 5'd15) begin qv <= 5'd0; go(S_SR); end    // (queue empty)
            end
          end
          S_SR: begin
            st0 <= shrows(st0); st1 <= shrows(st1); col <= 2'd0;
            go((rd == 4'd14) ? S_ARK0 : S_MC);
          end
          S_MC: begin
            st0[{col, 5'd0} +: 32] <= mixcol(st0[{col, 5'd0} +: 32]);
            st1[{col, 5'd0} +: 32] <= mixcol(st1[{col, 5'd0} +: 32]);
            col <= col + 2'd1;
            if (col == 2'd3) go(S_ARK0);
          end
          // ======== key expansion (FIPS 197 5.2, Nk = 8): a lane = two words ========
          S_KC: begin                                         // key -> round keys 0, 1
            cnt <= cnt + 3'd1;
            if (cnt == 3'd4) begin
              st0[31:0] <= srd0[63:32]; st1[31:0] <= srd1[63:32];   // w[7]
              kl <= 5'd4; go(S_KR);
            end
          end
          S_KR: go(S_KL);                                     // (w[i - 8], w[i - 7] read)
          S_KL: begin
            st0[127:64] <= srd0; st1[127:64] <= srd1;
            if (!kl[0]) begin bi <= 5'd0; wi <= 5'd0; go(S_KS); end   // i mod 8 = 0 or 4
            else begin st0[63:32] <= st0[31:0]; st1[63:32] <= st1[31:0]; go(S_KX); end
          end
          S_KS: begin                                         // SubWord (RotWord) -> bytes 4..7
            if (ph && iss) bi <= bi + 5'd1;
            if (wb) begin
              st0[{wdst, 3'd0} +: 8] <= y0; st1[{wdst, 3'd0} +: 8] <= y1;
              wi <= wi + 5'd1;
              if (wi == 5'd3) begin qv <= 5'd0; go(S_KX); end
            end
          end
          S_KX: begin                                         // w[i] = w[i - 8] ^ temp (^ Rcon)
            st0[95:64] <= st0[95:64] ^ st0[63:32] ^ {24'd0, (rot ? rcon : 8'd0)};
            st1[95:64] <= st1[95:64] ^ st1[63:32];
            go(S_KY);
          end
          S_KY: begin                                         // w[i + 1] = w[i - 7] ^ w[i]
            st0[127:96] <= st0[127:96] ^ st0[95:64]; st1[127:96] <= st1[127:96] ^ st1[95:64];
            go(S_KW);
          end
          S_KW: begin                                         // (lane kl written)
            st0[31:0] <= st0[127:96]; st1[31:0] <= st1[127:96];
            if (kl == 5'd29) done;
            else begin kl <= kl + 5'd1; go(S_KR); end
          end
          // ======== H, E(K, J0), CTR blocks ========
          S_BL0: begin
            if (op == AO_H) begin
              st0 <= 128'd0; st1 <= 128'd0; setrd(4'd0); ret <= S_OH; go(S_ARK0);
            end else if ((op == AO_CTR) && (blk == nblk)) begin
              if (nblk == 7'd64) done;
              else begin zl <= {nblk[5:0], 1'b0}; go(S_CZ); end
            end else go(S_BL1);
          end
          S_BL1: begin st0[63:0] <= brdata; go(S_BL2); end
          S_BL2: begin                                        // IV || ctr (big-endian)
            st0[127:64] <= {ctr[7:0], ctr[15:8], ctr[23:16], ctr[31:24], brdata[31:0]};
            st1 <= 128'd0; setrd(4'd0);
            ret <= (op == AO_J0) ? S_OH : S_CK0;
            go(S_ARK0);
          end
          S_OH: begin
            cnt <= cnt + 3'd1;
            if (cnt == ((op == AO_H) ? 3'd3 : 3'd1)) done;
          end
          S_CK0: begin ks0 <= st0[63:0]; ks1 <= st1[63:0]; go(S_CK1); end
          S_CK1: begin ks0 <= st0[127:64]; ks1 <= st1[127:64]; go(S_CK2); end
          S_CK2: begin blk <= blk + 7'd1; go(S_BL0); end
          S_CZ: begin
            zl <= zl + 7'd1;
            if (zl == 7'd127) done;
          end
          // ======== GHASH ========
          S_GI: begin                                         // Y := 0
            cnt <= cnt + 3'd1;
            if (cnt[0]) begin
              gsrc <= 2'd0; blk <= 7'd0; Z0 <= 128'd0; Z1 <= 128'd0; VA <= 128'd0; VB <= 128'd0;
              go(S_GX0);
            end
          end
          S_GX0: begin
            if (gsrc == 2'd3) done;
            else if (blk == gnb) begin gsrc <= gsrc + 2'd1; blk <= 7'd0; end
            else go(S_GX1);
          end
          S_GX1: begin                                        // X = Y ^ data (lane 0)
            st0[63:0] <= srd0 ^ ((gsrc == 2'd2) ? len0 : (brdata & gm0));
            st1[63:0] <= srd1;
            go(S_GX2);
          end
          S_GX2: begin
            st0[127:64] <= srd0 ^ ((gsrc == 2'd2) ? len1 : (brdata & gm1));
            st1[127:64] <= srd1;
            cnt <= 3'd0; go(S_GHA);
          end
          S_GHA, S_GHB: begin                                 // VA := H0 / VB := H1, Z := R, R
            cnt <= cnt + 3'd1;
            if (cnt == 3'd1) begin
              if (s == S_GHA) VA[63:0] <= lg(srd0); else VB[63:0] <= lg(srd1);
            end
            if (cnt == 3'd2) begin
              if (s == S_GHA) VA[127:64] <= lg(srd0); else VB[127:64] <= lg(srd1);
              Z0[63:0] <= rnd; Z1[63:0] <= rnd;
            end
            if (cnt == 3'd4) begin
              Z0[127:64] <= rnd; Z1[127:64] <= rnd;
              gi <= 7'd0; go((s == S_GHA) ? S_GPA : S_GPB);
            end
          end
          S_GPA, S_GPB: begin                                 // 128 clocks: Z_d ^= X_d[i] V
            if (xb0) Z0 <= Z0 ^ V;
            if (xb1) Z1 <= Z1 ^ V;
            if (s == S_GPA) VA <= mulx(VA); else VB <= mulx(VB);
            gi <= gi + 7'd1;
            if (gi == 7'd127) begin cnt <= 3'd0; go((s == S_GPA) ? S_GWA : S_GYB); end
          end
          S_GWA: begin                                        // (X0 H0 ^ R, X1 H0 ^ R written)
            cnt <= cnt + 3'd1;
            if (cnt == 3'd0) begin wz0 <= lg(Z0[63:0]); wz1 <= lg(Z1[63:0]); end
            if (cnt == 3'd1) begin wz0 <= lg(Z0[127:64]); wz1 <= lg(Z1[127:64]); end
            if (cnt == 3'd2) begin Z0 <= 128'd0; Z1 <= 128'd0; VA <= 128'd0; cnt <= 3'd0; go(S_GHB); end
          end
          S_GYB: begin                                        // Z_d ^= pass A's sums
            cnt <= cnt + 3'd1;
            if (cnt == 3'd1) begin Z0[63:0] <= Z0[63:0] ^ lg(srd0); Z1[63:0] <= Z1[63:0] ^ lg(srd1); end
            if (cnt == 3'd2) begin
              Z0[127:64] <= Z0[127:64] ^ lg(srd0); Z1[127:64] <= Z1[127:64] ^ lg(srd1);
              cnt <= 3'd0; go(S_GWB);
            end
          end
          S_GWB: begin                                        // (Y written)
            cnt <= cnt + 3'd1;
            if (cnt == 3'd0) begin wz0 <= lg(Z0[63:0]); wz1 <= lg(Z1[63:0]); end
            if (cnt == 3'd1) begin wz0 <= lg(Z0[127:64]); wz1 <= lg(Z1[127:64]); end
            if (cnt == 3'd2) begin
              Z0 <= 128'd0; Z1 <= 128'd0; VB <= 128'd0; blk <= blk + 7'd1; go(S_GX0);
            end
          end
          // ======== T = E(K, J0) ^ GHASH ========
          S_TG: begin
            cnt <= cnt + 3'd1;
            case (cnt)
              3'd1: begin st0[63:0] <= srd0; st1[63:0] <= srd1; end
              3'd2: begin st0[63:0] <= st0[63:0] ^ srd0; st1[63:0] <= st1[63:0] ^ srd1; end
              3'd3: begin st0[127:64] <= srd0; st1[127:64] <= srd1; end
              3'd4: begin st0[127:64] <= st0[127:64] ^ srd0; st1[127:64] <= st1[127:64] ^ srd1; end
              3'd6: done;
              default: ;
            endcase
          end
          // ======== WIPE ========
          S_WP: begin
            st0 <= 128'd0; st1 <= 128'd0; ks0 <= 64'd0; ks1 <= 64'd0;
            VA <= 128'd0; VB <= 128'd0; Z0 <= 128'd0; Z1 <= 128'd0; wz0 <= 64'd0; wz1 <= 64'd0;
            zl <= zl + 7'd1;
            if (zl == 7'd39) done;
          end
          default: done;
        endcase
      end
    end
  end
endmodule
`endif
`endif
