// pqse_ucode.v - microcode ROM (96-bit words, 10-bit pc), programs listed above the case table
// Case table generated by scripts/pqse_ucode_v15_gen.py; edit the program there.
// ML-KEM-512/768/1024 share the programs: a k-vector is a C_LOOP; pqse_core.v
// resolves slot (L_*), d (D_*), address (AM_*) and HASH (HM_*) codes for k.
// Secrets are first-order masked from creation, unmasked only as public results;
// fresh Fisher-Yates order (pqse_perm.v) before every NTT / INTT / PWM / ADD / CBD etc.
module pqse_ucode (
  input  wire        clk,
  input  wire        en,         // read: q <= ROM[pc], one clock later
  input  wire [9:0]  pc,
  output reg  [95:0] q
);
  `include "pqse_defs.vh"

  // combinational table + output register: mapped to a ROM block (FPGA block
  // RAM) instead of logic
  reg [95:0] ins;
`ifdef PQSE_UCODE_HEX
  // Quartus (quartus/area/pqse_quartus.tcl) builds the table from logic; read an
  // image of it for this build's defines (scripts/pqse_ucode_hex.py) into a ROM
  // block instead
  reg [95:0] rom [0:1023];
  initial $readmemh(`PQSE_UCODE_HEX, rom);
  always @(posedge clk) if (en) q <= rom[pc];
`else
  always @(posedge clk) if (en) q <= ins;
`endif

  // ---- instruction builders --------------------------------------------------------
  function [95:0] u_end(input [7:0] r);
    u_end = {C_END, 84'd0, r};
  endfunction
  function [95:0] u_br(input [3:0] c, input [9:0] t);
    u_br = {C_BR, c, t, 78'd0};
  endfunction
  // loop over i (w = 0) or j (w = 1) up to k (u_loop) or up to n (u_loopn)
  function [95:0] u_loop(input w, input [9:0] t);
    u_loop = {C_LOOP, w, 1'b0, 2'd0, t, 4'd0, 74'd0};
  endfunction
  function [95:0] u_loopn(input w, input [9:0] t, input [3:0] n);
    u_loopn = {C_LOOP, w, 1'b1, 2'd0, t, n, 74'd0};
  endfunction
  function [95:0] u_set(input [3:0] o);
    u_set = {C_SET, o, 88'd0};
  endfunction
  function [95:0] u_poly(input [3:0] o, input acc, input [3:0] c, input [3:0] a, input [3:0] b);
    u_poly = {C_POLY, o, acc, c, a, b, 1'b1, 74'd0};
  endfunction
  // [58]: slot bit 4 (pqse_core.v), [57:55]: buffer address mode
  function [95:0] u_io(input [3:0] o, input [1:0] dm, input [3:0] d, input cmp, input mchk,
                       input [8:0] ba, input [3:0] sl, input [3:0] e, input [3:0] e2,
                       input [2:0] am);
    u_io = {C_IO, o, dm, d, cmp, mchk, ba, sl, e, e2, 1'b0, am, 55'd0};
  endfunction
  // [56:55]: slot bits 4 (pqse_core.v), [54:52]: buffer address mode, [51]: CBD
  // with eta1 (eta 3 when k = 2), [50]: eta 3 (pqse_core.v)
  function [95:0] u_mask(input [3:0] o, input [3:0] d, input [3:0] sh0, input [3:0] sh1, input ng,
                         input [8:0] ba, input [3:0] e, input [3:0] e2, input acc,
                         input [2:0] am, input e1);
    u_mask = {C_MASK, o, d, sh0, sh1, ng, ba, e, e2, acc, 2'b00, am, e1, 51'd0};
  endfunction
  function [95:0] u_puf(input [3:0] o, input [3:0] e, input [8:0] hb);
    u_puf = {C_PUF, o, e, hb, 75'd0};
  endfunction
  // the os2 field [7:4] carries the HASH index mode (HM_*)
  function [95:0] u_hash(input [1:0] rate, input shake, input msk,
                         input [1:0] p1s, input [8:0] p1a, input [7:0] p1n,
                         input [1:0] p2s, input [8:0] p2a, input [7:0] p2n,
                         input [1:0] sfn, input [15:0] sfx, input [2:0] sink,
                         input [3:0] oe0, input [3:0] oe1, input [7:0] onl,
                         input [3:0] os, input [3:0] hm, input acc);
    u_hash = {C_HASH, rate, shake, msk, p1s, 1'b0, p1a, p1n, p2s, p2a, p2n, sfn, sfx,
              sink, oe0, oe1, onl, os, hm, acc, 3'd0};
  endfunction
  // KMAC256 job (pqse_sponge.v): J[2] = 1, J[1:0] = customization string,
  // J[85] = 1: KMACXOF256
  function [95:0] u_kmac(input [95:0] h, input xof, input [1:0] cs);
    u_kmac = {h[95:86], xof, h[84:3], 1'b1, cs};
  endfunction

  // ---- short forms ---------------------------------------------------------------------
  function [8:0] sa(input [3:0] e);            // seed entry as a part address
    sa = {3'd0, e, 2'd0};
  endfunction
  // SHA3-256(64 TRNG bytes) -> entry, masked (seed conditioning)
  function [95:0] h_trng(input [3:0] oe);
    h_trng = u_hash(RATE_136, 1'b0, 1'b1, SRC_TRNG, 9'd0, 8'd8, SRC_NONE, 9'd0, 8'd0,
                    2'd0, 16'd0, SNK_SEED, oe, 4'd0, 8'd4, 4'd0, HM_NONE, 1'b0);
  endfunction
  // H(ek) = SHA3-256 of an ek in the buffer (48 k + 4 lanes) -> entry
  function [95:0] h_hek(input [8:0] ba, input [3:0] oe);
    h_hek = u_hash(RATE_136, 1'b0, 1'b0, SRC_BUF, ba, 8'd0, SRC_NONE, 9'd0, 8'd0,
                   2'd0, 16'd0, SNK_SEED, oe, 4'd0, 8'd4, 4'd0, HM_HEK, 1'b0);
  endfunction
  // G = SHA3-512(e1 || e2) -> oe0 (32 bytes), oe1 (32 bytes), masked
  function [95:0] h_g(input [3:0] e1, input [3:0] e2, input [3:0] oe0, input [3:0] oe1);
    h_g = u_hash(RATE_72, 1'b0, 1'b1, SRC_SEED, sa(e1), 8'd4, SRC_SEED, sa(e2), 8'd4,
                 2'd0, 16'd0, SNK_SEED, oe0, oe1, 8'd8, 4'd0, HM_NONE, 1'b0);
  endfunction
  // (rho, sigma) = G(d || k) -> E_RHO, E_R (SNK_SEED), or XORed into them
  // (SNK_SXOR: the KeyGen check, both 0 if it agrees)
  function [95:0] h_gk(input [2:0] sink);
    h_gk = u_hash(RATE_72, 1'b0, 1'b1, SRC_SEED, sa(E_D), 8'd4, SRC_NONE, 9'd0, 8'd0,
                  2'd1, 16'd0, sink, E_RHO, E_R, 8'd8, 4'd0, HM_GK, 1'b0);
  endfunction
  // PRF_eta(e, nonce) = SHAKE256(e || nonce), 128 bytes (eta 2) or 192 (eta 3),
  // masked -> scratch entries E_CBD..; the mode picks the nonce and eta
  function [95:0] h_prf(input [3:0] e, input [7:0] n, input [3:0] hm);
    h_prf = u_hash(RATE_136, 1'b1, 1'b1, SRC_SEED, sa(e), 8'd4, SRC_NONE, 9'd0, 8'd0,
                   2'd1, {8'd0, n}, SNK_SEED, E_CBD, E_CBD + 4'd1, 8'd16, 4'd0, hm, 1'b0);
  endfunction
  // masked SamplePolyCBD of the PRF output in E_CBD -> slots os (share 0), os2
  // (share 1), random word order; acc: add to the slots; e1: eta1 (3 when k = 2)
  function [95:0] cbd(input [3:0] os, input [3:0] os2, input acc, input e1);
    cbd = u_mask(M_CBD, 4'd0, os, os2, 1'b0, 9'd0, E_CBD, 4'd0, acc, AM_NONE, e1);
  endfunction
  // XOF(rho || b0 || b1) -> SampleNTT into slot os; rho is public (buffer); the
  // mode puts (j, i) or (i, j) into the two bytes
  function [95:0] h_xof(input [8:0] a, input [3:0] hm, input [3:0] os);
    h_xof = u_hash(RATE_168, 1'b1, 1'b0, SRC_BUF, a, 8'd4, SRC_NONE, 9'd0, 8'd0,
                   2'd2, 16'd0, SNK_SNTT, 4'd0, 4'd0, 8'd0, os, hm, 1'b0);
  endfunction
  // KEK = SHA3-256(k_PUF || "K"), masked
  function [95:0] h_kek(input dummy);
    h_kek = u_hash(RATE_136, 1'b0, 1'b1, SRC_SEED, sa(E_PUF), 8'd4, SRC_NONE, 9'd0, 8'd0,
                   2'd1, 16'h004B, SNK_SEED, E_KEK, 4'd0, 8'd4, 4'd0, HM_NONE, 1'b0);
  endfunction
  // PUF key check value = SHA3-256(k_PUF || "C"), first lane only, masked -> entry oe
  function [95:0] h_kchk(input [3:0] e, input [3:0] oe);
    h_kchk = u_hash(RATE_136, 1'b0, 1'b1, SRC_SEED, sa(e), 8'd4, SRC_NONE, 9'd0, 8'd0,
                    2'd1, 16'h0043, SNK_SEED, oe, 4'd0, 8'd1, 4'd0, HM_NONE, 1'b0);
  endfunction
  // blob tag = SHA3-256(KEK || nonce || ct), masked; sink SEED (wrap) or MCMP (unwrap)
  function [95:0] h_tag(input [2:0] sink);
    h_tag = u_hash(RATE_136, 1'b0, 1'b1, SRC_SEED, sa(E_KEK), 8'd4, SRC_BUF, B_BLOB, 8'd10,
                   2'd0, 16'd0, sink, E_TAG, 4'd0, 8'd4, 4'd0, HM_NONE, 1'b0);
  endfunction
  // LMS blob tag = SHA3-256(KEK || nonce || ct || "L" || H), masked (PQSE_LMS):
  // an ML-KEM blob does not pass as an LMS blob, nor one of another H
  localparam [7:0] LMSH8 = LMS_H;
  function [95:0] h_ltag(input [2:0] sink);
    h_ltag = u_hash(RATE_136, 1'b0, 1'b1, SRC_SEED, sa(E_KEK), 8'd4, SRC_BUF, B_BLOB, 8'd10,
                    2'd2, {LMSH8, 8'h4C}, sink, E_TAG, 4'd0, 8'd4, 4'd0, HM_NONE, 1'b0);
  endfunction
  // LMS: one operation of the engine (pqse_lms.v)
  function [95:0] u_lms(input [3:0] o);
    u_lms = {C_LMS, o, 88'd0};
  endfunction
  // ... with ins[87] = b (LO_LVL: the bottom tree; LO_MSG: the HSS message, PQSE_LMS_HSS)
  function [95:0] u_lmsb(input [3:0] o, input b);
    u_lmsb = {C_LMS, o, b, 87'd0};
  endfunction

  // ---- ML-DSA (PQSE_DSA; pqse_dsa.v) ----------------------------------------------------
  // a branch on a 5-bit condition (BC_DSA ..): bit 4 in ins[77]
  function [95:0] u_br5(input [4:0] c, input [9:0] t);
    u_br5 = {C_BR, c[3:0], t, c[4], 77'd0};
  endfunction
  // polynomial fields {mode, base}: polynomial base, base + i, base + j
  function [5:0] dp(input [3:0] n);
    dp = {DI_0, n};
  endfunction
  function [5:0] dpi(input [3:0] n);
    dpi = {DI_I, n};
  endfunction
  function [5:0] dpj(input [3:0] n);
    dpj = {DI_J, n};
  endfunction
  // one engine operation (pqse_defs.vh: C_DSA); shuf: in the random order (hiding on);
  // lane ba bit 9 (the 8 KB buffer) in ins[52]
  function [95:0] u_dsa(input [3:0] o, input acc, input [5:0] c, input [5:0] a, input [5:0] b,
                        input [9:0] ba, input [2:0] lm, input [2:0] md, input shuf);
    u_dsa = {C_DSA, o, acc, c, a, b, ba[8:0], lm, md, shuf, ba[9], 52'd0};
  endfunction
  function [95:0] d_ntt(input [5:0] c);
    d_ntt = u_dsa(D_NTT, 1'b0, c, 6'd0, 6'd0, 10'd0, LM_0, 3'd0, 1'b1);
  endfunction
  function [95:0] d_intt(input [5:0] c);
    d_intt = u_dsa(D_INTT, 1'b0, c, 6'd0, 6'd0, 10'd0, LM_0, 3'd0, 1'b1);
  endfunction
  function [95:0] d_pwm(input acc, input [5:0] c, input [5:0] a, input [5:0] b);
    d_pwm = u_dsa(D_PWM, acc, c, a, b, 10'd0, LM_0, 3'd0, 1'b1);
  endfunction
  function [95:0] d_add(input [5:0] c, input [5:0] a);
    d_add = u_dsa(D_ADD, 1'b0, c, a, 6'd0, 10'd0, LM_0, 3'd0, 1'b1);
  endfunction
  function [95:0] d_sub(input [5:0] c, input [5:0] a);
    d_sub = u_dsa(D_SUB, 1'b0, c, a, 6'd0, 10'd0, LM_0, 3'd0, 1'b1);
  endfunction
  function [95:0] d_zero(input [5:0] c);
    d_zero = u_dsa(D_ZERO, 1'b0, c, 6'd0, 6'd0, 10'd0, LM_0, 3'd0, 1'b0);
  endfunction
  // Power2Round: t1 = 0: c := t0 mod q, 1: c := t1 2^13
  function [95:0] d_p2r(input [5:0] c, input t1);
    d_p2r = u_dsa(D_P2R, 1'b0, c, 6'd0, 6'd0, 10'd0, LM_0, {2'b00, t1}, 1'b0);
  endfunction
  // pack c (mode DM_*) into lanes from ba (+ lane mode)
  function [95:0] d_enc(input [2:0] md, input [5:0] c, input [9:0] ba, input [2:0] lm);
    d_enc = u_dsa(D_ENC, 1'b0, c, 6'd0, 6'd0, ba, lm, md, 1'b0);
  endfunction
  // BAD if |z| >= gamma1 - beta for a coefficient of c; nothing written (signing attempts)
  function [95:0] d_zchk(input [5:0] c);
    d_zchk = u_dsa(D_ENC, 1'b1, c, 6'd0, 6'd0, 10'd0, LM_0, DM_Z, 1'b0);
  endfunction
  // unpack lanes from ba (+ lane mode) into c (mode DM_*)
  function [95:0] d_dec(input [2:0] md, input [9:0] ba, input [2:0] lm, input [5:0] c);
    d_dec = u_dsa(D_DEC, 1'b0, c, 6'd0, 6'd0, ba, lm, md, 1'b0);
  endfunction
  // signing, polynomial i: c = w - c s2, a = c t0 (checks, hints into the stream)
  function [95:0] d_hint(input [5:0] c, input [5:0] a);
    d_hint = u_dsa(D_HINT, 1'b0, c, a, 6'd0, 10'd0, LM_0, 3'd0, 1'b0);
  endfunction
  // signing: the hint byte stream starts at lane ba
  function [95:0] d_hcnt(input [8:0] ba);
    d_hcnt = u_dsa(D_HCNT, 1'b1, 6'd0, 6'd0, 6'd0, {1'b0, ba}, LM_0, 3'd0, 1'b0);
  endfunction
  // verification: HDEC (polynomial b's hints into c; b = 0 starts the count) and HVEND seek
  // into the signature's hint part at lane ba
  function [95:0] d_hdec(input [5:0] c, input [5:0] b, input [9:0] ba);
    d_hdec = u_dsa(D_HDEC, 1'b0, c, 6'd0, b, ba, LM_0, 3'd0, 1'b0);
  endfunction
  function [95:0] d_hend(input dummy);
    d_hend = u_dsa(D_HEND, 1'b0, 6'd0, 6'd0, 6'd0, 10'd0, LM_0, 3'd0, 1'b0);
  endfunction
  function [95:0] d_hvend(input [9:0] ba);
    d_hvend = u_dsa(D_HVEND, 1'b0, 6'd0, 6'd0, 6'd0, ba, LM_0, 3'd0, 1'b0);
  endfunction
  // verification: c := t1 2^13 of row b of the loaded key (packed from polynomial a on)
  function [95:0] d_t1x(input [5:0] c, input [5:0] a, input [5:0] b);
    d_t1x = u_dsa(D_T1X, 1'b0, c, a, b, 10'd0, LM_0, 3'd0, 1'b0);
  endfunction
  // a HASH job reading buffer lanes 512..: part 1 / part 2 address bit 9 in J[1] / J[0]
  // (pqse_sponge.v; not for KMAC jobs)
  function [95:0] h_hi(input [95:0] h, input p1, input p2);
    h_hi = {h[95:2], p1, p2};
  endfunction
  // (rho, rho', K) = H(xi || k || l, 128 bytes), masked -> E_DRHO (lanes 0..3), E_DRHOP
  // (4..11: entries 4, 5), E_DK (12..15)
  function [95:0] h_dexp(input [3:0] e);
    h_dexp = u_hash(RATE_136, 1'b1, 1'b1, SRC_SEED, sa(e), 8'd4, SRC_NONE, 9'd0, 8'd0,
                    2'd2, 16'h0404, SNK_SEED, E_DRHO, E_DRHOP, 8'd16, 4'd0, HM_NONE, 1'b0);
  endfunction
  // ExpandS: RejBoundedPoly(rho' || u16(n + i)) -> polynomial {pm, pb}, masked job
  function [95:0] h_dexps(input [7:0] n, input [1:0] pm, input [3:0] pb);
    h_dexps = u_hash(RATE_136, 1'b1, 1'b1, SRC_SEED, sa(E_DRHOP), 8'd8, SRC_NONE, 9'd0, 8'd0,
                     2'd2, {8'd0, n}, SNK_DSA, {1'b0, SM_S}, {2'd0, pm}, 8'd0, pb, HM_PI1, 1'b0);
  endfunction
  // ExpandMask: y_i from H(rho'' || u16(kappa + i), 576 bytes) -> P0+i, masked job
  function [95:0] h_dmask(input dummy);
    h_dmask = u_hash(RATE_136, 1'b1, 1'b1, SRC_SEED, sa(E_DRHO2), 8'd8, SRC_NONE, 9'd0, 8'd0,
                     2'd2, 16'd0, SNK_DSA, {1'b0, SM_Y}, {2'd0, DI_I}, 8'd0, 4'd0, HM_KAP, 1'b0);
  endfunction
  // ExpandA: A^[i][j] = RejNTTPoly(G(rho || j || i)) -> polynomial os; rho is public
  // (B_DRHOS signing, B_DRHO verification)
  function [95:0] h_dxof(input [9:0] ba, input [3:0] os);
    h_dxof = h_hi(u_hash(RATE_168, 1'b1, 1'b0, SRC_BUF, ba[8:0], 8'd4, SRC_NONE, 9'd0, 8'd0,
                         2'd2, 16'd0, SNK_DSA, {1'b0, SM_A}, {2'd0, DI_0}, 8'd0, os, HM_XOF, 1'b0),
                  ba[9], 1'b0);
  endfunction
  // c~ = H(mu || w1Encode(w1), lambda / 4 bytes: n lanes) -> E_DCT (, E_DCT2), public data:
  // unmasked job; w1 nw lanes
  function [95:0] h_dch(input [7:0] nw, input [7:0] n);
    h_dch = h_hi(u_hash(RATE_136, 1'b1, 1'b0, SRC_BUF, B_DMU[8:0], 8'd8, SRC_BUF, B_DW1[8:0], nw,
                        2'd0, 16'd0, SNK_SEED, E_DCT, E_DCT2, n, 4'd0, HM_NONE, 1'b0),
                 1'b1, 1'b1);
  endfunction
  // rho'' = H(K || rnd || mu, 64 bytes), masked -> E_DRHO2 (2 entries)
  function [95:0] h_drho2(input dummy);
    h_drho2 = h_hi(u_hash(RATE_136, 1'b1, 1'b1, SRC_SEED, sa(E_DK), 8'd8, SRC_BUF, B_DMU[8:0], 8'd8,
                          2'd0, 16'd0, SNK_SEED, E_DRHO2, E_DRHO2 + 4'd1, 8'd8, 4'd0, HM_NONE, 1'b0),
                   1'b0, 1'b1);
  endfunction
  // c = SampleInBall(c~) -> polynomial os (zeroed first): c~ from E_DCT (signing; a seed
  // source needs a masked job) or from the signature in the buffer (verification, n lanes)
  function [95:0] h_dball(input [1:0] src, input [7:0] n, input [3:0] os);
    h_dball = u_hash(RATE_136, 1'b1, (src == SRC_SEED), src,
                     (src == SRC_SEED) ? sa(E_DCT) : B_DSIG, n, SRC_NONE, 9'd0, 8'd0,
                     2'd0, 16'd0, SNK_DSA, {1'b0, SM_C}, {2'd0, DI_0}, 8'd0, os, HM_NONE, 1'b0);
  endfunction
  // ML-DSA blob tag = SHA3-256(KEK || nonce || ct || "D" || 44), masked: an ML-KEM or
  // LMS blob does not pass as an ML-DSA blob, nor the other way round
  function [95:0] h_dtag(input [2:0] sink);
    h_dtag = u_hash(RATE_136, 1'b0, 1'b1, SRC_SEED, sa(E_KEK), 8'd4, SRC_BUF, B_BLOB, 8'd10,
                    2'd2, 16'h2C44, sink, E_TAG, 4'd0, 8'd4, 4'd0, HM_NONE, 1'b0);
  endfunction
  // blob keystream = SHAKE256(KEK || nonce, 64 bytes), masked, XORed into oe0 | oe1
  function [95:0] h_ks(input [3:0] oe0, input [3:0] oe1);
    h_ks = u_hash(RATE_136, 1'b1, 1'b1, SRC_SEED, sa(E_KEK), 8'd4, SRC_BUF, B_BLOB_NONCE, 8'd2,
                  2'd0, 16'd0, SNK_SXOR, oe0, oe1, 8'd8, 4'd0, HM_NONE, 1'b0);
  endfunction
  // message keystream = KMACXOF256(SK, H, 1024 bits, "E1" / "E2"), masked; the
  // sink XORs it into the 16 message lanes
  function [95:0] h_kks(input [1:0] cs);
    h_kks = u_kmac(u_hash(RATE_136, 1'b1, 1'b1, SRC_SEED, sa(E_SK), 8'd4, SRC_BUF, B_SM_HDR, 8'd4,
                          2'd0, 16'd0, SNK_BXOR, 4'd0, 4'd0, 8'd16, 4'd0, HM_NONE, 1'b0),
                   1'b1, cs);
  endfunction
  // message tag = KMAC256(SK, H || C, 256, "T1" / "T2"), masked; sink SEED (SEAL,
  // -> E_TAG) or MCMP (OPEN: compared with the received tag, acc = 1)
  function [95:0] h_ktag(input [2:0] sink, input [1:0] cs);
    h_ktag = u_kmac(u_hash(RATE_136, 1'b0, 1'b1, SRC_SEED, sa(E_SK), 8'd4, SRC_BUF, B_SM, 8'd20,
                           2'd0, 16'd0, sink, E_TAG, 4'd0, 8'd4, 4'd0, HM_NONE,
                           (sink == SNK_MCMP)),
                    1'b0, cs);
  endfunction
  // record store (PQSE_STORE): the secure-message jobs with the KEK as the key.
  // Record keystream = KMACXOF256(KEK, header, 1024 bits, "E1"), XORed into the 16
  // data lanes; record tag = KMAC256(KEK, header || data, 256, "T1"), sink SEED
  // (STWRITE, -> E_TAG) or MCMP (STREAD: compared with the stored tag)
  function [95:0] h_rks(input dummy);
    h_rks = u_kmac(u_hash(RATE_136, 1'b1, 1'b1, SRC_SEED, sa(E_KEK), 8'd4, SRC_BUF, B_SM_HDR, 8'd4,
                          2'd0, 16'd0, SNK_BXOR, 4'd0, 4'd0, 8'd16, 4'd0, HM_NONE, 1'b0),
                   1'b1, KC_E1);
  endfunction
  function [95:0] h_rtag(input [2:0] sink);
    h_rtag = u_kmac(u_hash(RATE_136, 1'b0, 1'b1, SRC_SEED, sa(E_KEK), 8'd4, SRC_BUF, B_SM, 8'd20,
                           2'd0, 16'd0, sink, E_TAG, 4'd0, 8'd4, 4'd0, HM_NONE,
                           (sink == SNK_MCMP)),
                    1'b0, KC_T1);
  endfunction
  // AES-256-GCM (PQSE_AES): one operation of the engine (pqse_aes.v)
  function [95:0] u_aes(input [3:0] o);
    u_aes = {C_AES, o, 88'd0};
  endfunction
  // the GCM key from the session key: SHA3-256(SK || "A") -> E_W0, masked
  function [95:0] h_ak(input dummy);
    h_ak = u_hash(RATE_136, 1'b0, 1'b1, SRC_SEED, sa(E_SK), 8'd4, SRC_NONE, 9'd0, 8'd0,
                  2'd1, 16'h0041, SNK_SEED, E_W0, 4'd0, 8'd4, 4'd0, HM_NONE, 1'b0);
  endfunction
  // key from a seed entry: SHA3-256(entry || suffix (sfn bytes)) -> E_W0, masked. PQSE_AES:
  // SEAL / OPEN keys SHA3-256(SK || "S1") (initiator -> responder) / "S2" (reverse), record
  // store SHA3-256(KEK || "R"); each key has its own IV space (h_ak's "A": host GCM)
  function [95:0] h_kd(input [3:0] e, input [1:0] sfn, input [15:0] sfx);
    h_kd = u_hash(RATE_136, 1'b0, 1'b1, SRC_SEED, sa(e), 8'd4, SRC_NONE, 9'd0, 8'd0,
                  sfn, sfx, SNK_SEED, E_W0, 4'd0, 8'd4, 4'd0, HM_NONE, 1'b0);
  endfunction
  // AES key blob tag = SHA3-256(KEK || nonce || ct || "A" || 32), masked: an ML-KEM, LMS or
  // ML-DSA blob does not pass as an AES blob, nor the other way round
  function [95:0] h_atag(input [2:0] sink);
    h_atag = u_hash(RATE_136, 1'b0, 1'b1, SRC_SEED, sa(E_KEK), 8'd4, SRC_BUF, B_BLOB, 8'd10,
                    2'd2, 16'h2041, sink, E_TAG, 4'd0, 8'd4, 4'd0, HM_NONE, 1'b0);
  endfunction
  // GCMDEC's tag check: SHA3-256 of the received tag (public, 2 lanes) -> E_TAG, and
  // SHA3-256 of the computed one (masked, E_W0 lanes 0, 1) compared with it (B_SM_TAG)
  function [95:0] h_gtr(input dummy);
    h_gtr = u_hash(RATE_136, 1'b0, 1'b0, SRC_BUF, B_GTAG, 8'd2, SRC_NONE, 9'd0, 8'd0,
                   2'd0, 16'd0, SNK_SEED, E_TAG, 4'd0, 8'd4, 4'd0, HM_NONE, 1'b0);
  endfunction
  function [95:0] h_gtc(input dummy);
    h_gtc = u_hash(RATE_136, 1'b0, 1'b1, SRC_SEED, sa(E_W0), 8'd2, SRC_NONE, 9'd0, 8'd0,
                   2'd0, 16'd0, SNK_MCMP, E_TAG, 4'd0, 8'd4, 4'd0, HM_NONE, 1'b1);
  endfunction
  // record store: one operation of the engine (pqse_store.v); flag: SO_HDR's deleted bit
  function [95:0] u_st(input [3:0] o, input flag);
    u_st = {C_ST, o, flag, 87'd0};
  endfunction
  // K-bar = J(z || c) = SHAKE256(z || c, 32), masked; c is DU k + DV lanes
  function [95:0] h_j(input dummy);
    h_j = u_hash(RATE_136, 1'b1, 1'b1, SRC_SEED, sa(E_Z), 8'd4, SRC_BUF, B_XIN, 8'd0,
                 2'd0, 16'd0, SNK_SEED, E_KB, 4'd0, 8'd4, 4'd0, HM_JC, 1'b0);
  endfunction

  function [95:0] pwm(input acc, input [3:0] c, input [3:0] a, input [3:0] b);
    pwm = u_poly(P_PWM, acc, c, a, b);
  endfunction
  function [95:0] ntt(input [3:0] c);
    ntt = u_poly(P_NTT, 1'b0, c, 4'd0, 4'd0);
  endfunction
  function [95:0] intt(input [3:0] c);
    intt = u_poly(P_INTT, 1'b0, c, 4'd0, 4'd0);
  endfunction
  function [95:0] pzero(input [3:0] c);
    pzero = u_poly(P_ZERO, 1'b0, c, 4'd0, 4'd0);
  endfunction
  function [95:0] padd(input [3:0] c, input [3:0] a);
    padd = u_poly(P_ADD, 1'b0, c, a, 4'd0);
  endfunction
  function [95:0] psub(input [3:0] c, input [3:0] a);
    psub = u_poly(P_SUB, 1'b0, c, a, 4'd0);
  endfunction
  // FAULT unless c + a = 0 mod q everywhere (pqse_poly ZCHK); not shuffled
  function [95:0] pzchk(input [3:0] c, input [3:0] a);
    pzchk = {C_POLY, P_ZCHK, 1'b0, c, a, 4'd0, 1'b0, 74'd0};
  endfunction
  function [95:0] msplit(input [3:0] c, input [3:0] a);
    msplit = u_poly(P_MSPLIT, 1'b0, c, a, 4'd0);
  endfunction
  // decode d bits (d = 12, D_DU or D_DV) from buffer lane ba (+ mode) into slot sl
  function [95:0] dec(input [1:0] dm, input [3:0] d, input mchk, input [8:0] ba, input [3:0] sl,
                      input [2:0] am);
    dec = u_io(IO_DEC, dm, d, (d != 4'd12), mchk, ba, sl, 4'd0, 4'd0, am);
  endfunction
  function [95:0] enc12(input [3:0] sl, input [8:0] ba, input [2:0] am);
    enc12 = u_io(IO_ENC, DM_WR, 4'd12, 1'b0, 1'b0, ba, sl, 4'd0, 4'd0, am);
  endfunction
  function [95:0] s2b(input [3:0] e, input [8:0] ba, input [2:0] am);          // 4 lanes
    s2b = u_io(IO_S2B, DM_WR, 4'd0, 1'b0, 1'b0, ba, 4'd0, e, 4'd0, am);
  endfunction
  function [95:0] s2bn(input [3:0] e, input [8:0] ba, input [3:0] n);          // lanes 0..n-1
    s2bn = u_io(IO_S2B, DM_WR, n, 1'b0, 1'b0, ba, 4'd0, e, 4'd0, AM_NONE);
  endfunction
  function [95:0] b2s(input [8:0] ba, input [3:0] e, input [2:0] am);
    b2s = u_io(IO_B2S, DM_WR, 4'd0, 1'b0, 1'b0, ba, 4'd0, e, 4'd0, am);
  endfunction
  function [95:0] s2s(input [3:0] e, input [3:0] e2);
    s2s = u_io(IO_S2S, DM_WR, 4'd0, 1'b0, 1'b0, 9'd0, 4'd0, e, e2, AM_NONE);
  endfunction
  function [95:0] szero(input [3:0] e);
    szero = u_io(IO_SZERO, DM_WR, 4'd0, 1'b0, 1'b0, 9'd0, 4'd0, e, 4'd0, AM_NONE);
  endfunction
  function [95:0] sremask(input [3:0] e);
    sremask = u_io(IO_SREMASK, DM_WR, 4'd0, 1'b0, 1'b0, 9'd0, 4'd0, e, 4'd0, AM_NONE);
  endfunction
  function [95:0] scmpn(input [3:0] e, input [8:0] ba, input [3:0] n, input [2:0] am); // n = 0: 4 lanes
    scmpn = u_io(IO_SCMP, DM_WR, n, 1'b0, 1'b0, ba, 4'd0, e, 4'd0, am);
  endfunction
  function [95:0] seq(input [3:0] e, input [3:0] e2);         // FAULT if e != e2 (masked)
    seq = u_io(IO_SEQ, DM_WR, 4'd0, 1'b0, 1'b0, 9'd0, 4'd0, e, e2, AM_NONE);
  endfunction
  function [95:0] trunc(input chk);                            // chk: length check only
    trunc = u_io(IO_TRUNC, DM_WR, 4'd0, chk, 1'b0, B_SM_MSG, 4'd0, 4'd0, 4'd0, AM_NONE);
  endfunction
  function [95:0] ctr(input [3:0] o);                          // IO_CTRW / IO_CTRC
    ctr = u_io(o, DM_WR, 4'd0, 1'b0, 1'b0, B_SM_HDR, 4'd0, 4'd0, 4'd0, AM_NONE);
  endfunction
  // PQSE_AES: the counter in the GCM IV (lane 0; CTRW zeroes the two tag lanes after it)
  function [95:0] ctrg(input [3:0] o);
    ctrg = u_io(o, DM_WR, 4'd0, 1'b0, 1'b0, B_GIV, 4'd0, 4'd0, 4'd0, AM_NONE);
  endfunction
  function [95:0] m_op(input [3:0] o);          // OKINI / OKOUT / OKCHK
    m_op = u_mask(o, 4'd0, 4'd0, 4'd0, 1'b0, 9'd0, 4'd0, 4'd0, 1'b0, AM_NONE, 1'b0);
  endfunction
  function [95:0] cmprc(input [3:0] d, input [8:0] ba, input [2:0] am);   // compare with the ciphertext
    cmprc = u_mask(M_CMPRC, d, L_ACC0, L_ACC1, 1'b0, ba, 4'd0, 4'd0, 1'b0, am, 1'b0);
  endfunction
  function [95:0] cmpro(input [3:0] d, input [8:0] ba, input [2:0] am);   // write the ciphertext
    cmpro = u_mask(M_CMPRO, d, L_ACC0, L_ACC1, 1'b0, ba, 4'd0, 4'd0, 1'b0, am, 1'b0);
  endfunction
  function [95:0] cmpr1(input [3:0] e);                   // m' = Compress_1(w) -> entry e
    cmpr1 = u_mask(M_CMPR1, 4'd1, L_ACC0, L_ACC1, 1'b1, 9'd0, e, 4'd0, 1'b0, AM_NONE, 1'b0);
  endfunction
  function [95:0] mu(input [3:0] e);                      // + Decompress_1(m)
    mu = u_mask(M_MU, 4'd0, L_ACC0, L_ACC1, 1'b0, 9'd0, e, 4'd0, 1'b1, AM_NONE, 1'b0);
  endfunction

  // entry points: see EP_* in pqse_defs.vh
  always @* begin
    case (pc)
      // ---- generated by scripts/pqse_ucode_v15_gen.py: begin ----
      10'd0:    ins = u_end(R_BADIN);
      10'd1:    ins = u_end(R_NOKEY);
      10'd2:    ins = u_end(R_BADBLOB);
      10'd3:    ins = u_end(R_DENIED);
      10'd4:    ins = u_end(R_BADTAG);
      10'd5:    ins = u_end(R_NOSK);
      10'd6:    ins = u_end(R_REPLAY);
      10'd7:    ins = u_end(R_PUF);
      10'd8:    ins = u_end(R_FAULT);                                                // X_KGF: a KeyGen recompute check failed
      10'd16:   ins = u_set(ST_RESEED);
      10'd17:   ins = u_br(BC_WRAP, 10'd48);                                         // KGWRAP: KEK first (no key yet if it fails)
      10'd18:   ins = u_br(BC_INJ, 10'd22);
      10'd19:   ins = h_trng(E_D);
      10'd20:   ins = h_trng(E_Z);
      10'd21:   ins = u_br(BC_ALWAYS, 10'd80);
      10'd22:   ins = b2s(B_INJD, E_D, AM_NONE);                                     // TEST: injected d, z
      10'd23:   ins = sremask(E_D);
      10'd24:   ins = b2s(B_INJZ, E_Z, AM_NONE);
      10'd25:   ins = sremask(E_Z);
      10'd26:   ins = u_br(BC_ALWAYS, 10'd80);
      10'd32:   ins = u_set(ST_RESEED);
      10'd33:   ins = u_br(BC_ALWAYS, 10'd48);                                       // PUF key -> KEK, back to L_UWK
      10'd34:   ins = m_op(M_OKINI);
      10'd35:   ins = h_tag(SNK_MCMP);                                               // masked tag check
      10'd36:   ins = m_op(M_OKCHK);                                                 // the two ok copies must agree
      10'd37:   ins = m_op(M_OKOUT);
      10'd38:   ins = u_br(BC_BAD, 10'd44);
      10'd39:   ins = b2s(B_BLOB_CT, E_D, AM_NONE);
      10'd40:   ins = b2s(B_BLOB_CT + 9'd4, E_Z, AM_NONE);
      10'd41:   ins = h_ks(E_D, E_Z);                                                // d, z now masked plaintext
      10'd42:   ins = szero(E_KEK);
      10'd43:   ins = u_br(BC_ALWAYS, 10'd80);
      10'd44:   ins = szero(E_KEK);
      10'd45:   ins = u_br(BC_ALWAYS, 10'd2);
      10'd48:   ins = u_puf(PF_RECON, E_PUF, B_HELP);                                // one read per bit
      10'd49:   ins = h_kchk(E_PUF, E_TMP);
      10'd50:   ins = scmpn(E_TMP, B_HELP_CHK, 4'd1, AM_NONE);                       // 64-bit check value
      10'd51:   ins = u_br(BC_NBAD, 10'd72);
      10'd52:   ins = u_set(ST_BADC);
      10'd53:   ins = u_puf(PF_RECON3, E_PUF, B_HELP);                               // retry: majority of 3 reads
      10'd54:   ins = h_kchk(E_PUF, E_TMP);
      10'd55:   ins = scmpn(E_TMP, B_HELP_CHK, 4'd1, AM_NONE);
      10'd56:   ins = u_br(BC_NBAD, 10'd72);
      10'd57:   ins = u_set(ST_BADC);
      10'd58:   ins = u_puf(PF_RECON5, E_PUF, B_HELP);                               // retry: majority of 5 reads
      10'd59:   ins = h_kchk(E_PUF, E_TMP);
      10'd60:   ins = scmpn(E_TMP, B_HELP_CHK, 4'd1, AM_NONE);
      10'd61:   ins = u_br(BC_NBAD, 10'd72);
      10'd62:   ins = u_set(ST_BADC);
      10'd63:   ins = u_puf(PF_RECON5, E_PUF, B_HELP);                               // retry: majority of 5 reads (again)
      10'd64:   ins = h_kchk(E_PUF, E_TMP);
      10'd65:   ins = scmpn(E_TMP, B_HELP_CHK, 4'd1, AM_NONE);
      10'd66:   ins = u_br(BC_NBAD, 10'd72);
      10'd67:   ins = u_set(ST_BADC);
      10'd68:   ins = u_puf(PF_RECON5, E_PUF, B_HELP);                               // retry: majority of 5 reads (again)
      10'd69:   ins = h_kchk(E_PUF, E_TMP);
      10'd70:   ins = scmpn(E_TMP, B_HELP_CHK, 4'd1, AM_NONE);
      10'd71:   ins = u_br(BC_BAD, 10'd77);
      10'd72:   ins = szero(E_TMP);
      10'd73:   ins = h_kek(1'b0);
      10'd74:   ins = szero(E_PUF);
      10'd75:   ins = u_br(BC_WRAP, 10'd18);                                         // KGWRAP: on to KeyGen
`ifdef PQSE_LMS
      10'd76:   ins = u_br(BC_ALWAYS, 10'd501);                                      // UNWRAP / LMS / ML-DSA / store / AES: on to L_PRET
`elsif PQSE_DSA
      10'd76:   ins = u_br(BC_ALWAYS, 10'd501);                                      // UNWRAP / LMS / ML-DSA / store / AES: on to L_PRET
`elsif PQSE_STORE
      10'd76:   ins = u_br(BC_ALWAYS, 10'd501);                                      // UNWRAP / LMS / ML-DSA / store / AES: on to L_PRET
`elsif PQSE_AES
      10'd76:   ins = u_br(BC_ALWAYS, 10'd501);                                      // UNWRAP / LMS / ML-DSA / store / AES: on to L_PRET
`else
      10'd76:   ins = u_br(BC_ALWAYS, 10'd34);
`endif
      10'd77:   ins = szero(E_PUF);
      10'd78:   ins = szero(E_TMP);
      10'd79:   ins = u_br(BC_ALWAYS, 10'd7);
      10'd80:   ins = h_gk(SNK_SEED);                                                // (rho, sigma) = G(d || k) -> E_RHO, E_R
      10'd81:   ins = s2b(E_RHO, B_EKOWN, AM_48K);                                   // rho is public: after t^ in the own ek
      10'd82:   ins = s2b(E_RHO, B_TMP, AM_NONE);                                    // ... and where the XOF reads it
      10'd83:   ins = szero(E_KB);                                                   // all-zero reference entry (G check)
      10'd84:   ins = scmpn(E_RHO, B_EKOWN, 4'd0, AM_48K);                           // rho in the buffer = rho of G (public)
      10'd85:   ins = u_br(BC_BAD, 10'd8);
      10'd86:   ins = h_prf(E_R, 8'd0, HM_PI1);                                      // s_i: PRF(sigma, i), eta1
      10'd87:   ins = cbd(L_SI0, L_SI1, 1'b0, 1'b1);                                 // copy 1 (shares)
      10'd88:   ins = h_prf(E_R, 8'd0, HM_PI1);                                      // the PRF again
      10'd89:   ins = cbd(L_ACC0, L_ACC1, 1'b0, 1'b1);                               // copy 2: fresh masks, own order
      10'd90:   ins = ntt(L_SI0);
      10'd91:   ins = ntt(L_SI1);
      10'd92:   ins = ntt(L_ACC0);
      10'd93:   ins = ntt(L_ACC1);
      10'd94:   ins = psub(L_ACC0, L_SI0);                                           // share 0: y0 - x0
      10'd95:   ins = psub(L_ACC1, L_SI1);                                           // share 1: y1 - x1
      10'd96:   ins = pzchk(L_ACC0, L_ACC1);                                         // sum 0 everywhere, else FAULT
      10'd97:   ins = u_loop(1'b0, 10'd86);                                          // next i < k
      10'd98:   ins = h_prf(E_R, 8'd0, HM_PKI1);                                     // e_i: PRF(sigma, k + i), eta1
      10'd99:   ins = cbd(L_YI0, L_YI1, 1'b0, 1'b1);
      10'd100:  ins = h_prf(E_R, 8'd0, HM_PKI1);
      10'd101:  ins = cbd(L_ACC0, L_ACC1, 1'b0, 1'b1);
      10'd102:  ins = ntt(L_YI0);
      10'd103:  ins = ntt(L_YI1);
      10'd104:  ins = ntt(L_ACC0);
      10'd105:  ins = ntt(L_ACC1);
      10'd106:  ins = psub(L_ACC0, L_YI0);
      10'd107:  ins = psub(L_ACC1, L_YI1);
      10'd108:  ins = pzchk(L_ACC0, L_ACC1);
      10'd109:  ins = u_loop(1'b0, 10'd98);
      10'd110:  ins = h_gk(SNK_SXOR);                                                // G(d || k) again, XORed into rho, sigma
      10'd111:  ins = seq(E_RHO, E_KB);
      10'd112:  ins = seq(E_R, E_KB);                                                // (sigma is not needed after the PRFs)
      10'd113:  ins = h_xof(B_TMP, HM_XOF, L_T);                                     // A^[i][j] = SampleNTT(rho || j || i)
      10'd114:  ins = pwm(1'b1, L_YI0, L_T, L_SJ0);
      10'd115:  ins = pwm(1'b1, L_YI1, L_T, L_SJ1);
      10'd116:  ins = u_loop(1'b1, 10'd113);                                         // next j < k
      10'd117:  ins = padd(L_YI0, L_YI1);                                            // t^_i is public: unmask
      10'd118:  ins = enc12(L_YI0, B_EKOWN, AM_48I);
      10'd119:  ins = u_loop(1'b0, 10'd113);                                         // next i < k
      10'd120:  ins = h_hek(B_EKOWN, E_H);                                           // H(ek), 48 k + 4 lanes
      10'd121:  ins = u_br(BC_KGEN, 10'd448);                                        // KEYGEN / KGWRAP: PCT first
      10'd122:  ins = u_set(ST_KEYV);                                                // s^ and z stay masked; key_k := k
      10'd123:  ins = u_br(BC_WRAP, 10'd125);
      10'd124:  ins = u_br(BC_ALWAYS, 10'd137);
      10'd125:  ins = h_trng(E_TMP);
      10'd126:  ins = s2bn(E_TMP, B_BLOB_NONCE, 4'd2);                               // nonce (2 lanes)
      10'd127:  ins = s2s(E_D, E_W0);
      10'd128:  ins = s2s(E_Z, E_W1);
      10'd129:  ins = h_ks(E_W0, E_W1);
      10'd130:  ins = s2b(E_W0, B_BLOB_CT, AM_NONE);                                 // ciphertext is public
      10'd131:  ins = s2b(E_W1, B_BLOB_CT + 9'd4, AM_NONE);
      10'd132:  ins = h_tag(SNK_SEED);
      10'd133:  ins = s2b(E_TAG, B_BLOB_TAG, AM_NONE);
      10'd134:  ins = szero(E_W0);
      10'd135:  ins = szero(E_W1);
      10'd136:  ins = szero(E_KEK);
      10'd137:  ins = szero(E_D);
      10'd138:  ins = szero(E_R);
      10'd139:  ins = szero(E_RHO);
      10'd140:  ins = szero(E_CBD + 4'd0);                                           // PRF scratch (E_PUF, E_TMP, E_PH, E_W0, E_W1, E_TAG)
      10'd141:  ins = szero(E_CBD + 4'd1);
      10'd142:  ins = szero(E_CBD + 4'd2);
      10'd143:  ins = szero(E_CBD + 4'd3);
      10'd144:  ins = szero(E_CBD + 4'd4);
      10'd145:  ins = szero(E_CBD + 4'd5);
      10'd146:  ins = pzero(L_T);
      10'd147:  ins = pzero(L_ACC0);
      10'd148:  ins = pzero(L_ACC1);
      10'd149:  ins = pzero(L_YI0);
      10'd150:  ins = pzero(L_YI1);
      10'd151:  ins = u_loop(1'b0, 10'd149);
      10'd152:  ins = u_end(R_OK);
      10'd160:  ins = u_set(ST_RESEED);
      10'd161:  ins = pzero(L_Z);                                                    // the all-zero slot (precharge reads)
      10'd162:  ins = dec(DM_CHK, 4'd12, 1'b1, B_XIN, L_T, AM_48I);                  // ek modulus check, t^_i
      10'd163:  ins = u_loop(1'b0, 10'd162);
      10'd164:  ins = u_br(BC_BAD, 10'd0);
      10'd165:  ins = u_br(BC_INJ, 10'd168);
      10'd166:  ins = h_trng(E_M);
      10'd167:  ins = u_br(BC_ALWAYS, 10'd170);
      10'd168:  ins = b2s(B_INJM, E_M, AM_NONE);                                     // TEST: injected m
      10'd169:  ins = sremask(E_M);
      10'd170:  ins = h_hek(B_XIN, E_PH);                                            // H(ek)
      10'd171:  ins = h_g(E_M, E_PH, E_K1, E_R);                                     // (K, r) = G(m || H(ek))
      10'd172:  ins = b2s(B_XIN, E_TMP, AM_48K);                                     // rho of the key in use ...
      10'd173:  ins = s2b(E_TMP, B_TMP, AM_NONE);                                    // ... to where the XOF reads it
      10'd174:  ins = szero(E_TMP);
      10'd175:  ins = h_prf(E_R, 8'd0, HM_PI1);                                      // y_i: PRF(r, i), eta1
      10'd176:  ins = cbd(L_YI0, L_YI1, 1'b0, 1'b1);
      10'd177:  ins = ntt(L_YI0);
      10'd178:  ins = ntt(L_YI1);
      10'd179:  ins = u_loop(1'b0, 10'd175);
      10'd180:  ins = pzero(L_ACC0);
      10'd181:  ins = pzero(L_ACC1);
      10'd182:  ins = dec(DM_WR, 4'd12, 1'b0, B_XIN, L_T, AM_48J);                   // t^_j
      10'd183:  ins = pwm(1'b1, L_ACC0, L_T, L_YJ0);
      10'd184:  ins = pwm(1'b1, L_ACC1, L_T, L_YJ1);
      10'd185:  ins = u_loop(1'b1, 10'd182);
      10'd186:  ins = intt(L_ACC0);
      10'd187:  ins = intt(L_ACC1);
      10'd188:  ins = h_prf(E_R, 8'd0, HM_P2K2);                                     // + e2: PRF(r, 2k), eta2
      10'd189:  ins = cbd(L_ACC0, L_ACC1, 1'b1, 1'b0);
      10'd190:  ins = mu(E_M);                                                       // + mu (masked m)
      10'd191:  ins = cmpro(D_DV, B_XIN, AM_DUK);                                    // c2 = Compress_dv(v)
      10'd192:  ins = pzero(L_ACC0);
      10'd193:  ins = pzero(L_ACC1);
      10'd194:  ins = h_xof(B_TMP, HM_XOFT, L_T);                                    // A^[j][i] = SampleNTT(rho || i || j)
      10'd195:  ins = pwm(1'b1, L_ACC0, L_T, L_YJ0);
      10'd196:  ins = pwm(1'b1, L_ACC1, L_T, L_YJ1);
      10'd197:  ins = u_loop(1'b1, 10'd194);
      10'd198:  ins = intt(L_ACC0);
      10'd199:  ins = intt(L_ACC1);
      10'd200:  ins = h_prf(E_R, 8'd0, HM_PKI2);                                     // + e1_i: PRF(r, k + i), eta2
      10'd201:  ins = cbd(L_ACC0, L_ACC1, 1'b1, 1'b0);
      10'd202:  ins = cmpro(D_DU, B_XIN, AM_DUI);                                    // c1 part i = Compress_du(u_i)
      10'd203:  ins = u_loop(1'b0, 10'd192);
      10'd204:  ins = s2s(E_K1, E_SK);                                               // K -> session key (masked)
      10'd205:  ins = u_set(ST_SKV);                                                 // role: initiator
      10'd206:  ins = u_br(BC_KEXP, 10'd208);
      10'd207:  ins = u_br(BC_ALWAYS, 10'd209);
      10'd208:  ins = s2b(E_SK, B_K, AM_NONE);                                       // TEST / PERSO: K to the host
      10'd209:  ins = szero(E_M);
      10'd210:  ins = szero(E_R);
      10'd211:  ins = szero(E_K1);
      10'd212:  ins = szero(E_CBD + 4'd0);
      10'd213:  ins = szero(E_CBD + 4'd1);
      10'd214:  ins = szero(E_CBD + 4'd2);
      10'd215:  ins = szero(E_CBD + 4'd3);
      10'd216:  ins = szero(E_CBD + 4'd4);
      10'd217:  ins = szero(E_CBD + 4'd5);
      10'd218:  ins = pzero(L_T);
      10'd219:  ins = pzero(L_ACC0);
      10'd220:  ins = pzero(L_ACC1);
      10'd221:  ins = pzero(L_YI0);
      10'd222:  ins = pzero(L_YI1);
      10'd223:  ins = u_loop(1'b0, 10'd221);
      10'd224:  ins = u_end(R_OK);
      10'd240:  ins = u_br(BC_NOKEY, 10'd1);
      10'd241:  ins = u_set(ST_RESEED);
      10'd242:  ins = pzero(L_Z);                                                    // (TVLA traces start here)
      10'd243:  ins = m_op(M_OKINI);
      10'd244:  ins = b2s(B_EKOWN, E_TMP, AM_48K);                                   // rho of the key in use ...
      10'd245:  ins = s2b(E_TMP, B_TMP, AM_NONE);                                    // ... to where the XOF reads it
      10'd246:  ins = szero(E_TMP);
      10'd247:  ins = pzero(L_ACC0);
      10'd248:  ins = pzero(L_ACC1);
      10'd249:  ins = dec(DM_WR, D_DU, 1'b0, B_XIN, L_T, AM_DUI);                    // u'_i
      10'd250:  ins = ntt(L_T);
      10'd251:  ins = pwm(1'b1, L_ACC0, L_SI0, L_T);
      10'd252:  ins = pwm(1'b1, L_ACC1, L_SI1, L_T);
      10'd253:  ins = u_loop(1'b0, 10'd249);
      10'd254:  ins = intt(L_ACC0);
      10'd255:  ins = intt(L_ACC1);
      10'd256:  ins = dec(DM_RSUB, D_DV, 1'b0, B_XIN, L_ACC0, AM_DUK);               // w0 = v' - acc0
      10'd257:  ins = cmpr1(E_MP);                                                   // m' (fresh masks, fresh order) ...
      10'd258:  ins = cmpr1(E_CBD + 4'd1);                                           // ... again (scratch entry)
      10'd259:  ins = seq(E_MP, E_CBD + 4'd1);                                       // the two decodings must agree
      10'd260:  ins = h_g(E_MP, E_H, E_K1, E_R);                                     // (K', r') = G(m' || h)
      10'd261:  ins = h_j(1'b0);                                                     // K-bar = J(z || c), ciphertext lanes of k
      10'd262:  ins = h_prf(E_R, 8'd0, HM_PI1);                                      // y_i: PRF(r, i), eta1
      10'd263:  ins = cbd(L_YI0, L_YI1, 1'b0, 1'b1);
      10'd264:  ins = ntt(L_YI0);
      10'd265:  ins = ntt(L_YI1);
      10'd266:  ins = u_loop(1'b0, 10'd262);
      10'd267:  ins = pzero(L_ACC0);
      10'd268:  ins = pzero(L_ACC1);
      10'd269:  ins = h_xof(B_TMP, HM_XOFT, L_T);                                    // A^[j][i] = SampleNTT(rho || i || j)
      10'd270:  ins = pwm(1'b1, L_ACC0, L_T, L_YJ0);
      10'd271:  ins = pwm(1'b1, L_ACC1, L_T, L_YJ1);
      10'd272:  ins = u_loop(1'b1, 10'd269);
      10'd273:  ins = intt(L_ACC0);
      10'd274:  ins = intt(L_ACC1);
      10'd275:  ins = h_prf(E_R, 8'd0, HM_PKI2);                                     // + e1_i: PRF(r, k + i), eta2
      10'd276:  ins = cbd(L_ACC0, L_ACC1, 1'b1, 1'b0);
      10'd277:  ins = cmprc(D_DU, B_XIN, AM_DUI);                                    // c1 part i = Compress_du(u_i)
      10'd278:  ins = u_loop(1'b0, 10'd267);
      10'd279:  ins = pzero(L_ACC0);
      10'd280:  ins = pzero(L_ACC1);
      10'd281:  ins = dec(DM_WR, 4'd12, 1'b0, B_EKOWN, L_T, AM_48J);                 // t^_j
      10'd282:  ins = pwm(1'b1, L_ACC0, L_T, L_YJ0);
      10'd283:  ins = pwm(1'b1, L_ACC1, L_T, L_YJ1);
      10'd284:  ins = u_loop(1'b1, 10'd281);
      10'd285:  ins = intt(L_ACC0);
      10'd286:  ins = intt(L_ACC1);
      10'd287:  ins = h_prf(E_R, 8'd0, HM_P2K2);                                     // + e2: PRF(r, 2k), eta2
      10'd288:  ins = cbd(L_ACC0, L_ACC1, 1'b1, 1'b0);
      10'd289:  ins = mu(E_MP);                                                      // + mu (masked m)
      10'd290:  ins = cmprc(D_DV, B_XIN, AM_DUK);                                    // c2 = Compress_dv(v)
      10'd291:  ins = m_op(M_OKCHK);                                                 // the two ok copies must agree
      10'd292:  ins = u_mask(M_SEL, 4'd0, E_SK, 4'd0, 1'b0, B_K, E_K1, E_KB, 1'b1, AM_NONE, 1'b0); // K, kept masked
      10'd293:  ins = u_set(ST_SKVR);                                                // role: responder
      10'd294:  ins = u_br(BC_KEXP, 10'd296);
      10'd295:  ins = u_br(BC_ALWAYS, 10'd297);
      10'd296:  ins = s2b(E_SK, B_K, AM_NONE);                                       // TEST / PERSO: K to the host
      10'd297:  ins = szero(E_MP);
      10'd298:  ins = szero(E_K1);
      10'd299:  ins = szero(E_R);
      10'd300:  ins = szero(E_KB);
      10'd301:  ins = szero(E_CBD + 4'd0);
      10'd302:  ins = szero(E_CBD + 4'd1);
      10'd303:  ins = szero(E_CBD + 4'd2);
      10'd304:  ins = szero(E_CBD + 4'd3);
      10'd305:  ins = szero(E_CBD + 4'd4);
      10'd306:  ins = szero(E_CBD + 4'd5);
      10'd307:  ins = pzero(L_T);
      10'd308:  ins = pzero(L_ACC0);
      10'd309:  ins = pzero(L_ACC1);
      10'd310:  ins = pzero(L_YI0);
      10'd311:  ins = pzero(L_YI1);
      10'd312:  ins = u_loop(1'b0, 10'd310);
      10'd313:  ins = u_end(R_OK);
`ifndef PQSE_AES
      10'd320:  ins = u_br(BC_NOSK, 10'd5);
      10'd321:  ins = trunc(1'b0);                                                   // L in 1..128? M bytes from L on := 0
      10'd322:  ins = u_br(BC_BAD, 10'd0);                                           // (no counter used up)
      10'd323:  ins = u_set(ST_RESEED);
      10'd324:  ins = ctr(IO_CTRW);                                                  // header: counter, L, 0, 0
      10'd325:  ins = u_set(ST_TXINC);                                               // counted before use: never reused
      10'd326:  ins = u_br(BC_ROLE, 10'd331);
      10'd327:  ins = h_kks(KC_E1);                                                  // initiator -> responder
      10'd328:  ins = trunc(1'b0);                                                   // C bytes from L on := 0
      10'd329:  ins = h_ktag(SNK_SEED, KC_T1);
      10'd330:  ins = u_br(BC_ALWAYS, 10'd334);
      10'd331:  ins = h_kks(KC_E2);                                                  // responder -> initiator
      10'd332:  ins = trunc(1'b0);
      10'd333:  ins = h_ktag(SNK_SEED, KC_T2);
      10'd334:  ins = s2b(E_TAG, B_SM_TAG, AM_NONE);
      10'd335:  ins = szero(E_TAG);
      10'd336:  ins = u_end(R_OK);
`endif
`ifdef PQSE_AES
      10'd320:  ins = u_br(BC_NOSK, 10'd5);                                          // SEAL (PQSE_AES): AES-256-GCM in the GCM windows
      10'd321:  ins = u_aes(AO_HDR);                                                 // P, A (out of range: result 1)
      10'd322:  ins = u_br(BC_BAD, 10'd0);
      10'd323:  ins = u_set(ST_RESEED);
      10'd324:  ins = ctrg(IO_CTRW);                                                 // IV lane 0 := the send counter; the tag lanes := 0
      10'd325:  ins = u_set(ST_TXINC);                                               // counted before use: never reused
      10'd326:  ins = u_br(BC_ROLE, 10'd329);
      10'd327:  ins = h_kd(E_SK, 2'd2, 16'h3153);                                    // K = SHA3-256(SK || "S1"): initiator -> responder
      10'd328:  ins = u_br(BC_ALWAYS, 10'd975);                                      // encrypt, GHASH, the tag to B_GTAG
      10'd329:  ins = h_kd(E_SK, 2'd2, 16'h3253);                                    // K = SHA3-256(SK || "S2"): responder -> initiator
      10'd330:  ins = u_br(BC_ALWAYS, 10'd975);
`endif
`ifndef PQSE_AES
      10'd352:  ins = u_br(BC_NOSK, 10'd5);
      10'd353:  ins = ctr(IO_CTRC);                                                  // replay window check
      10'd354:  ins = u_br(BC_BAD, 10'd6);
      10'd355:  ins = trunc(1'b1);                                                   // length check only
      10'd356:  ins = u_br(BC_BAD, 10'd4);                                           // (a sender never seals such a length)
      10'd357:  ins = u_set(ST_RESEED);
      10'd358:  ins = m_op(M_OKINI);
      10'd359:  ins = u_br(BC_ROLE, 10'd362);
      10'd360:  ins = h_ktag(SNK_MCMP, KC_T2);                                       // initiator opens R -> I
      10'd361:  ins = u_br(BC_ALWAYS, 10'd363);
      10'd362:  ins = h_ktag(SNK_MCMP, KC_T1);                                       // responder opens I -> R
      10'd363:  ins = m_op(M_OKCHK);                                                 // the two ok copies must agree
      10'd364:  ins = m_op(M_OKOUT);
      10'd365:  ins = u_br(BC_BAD, 10'd4);                                           // stays encrypted, window unchanged
      10'd366:  ins = u_set(ST_RXACC);                                               // authentic: mark the counter
      10'd367:  ins = u_br(BC_ROLE, 10'd371);
      10'd368:  ins = h_kks(KC_E2);
      10'd369:  ins = trunc(1'b0);                                                   // plaintext bytes from L on := 0
      10'd370:  ins = u_end(R_OK);
      10'd371:  ins = h_kks(KC_E1);
      10'd372:  ins = trunc(1'b0);
      10'd373:  ins = u_end(R_OK);
`endif
`ifdef PQSE_AES
      10'd352:  ins = u_br(BC_NOSK, 10'd5);                                          // OPEN (PQSE_AES)
      10'd353:  ins = u_aes(AO_HDR);                                                 // P, A (out of range: result 9, a sender never seals that)
      10'd354:  ins = u_br(BC_BAD, 10'd4);
      10'd355:  ins = ctrg(IO_CTRC);                                                 // replay window check (the counter: IV lane 0)
      10'd356:  ins = u_br(BC_BAD, 10'd6);
      10'd357:  ins = u_set(ST_RESEED);
      10'd358:  ins = u_br(BC_ROLE, 10'd361);
      10'd359:  ins = h_kd(E_SK, 2'd2, 16'h3253);                                    // initiator opens R -> I: "S2"
      10'd360:  ins = u_br(BC_ALWAYS, 10'd975);                                      // GHASH, masked tag check, then decrypt (BC_GDEC)
      10'd361:  ins = h_kd(E_SK, 2'd2, 16'h3153);                                    // responder opens I -> R: "S1"
      10'd362:  ins = u_br(BC_ALWAYS, 10'd975);
`endif
      10'd384:  ins = u_set(ST_RESEED);
      10'd385:  ins = h_hek(B_EKOWN, E_H);
      10'd386:  ins = scmpn(E_H, B_INJH, 4'd0, AM_NONE);                             // dk hash check (4 lanes)
      10'd387:  ins = u_br(BC_BAD, 10'd0);
      10'd388:  ins = dec(DM_WR, 4'd12, 1'b0, B_XIN, L_SI0, AM_48I);                 // s^_i bytes
      10'd389:  ins = msplit(L_SI0, L_SI1);                                          // -> shares
      10'd390:  ins = u_loop(1'b0, 10'd388);
      10'd391:  ins = pzero(L_Z);
      10'd392:  ins = enc12(L_Z, B_XIN, AM_48I);                                     // wipe the s^ bytes (B_XIN becomes readable after ENCAPS)
      10'd393:  ins = u_loop(1'b0, 10'd392);
      10'd394:  ins = b2s(B_INJZ, E_Z, AM_NONE);
      10'd395:  ins = sremask(E_Z);
      10'd396:  ins = u_set(ST_KEYV);                                                // key_k := k
      10'd397:  ins = u_end(R_OK);
      10'd400:  ins = u_set(ST_RESEED);
      10'd401:  ins = h_trng(E_TMP);                                                 // k (masked)
      10'd402:  ins = u_puf(PF_ENROLL, E_TMP, B_HELP);                               // helper -> 15 lanes, k canonical
      10'd403:  ins = h_kchk(E_TMP, E_W0);
      10'd404:  ins = s2bn(E_W0, B_HELP_CHK, 4'd1);                                  // check value -> helper lane 15
      10'd405:  ins = szero(E_W0);
      10'd406:  ins = szero(E_TMP);
      10'd407:  ins = u_end(R_OK);
      10'd408:  ins = u_puf(PF_RAW, 4'd0, B_XIN);                                    // 960 bits -> 15 lanes
      10'd409:  ins = u_end(R_OK);
      10'd410:  ins = u_io(IO_T2B, DM_WR, 4'd0, 1'b0, 1'b0, B_XIN, 4'd0, 4'd0, 4'd0, AM_NONE); // 136 words
      10'd411:  ins = u_end(R_OK);
      10'd416:  ins = pzero(L_SI0);                                                  // slot 2i, i = 0..9: all 20 slots
      10'd417:  ins = pzero(L_SI1);
      10'd418:  ins = u_loopn(1'b0, 10'd416, 4'd10);
      10'd419:  ins = szero(4'd0);
      10'd420:  ins = szero(4'd1);
      10'd421:  ins = szero(4'd2);
      10'd422:  ins = szero(4'd3);
      10'd423:  ins = szero(4'd4);
      10'd424:  ins = szero(4'd5);
      10'd425:  ins = szero(4'd6);
      10'd426:  ins = szero(4'd7);
      10'd427:  ins = szero(4'd8);
      10'd428:  ins = szero(4'd9);
      10'd429:  ins = szero(4'd10);
      10'd430:  ins = szero(4'd11);
      10'd431:  ins = szero(4'd12);
      10'd432:  ins = szero(4'd13);
      10'd433:  ins = szero(4'd14);
      10'd434:  ins = szero(4'd15);
      10'd435:  ins = s2b(E_TMP, B_K, AM_NONE);                                      // E_TMP is 0 now
      10'd436:  ins = s2b(E_TMP, B_TMP, AM_NONE);
      10'd437:  ins = s2b(E_TMP, B_SM + 9'd0, AM_NONE);                              // secure-message window
      10'd438:  ins = s2b(E_TMP, B_SM + 9'd4, AM_NONE);
      10'd439:  ins = s2b(E_TMP, B_SM + 9'd8, AM_NONE);
      10'd440:  ins = s2b(E_TMP, B_SM + 9'd12, AM_NONE);
      10'd441:  ins = s2b(E_TMP, B_SM + 9'd16, AM_NONE);
      10'd442:  ins = s2b(E_TMP, B_SM + 9'd20, AM_NONE);
      10'd443:  ins = u_set(ST_KEYC);
      10'd444:  ins = u_set(ST_SKC);
`ifdef PQSE_DSA
      10'd445:  ins = u_br(BC_ALWAYS, 10'd647);                                      // PQSE_DSA: the ML-DSA polynomials too
`else
      10'd445:  ins = u_end(R_OK);
`endif
      10'd448:  ins = pzero(L_Z);                                                    // the all-zero slot (precharge reads)
      10'd449:  ins = h_trng(E_M);                                                   // m (masked)
      10'd450:  ins = h_hek(B_EKOWN, E_PH);                                          // H(ek) of the published ek
      10'd451:  ins = h_g(E_M, E_PH, E_K1, E_R);                                     // (K, r) = G(m || H(ek))
      10'd452:  ins = h_prf(E_R, 8'd0, HM_PI1);                                      // y_i: PRF(r, i), eta1
      10'd453:  ins = cbd(L_YI0, L_YI1, 1'b0, 1'b1);
      10'd454:  ins = ntt(L_YI0);
      10'd455:  ins = ntt(L_YI1);
      10'd456:  ins = u_loop(1'b0, 10'd452);
      10'd457:  ins = pzero(L_ACC0);
      10'd458:  ins = pzero(L_ACC1);
      10'd459:  ins = dec(DM_WR, 4'd12, 1'b0, B_EKOWN, L_T, AM_48J);                 // t^_j
      10'd460:  ins = pwm(1'b1, L_ACC0, L_T, L_YJ0);
      10'd461:  ins = pwm(1'b1, L_ACC1, L_T, L_YJ1);
      10'd462:  ins = u_loop(1'b1, 10'd459);
      10'd463:  ins = intt(L_ACC0);
      10'd464:  ins = intt(L_ACC1);
      10'd465:  ins = h_prf(E_R, 8'd0, HM_P2K2);                                     // + e2: PRF(r, 2k), eta2
      10'd466:  ins = cbd(L_ACC0, L_ACC1, 1'b1, 1'b0);
      10'd467:  ins = mu(E_M);                                                       // + mu (masked m)
      10'd468:  ins = cmpro(D_DV, B_XIN, AM_DUK);                                    // c2 = Compress_dv(v)
      10'd469:  ins = pzero(L_ACC0);
      10'd470:  ins = pzero(L_ACC1);
      10'd471:  ins = h_xof(B_TMP, HM_XOFT, L_T);                                    // A^[j][i] = SampleNTT(rho || i || j)
      10'd472:  ins = pwm(1'b1, L_ACC0, L_T, L_YJ0);
      10'd473:  ins = pwm(1'b1, L_ACC1, L_T, L_YJ1);
      10'd474:  ins = u_loop(1'b1, 10'd471);
      10'd475:  ins = intt(L_ACC0);
      10'd476:  ins = intt(L_ACC1);
      10'd477:  ins = h_prf(E_R, 8'd0, HM_PKI2);                                     // + e1_i: PRF(r, k + i), eta2
      10'd478:  ins = cbd(L_ACC0, L_ACC1, 1'b1, 1'b0);
      10'd479:  ins = cmpro(D_DU, B_XIN, AM_DUI);                                    // c1 part i = Compress_du(u_i)
      10'd480:  ins = u_loop(1'b0, 10'd469);
      10'd481:  ins = pzero(L_ACC0);
      10'd482:  ins = pzero(L_ACC1);
      10'd483:  ins = dec(DM_WR, D_DU, 1'b0, B_XIN, L_T, AM_DUI);
      10'd484:  ins = ntt(L_T);
      10'd485:  ins = pwm(1'b1, L_ACC0, L_SI0, L_T);
      10'd486:  ins = pwm(1'b1, L_ACC1, L_SI1, L_T);
      10'd487:  ins = u_loop(1'b0, 10'd483);
      10'd488:  ins = intt(L_ACC0);
      10'd489:  ins = intt(L_ACC1);
      10'd490:  ins = dec(DM_RSUB, D_DV, 1'b0, B_XIN, L_ACC0, AM_DUK);               // w0 = v' - acc0
      10'd491:  ins = cmpr1(E_TMP);                                                  // m'
      10'd492:  ins = h_g(E_TMP, E_H, E_KB, E_R);                                    // (K', r') = G(m' || h), h of dk
      10'd493:  ins = seq(E_K1, E_KB);                                               // K' != K: FAULT (key never valid)
      10'd494:  ins = szero(E_M);
      10'd495:  ins = szero(E_TMP);
      10'd496:  ins = szero(E_K1);
      10'd497:  ins = szero(E_KB);
      10'd498:  ins = pzero(L_ACC0);
      10'd499:  ins = pzero(L_ACC1);
      10'd500:  ins = u_br(BC_ALWAYS, 10'd122);                                      // the rest is wiped at L_KGEND
`ifdef PQSE_LMS
      10'd501:  ins = u_br(BC_LMS, 10'd530);                                         // L_PREC returns here: LMS
`elsif PQSE_DSA
      10'd501:  ins = u_br(BC_LMS, 10'd530);                                         // L_PREC returns here: LMS
`elsif PQSE_STORE
      10'd501:  ins = u_br(BC_LMS, 10'd530);                                         // L_PREC returns here: LMS
`elsif PQSE_AES
      10'd501:  ins = u_br(BC_LMS, 10'd530);                                         // L_PREC returns here: LMS
`endif
`ifdef PQSE_DSA
`ifndef PQSE_DSA_VER
      10'd502:  ins = u_br5(BC_DSA, 10'd755);                                        // ... ML-DSA (DSAGEN, DSASIGN)
`else
      10'd502:  ins = u_br(BC_ALWAYS, 10'd503);
`endif
`else
      10'd502:  ins = u_br(BC_ALWAYS, 10'd503);
`endif
`ifdef PQSE_STORE
      10'd503:  ins = u_br5(BC_ST, 10'd912);                                         // ... record store (STREAD, STWRITE, STDEL)
`else
      10'd503:  ins = u_br(BC_ALWAYS, 10'd504);
`endif
`ifdef PQSE_AES
      10'd504:  ins = u_br5(BC_AES, 10'd964);                                        // ... AES (AESGEN, GCMENC / GCMDEC with the blob)
`else
      10'd504:  ins = u_br(BC_ALWAYS, 10'd505);
`endif
`ifdef PQSE_LMS
      10'd505:  ins = u_br(BC_ALWAYS, 10'd34);                                       // ... UNWRAP
`elsif PQSE_DSA
      10'd505:  ins = u_br(BC_ALWAYS, 10'd34);                                       // ... UNWRAP
`elsif PQSE_STORE
      10'd505:  ins = u_br(BC_ALWAYS, 10'd34);                                       // ... UNWRAP
`elsif PQSE_AES
      10'd505:  ins = u_br(BC_ALWAYS, 10'd34);                                       // ... UNWRAP
`endif
`ifdef PQSE_LMS
      10'd512:  ins = u_set(ST_RESEED);
      10'd513:  ins = u_br(BC_ALWAYS, 10'd48);                                       // PUF key -> KEK, back through L_PRET
      10'd528:  ins = u_set(ST_RESEED);
      10'd529:  ins = u_br(BC_ALWAYS, 10'd48);
      10'd530:  ins = u_br(BC_LMSG, 10'd565);
      10'd531:  ins = m_op(M_OKINI);                                                 // LMSLEAF / LMSSIGN: unwrap the LMS blob
      10'd532:  ins = h_ltag(SNK_MCMP);                                              // masked tag check (suffix L || H)
      10'd533:  ins = m_op(M_OKCHK);
      10'd534:  ins = m_op(M_OKOUT);
      10'd535:  ins = u_br(BC_BAD, 10'd589);
      10'd536:  ins = b2s(B_BLOB_CT, E_W0, AM_NONE);
      10'd537:  ins = b2s(B_BLOB_CT + 9'd4, E_W1, AM_NONE);
      10'd538:  ins = h_ks(E_W0, E_W1);                                              // SEED, I now masked plaintext
      10'd539:  ins = szero(E_KEK);
      10'd540:  ins = s2bn(E_W1, B_LMS_I, 4'd2);                                     // I is public
      10'd541:  ins = szero(E_W1);
      10'd542:  ins = u_br(BC_HSS, 10'd597);                                         // two levels (PQSE_LMS_HSS): its own programs
      10'd543:  ins = u_br(BC_LMSS, 10'd548);
      10'd544:  ins = u_lms(LO_QLD);                                                 // LMSLEAF: q from the host
      10'd545:  ins = u_br(BC_BAD, 10'd591);
      10'd546:  ins = u_lms(LO_LEAF);                                                // the 67 chain ends of leaf q -> B_LMS_Y
      10'd547:  ins = u_br(BC_ALWAYS, 10'd562);
      10'd548:  ins = u_lms(LO_BIND);                                                // the counter belongs to this key?
      10'd549:  ins = u_br(BC_BAD, 10'd593);
      10'd550:  ins = u_lms(LO_BEGIN);                                               // q := counter, burned first (write-ahead)
      10'd551:  ins = u_br(BC_BAD, 10'd595);
      10'd552:  ins = u_br(BC_INJ, 10'd555);
      10'd553:  ins = h_trng(E_TMP);                                                 // C
      10'd554:  ins = u_br(BC_ALWAYS, 10'd557);
      10'd555:  ins = b2s(B_INJM, E_TMP, AM_NONE);                                   // TEST: injected C
      10'd556:  ins = sremask(E_TMP);
      10'd557:  ins = s2b(E_TMP, B_LMS_C, AM_NONE);                                  // C is public
      10'd558:  ins = szero(E_TMP);
      10'd559:  ins = u_lms(LO_MSG);                                                 // Q = H(I || q || D_MESG || C || M)
      10'd560:  ins = u_lms(LO_SIGN);                                                // y[i] = chain i to digit i of Q || Cksm
      10'd561:  ins = u_lms(LO_INFO);
      10'd562:  ins = szero(E_W0);
      10'd563:  ins = szero(E_TMP);
      10'd564:  ins = u_end(R_OK);
      10'd565:  ins = u_br(BC_INJ, 10'd569);                                         // LMSGEN
      10'd566:  ins = h_trng(E_W0);                                                  // SEED (masked)
      10'd567:  ins = h_trng(E_W1);                                                  // I (lanes 0, 1)
      10'd568:  ins = u_br(BC_ALWAYS, 10'd573);
      10'd569:  ins = b2s(B_INJD, E_W0, AM_NONE);                                    // TEST: injected SEED, I
      10'd570:  ins = sremask(E_W0);
      10'd571:  ins = b2s(B_INJZ, E_W1, AM_NONE);
      10'd572:  ins = sremask(E_W1);
      10'd573:  ins = s2bn(E_W1, B_LMS_I, 4'd2);                                     // I is public
      10'd574:  ins = u_lms(LO_KEYRST);                                              // counter := 0, bound to the new I
      10'd575:  ins = h_trng(E_TMP);
      10'd576:  ins = s2bn(E_TMP, B_BLOB_NONCE, 4'd2);                               // nonce (2 lanes)
      10'd577:  ins = szero(E_TMP);
      10'd578:  ins = h_ks(E_W0, E_W1);                                              // encrypted in place
      10'd579:  ins = s2b(E_W0, B_BLOB_CT, AM_NONE);                                 // ciphertext is public
      10'd580:  ins = s2b(E_W1, B_BLOB_CT + 9'd4, AM_NONE);
      10'd581:  ins = h_ltag(SNK_SEED);
      10'd582:  ins = s2b(E_TAG, B_BLOB_TAG, AM_NONE);
      10'd583:  ins = szero(E_TAG);
      10'd584:  ins = szero(E_W0);
      10'd585:  ins = szero(E_W1);
      10'd586:  ins = szero(E_KEK);
      10'd587:  ins = u_lms(LO_INFO);
      10'd588:  ins = u_end(R_OK);
      10'd589:  ins = szero(E_KEK);                                                  // the blob's tag did not check out
      10'd590:  ins = u_br(BC_ALWAYS, 10'd2);
      10'd591:  ins = szero(E_W0);                                                   // q out of range
      10'd592:  ins = u_br(BC_ALWAYS, 10'd0);
      10'd593:  ins = szero(E_W0);                                                   // another key's counter
      10'd594:  ins = u_end(R_LMSKEY);
      10'd595:  ins = szero(E_W0);                                                   // no signature left
      10'd596:  ins = u_end(R_LMSEXH);
`endif
`ifdef PQSE_LMS_HSS
      10'd597:  ins = u_br(BC_LMSS, 10'd604);
      10'd598:  ins = u_br(BC_LMSN, 10'd620);
      10'd599:  ins = u_lms(LO_QLD);                                                 // LMSLEAF: {level, p, q} from the host
      10'd600:  ins = u_br(BC_BAD, 10'd591);
      10'd601:  ins = u_lms(LO_DERIV);                                               // bottom tree p (used for level 1)
      10'd602:  ins = u_lms(LO_LEAF);                                                // the 67 chain ends of leaf q -> B_LMS_Y
      10'd603:  ins = u_br(BC_ALWAYS, 10'd642);
      10'd604:  ins = u_lms(LO_BIND);                                                // the counter belongs to this key?
      10'd605:  ins = u_br(BC_BAD, 10'd593);
      10'd606:  ins = u_lms(LO_BEGIN);                                               // tree p, leaf b := counter, burned first; the bottom tree
      10'd607:  ins = u_br(BC_BAD, 10'd595);
      10'd608:  ins = u_br(BC_INJ, 10'd611);
      10'd609:  ins = h_trng(E_TMP);                                                 // C
      10'd610:  ins = u_br(BC_ALWAYS, 10'd613);
      10'd611:  ins = b2s(B_INJM, E_TMP, AM_NONE);                                   // TEST: injected C
      10'd612:  ins = sremask(E_TMP);
      10'd613:  ins = s2b(E_TMP, B_LMS_C, AM_NONE);                                  // C is public
      10'd614:  ins = szero(E_TMP);
      10'd615:  ins = u_lms(LO_DERIV);                                               // bottom tree p's SEED, I
      10'd616:  ins = u_lms(LO_MSG);                                                 // Q = H(I_p || b || D_MESG || C || M)
      10'd617:  ins = u_lms(LO_SIGN);
      10'd618:  ins = u_lms(LO_INFO);
      10'd619:  ins = u_br(BC_ALWAYS, 10'd642);
      10'd620:  ins = u_lms(LO_BIND);                                                // LMSNEXT
      10'd621:  ins = u_br(BC_BAD, 10'd593);
      10'd622:  ins = u_lms(LO_NEXT);                                                // top leaf p burned (the rest of the current tree first)
      10'd623:  ins = u_br(BC_BAD, 10'd595);
      10'd624:  ins = u_lms(LO_DERIV);                                               // bottom tree p's SEED, I
      10'd625:  ins = u_lmsb(LO_LVL, 1'b1);
      10'd626:  ins = u_lms(LO_ROOT);                                                // its root -> B_LMS_M (every leaf, here on the card)
      10'd627:  ins = u_lmsb(LO_LVL, 1'b0);                                          // top leaf p signs
      10'd628:  ins = u_br(BC_INJ, 10'd631);
      10'd629:  ins = h_trng(E_TMP);                                                 // C
      10'd630:  ins = u_br(BC_ALWAYS, 10'd633);
      10'd631:  ins = b2s(B_INJM, E_TMP, AM_NONE);                                   // TEST: injected C
      10'd632:  ins = sremask(E_TMP);
      10'd633:  ins = s2b(E_TMP, B_LMS_C, AM_NONE);                                  // C is public
      10'd634:  ins = s2b(E_TMP, B_LMS_X, AM_NONE);                                  // the message: C ||
      10'd635:  ins = szero(E_TMP);
      10'd636:  ins = s2bn(E_PH, B_LMS_X + 9'd5, 4'd2);                              // ... types || I_p || root (LO_PUB)
      10'd637:  ins = u_lms(LO_PUB);
      10'd638:  ins = u_lmsb(LO_MSG, 1'b1);                                          // Q = H(I || p || D_MESG || C || bottom public key)
      10'd639:  ins = u_lms(LO_SIGN);
      10'd640:  ins = u_lms(LO_INFO);
      10'd641:  ins = s2bn(E_PH, B_LMS_Q, 4'd2);                                     // I_p for the host (in place of Q)
      10'd642:  ins = szero(E_W0);
      10'd643:  ins = szero(E_W1);
      10'd644:  ins = szero(E_PH);
      10'd645:  ins = szero(E_TMP);
      10'd646:  ins = u_end(R_OK);
`endif
`ifdef PQSE_DSA
      10'd647:  ins = d_zero(dpi(4'd10));                                            // ZEROIZE (PQSE_DSA): also polynomials 10..15 (slots 20..31)
      10'd648:  ins = u_loopn(1'b0, 10'd647, 4'd6);
      10'd649:  ins = u_set(ST_PKC);                                                 // ... and the loaded public key
      10'd650:  ins = u_end(R_OK);
`endif
`ifdef PQSE_DSA
`ifndef PQSE_DSA_VER
      10'd704:  ins = u_set(ST_RESEED);                                              // DSAGEN, DSASIGN
      10'd705:  ins = u_br(BC_ALWAYS, 10'd48);                                       // PUF key -> KEK, back through L_PRET
`endif
`endif
`ifdef PQSE_DSA
      10'd712:  ins = u_set(ST_PKC);                                                 // the parameter set is the new key's (CONFIG[5:4]) from here on
      10'd713:  ins = d_dec(DM_R8, B_DPK, LM_0, dp(4'd11));                          // rho -> P11 (a byte per word)
      10'd714:  ins = d_dec(DM_T1P, B_DPK + 10'd4, LM_0, dp(4'd12));                 // t1 rows 0, 1 (two coefficients a word) -> P12
      10'd715:  ins = d_dec(DM_T1P, B_DPK + 10'd84, LM_0, dp(4'd13));                // rows 2, 3 -> P13
`endif
`ifdef PQSE_DSA_VER
      10'd716:  ins = u_br5(BC_DL65, 10'd808);                                       // ML-DSA-65 / 87: the other rows
`else
      10'd716:  ins = u_set(ST_PKC);
`endif
`ifdef PQSE_DSA_VER
      10'd717:  ins = u_br5(BC_DL87, 10'd807);
`else
      10'd717:  ins = u_set(ST_PKC);
`endif
`ifdef PQSE_DSA
      10'd718:  ins = u_set(ST_PKV);
      10'd719:  ins = u_end(R_OK);
      10'd720:  ins = u_br5(BC_NOPK, 10'd1);                                         // DSAPK or DSAGEN first
      10'd721:  ins = u_set(ST_KEYC);                                                // polynomials 0..10 are ML-KEM's slots: its key is gone
`endif
`ifdef PQSE_DSA_VER
      10'd722:  ins = u_br5(BC_DL65, 10'd755);                                       // the loaded key's parameter set
`else
      10'd722:  ins = u_set(ST_KEYC);
`endif
`ifdef PQSE_DSA_VER
      10'd723:  ins = u_br5(BC_DL87, 10'd781);
`else
      10'd723:  ins = u_set(ST_KEYC);
`endif
`ifdef PQSE_DSA
      10'd724:  ins = d_enc(DM_R8, dp(4'd11), B_DRHO, LM_0);                         // rho of the loaded key, for ExpandA
      10'd725:  ins = d_dec(DM_Z, B_DSIG + 10'd4, LM_I72, dpi(4'd0));                // z_j; BAD if |z_j| >= gamma1 - beta
      10'd726:  ins = d_ntt(dpi(4'd0));
      10'd727:  ins = u_loopn(1'b0, 10'd725, 4'd4);
      10'd728:  ins = u_br(BC_BAD, 10'd748);
      10'd729:  ins = d_zero(dp(4'd7));
      10'd730:  ins = h_dball(SRC_BUF, 8'd4, 4'd7);                                  // c = SampleInBall(c~ of the signature) -> P7
      10'd731:  ins = d_ntt(dp(4'd7));
      10'd732:  ins = d_zero(dp(4'd8));
      10'd733:  ins = h_dxof(B_DRHO, 4'd9);                                          // A^[i][j] -> P9
      10'd734:  ins = d_pwm(1'b1, dp(4'd8), dp(4'd9), dpj(4'd0));                    // + A^[i][j] o z^_j
      10'd735:  ins = u_loopn(1'b1, 10'd733, 4'd4);
      10'd736:  ins = d_t1x(dp(4'd9), dp(4'd12), dpi(4'd0));                         // t1_i 2^13 -> P9 ...
      10'd737:  ins = d_ntt(dp(4'd9));
      10'd738:  ins = d_pwm(1'b0, dp(4'd9), dp(4'd9), dp(4'd7));                     // ... o c^
      10'd739:  ins = d_sub(dp(4'd8), dp(4'd9));
      10'd740:  ins = d_intt(dp(4'd8));                                              // w'_approx_i -> P8
      10'd741:  ins = d_hdec(dp(4'd8), dpi(4'd0), {1'b0, B_DHINT});                  // its hints -> bit 23 (BAD: malformed)
      10'd742:  ins = d_enc(DM_UH, dp(4'd8), B_DW1, LM_I24);                         // w1'_i = UseHint(h_i, w'_approx_i)
      10'd743:  ins = u_loopn(1'b0, 10'd732, 4'd4);
      10'd744:  ins = d_hvend({1'b0, B_DHINT});                                      // BAD unless the unused position bytes are 0
      10'd745:  ins = u_br(BC_BAD, 10'd748);
      10'd746:  ins = h_dch(8'd96, 8'd4);                                            // c~' = H(mu || w1Encode(w1')) -> E_DCT (, E_DCT2)
      10'd747:  ins = scmpn(E_DCT, B_DSIG, 4'd0, AM_NONE);                           // BAD unless c~' = c~
      10'd748:  ins = szero(E_DCT);
      10'd749:  ins = szero(E_DCT2);
      10'd750:  ins = d_zero(dpi(4'd0));                                             // polynomials 0..10 (the loaded key stays)
      10'd751:  ins = u_loopn(1'b0, 10'd750, 4'd11);
      10'd752:  ins = u_br(BC_BAD, 10'd754);
      10'd753:  ins = u_end(R_OK);
      10'd754:  ins = u_end(R_BADSIG);
`endif
`ifdef PQSE_DSA_VER
      10'd755:  ins = d_enc(DM_R8, dp(4'd11), B_DRHO, LM_0);                         // ML-DSA-65: rho of the loaded key, for ExpandA
      10'd756:  ins = d_dec(DM_Z, B_DSIG + 10'd6, LM_I80, dpi(4'd0));                // z_j; BAD if |z_j| >= gamma1 - beta
      10'd757:  ins = d_ntt(dpi(4'd0));
      10'd758:  ins = u_loopn(1'b0, 10'd756, 4'd5);
      10'd759:  ins = u_br(BC_BAD, 10'd748);
      10'd760:  ins = d_zero(dp(4'd7));
      10'd761:  ins = h_dball(SRC_BUF, 8'd6, 4'd7);                                  // c = SampleInBall(c~ of the signature) -> P7
      10'd762:  ins = d_ntt(dp(4'd7));
      10'd763:  ins = d_zero(dp(4'd8));
      10'd764:  ins = h_dxof(B_DRHO, 4'd9);                                          // A^[i][j] -> P9
      10'd765:  ins = d_pwm(1'b1, dp(4'd8), dp(4'd9), dpj(4'd0));                    // + A^[i][j] o z^_j
      10'd766:  ins = u_loopn(1'b1, 10'd764, 4'd5);
      10'd767:  ins = d_t1x(dp(4'd9), dp(4'd12), dpi(4'd0));                         // t1_i 2^13 -> P9 ...
      10'd768:  ins = d_ntt(dp(4'd9));
      10'd769:  ins = d_pwm(1'b0, dp(4'd9), dp(4'd9), dp(4'd7));                     // ... o c^
      10'd770:  ins = d_sub(dp(4'd8), dp(4'd9));
      10'd771:  ins = d_intt(dp(4'd8));                                              // w'_approx_i -> P8
      10'd772:  ins = d_hdec(dp(4'd8), dpi(4'd0), {1'b0, B_DSIG} + 10'd406);         // its hints -> bit 23 (BAD: malformed)
      10'd773:  ins = d_enc(DM_UH, dp(4'd8), B_DW1, LM_I16);                         // w1'_i = UseHint(h_i, w'_approx_i)
      10'd774:  ins = u_loopn(1'b0, 10'd763, 4'd6);
      10'd775:  ins = d_hvend({1'b0, B_DSIG} + 10'd406);                             // BAD unless the unused position bytes are 0
      10'd776:  ins = u_br(BC_BAD, 10'd748);
      10'd777:  ins = h_dch(8'd96, 8'd6);                                            // c~' = H(mu || w1Encode(w1')) -> E_DCT (, E_DCT2)
      10'd778:  ins = scmpn(E_DCT2, B_DSIG + 9'd4, 4'd2, AM_NONE);
      10'd779:  ins = scmpn(E_DCT, B_DSIG, 4'd0, AM_NONE);                           // BAD unless c~' = c~
      10'd780:  ins = u_br(BC_ALWAYS, 10'd748);
      10'd781:  ins = d_enc(DM_R8, dp(4'd11), B_DRHO, LM_0);                         // ML-DSA-87: rho of the loaded key, for ExpandA
      10'd782:  ins = d_dec(DM_Z, B_DSIG + 10'd8, LM_I80, dpi(4'd0));                // z_j; BAD if |z_j| >= gamma1 - beta
      10'd783:  ins = d_ntt(dpi(4'd0));
      10'd784:  ins = u_loopn(1'b0, 10'd782, 4'd7);
      10'd785:  ins = u_br(BC_BAD, 10'd748);
      10'd786:  ins = d_zero(dp(4'd7));
      10'd787:  ins = h_dball(SRC_BUF, 8'd8, 4'd7);                                  // c = SampleInBall(c~ of the signature) -> P7
      10'd788:  ins = d_ntt(dp(4'd7));
      10'd789:  ins = d_zero(dp(4'd8));
      10'd790:  ins = h_dxof(B_DRHO, 4'd9);                                          // A^[i][j] -> P9
      10'd791:  ins = d_pwm(1'b1, dp(4'd8), dp(4'd9), dpj(4'd0));                    // + A^[i][j] o z^_j
      10'd792:  ins = u_loopn(1'b1, 10'd790, 4'd7);
      10'd793:  ins = d_t1x(dp(4'd9), dp(4'd12), dpi(4'd0));                         // t1_i 2^13 -> P9 ...
      10'd794:  ins = d_ntt(dp(4'd9));
      10'd795:  ins = d_pwm(1'b0, dp(4'd9), dp(4'd9), dp(4'd7));                     // ... o c^
      10'd796:  ins = d_sub(dp(4'd8), dp(4'd9));
      10'd797:  ins = d_intt(dp(4'd8));                                              // w'_approx_i -> P8
      10'd798:  ins = d_hdec(dp(4'd8), dpi(4'd0), {1'b0, B_DSIG} + 10'd568);         // its hints -> bit 23 (BAD: malformed)
      10'd799:  ins = d_enc(DM_UH, dp(4'd8), B_DW1, LM_I16);                         // w1'_i = UseHint(h_i, w'_approx_i)
      10'd800:  ins = u_loopn(1'b0, 10'd789, 4'd8);
      10'd801:  ins = d_hvend({1'b0, B_DSIG} + 10'd568);                             // BAD unless the unused position bytes are 0
      10'd802:  ins = u_br(BC_BAD, 10'd748);
      10'd803:  ins = h_dch(8'd128, 8'd8);                                           // c~' = H(mu || w1Encode(w1')) -> E_DCT (, E_DCT2)
      10'd804:  ins = scmpn(E_DCT2, B_DSIG + 9'd4, 4'd0, AM_NONE);
      10'd805:  ins = scmpn(E_DCT, B_DSIG, 4'd0, AM_NONE);                           // BAD unless c~' = c~
      10'd806:  ins = u_br(BC_ALWAYS, 10'd748);
      10'd807:  ins = d_dec(DM_T1P, B_DPK + 10'd244, LM_0, dp(4'd15));               // ML-DSA-87: rows 6, 7 -> P15
      10'd808:  ins = d_dec(DM_T1P, B_DPK + 10'd164, LM_0, dp(4'd14));               // ML-DSA-65 / 87: rows 4, 5 -> P14
      10'd809:  ins = u_br(BC_ALWAYS, 10'd718);
`endif
`ifdef PQSE_DSA
`ifndef PQSE_DSA_VER
      10'd755:  ins = u_br5(BC_DSAG, 10'd779);
      10'd756:  ins = m_op(M_OKINI);                                                 // DSASIGN: unwrap the ML-DSA blob
      10'd757:  ins = h_dtag(SNK_MCMP);                                              // masked tag check (suffix D || 44)
      10'd758:  ins = m_op(M_OKCHK);
      10'd759:  ins = m_op(M_OKOUT);
      10'd760:  ins = u_br(BC_BAD, 10'd777);
      10'd761:  ins = b2s(B_BLOB_CT, E_W0, AM_NONE);
      10'd762:  ins = b2s(B_BLOB_CT + 9'd4, E_W1, AM_NONE);
      10'd763:  ins = h_ks(E_W0, E_W1);                                              // xi now masked plaintext (E_W1: 32 zero bytes)
      10'd764:  ins = szero(E_KEK);
      10'd765:  ins = szero(E_W1);
      10'd766:  ins = u_br(BC_INJ, 10'd769);
      10'd767:  ins = h_trng(E_DRND);                                                // rnd from the TRNG (hedged signing)
      10'd768:  ins = u_br(BC_ALWAYS, 10'd771);
      10'd769:  ins = b2s(B_INJM, E_DRND, AM_NONE);                                  // TEST: injected rnd (known answers)
      10'd770:  ins = sremask(E_DRND);
      10'd771:  ins = h_dexp(E_W0);                                                  // (rho, rho', K) = H(xi || 4 || 4) -> E_DRHO, E_DRHOP, E_DK
      10'd772:  ins = szero(E_W0);
      10'd773:  ins = h_drho2(1'b0);                                                 // rho'' = H(K || rnd || mu) -> E_DRHO2
      10'd774:  ins = szero(E_DK);
      10'd775:  ins = szero(E_DRND);
      10'd776:  ins = u_br(BC_ALWAYS, 10'd800);
      10'd777:  ins = szero(E_KEK);                                                  // the blob's tag did not check out
      10'd778:  ins = u_br(BC_ALWAYS, 10'd2);
      10'd779:  ins = u_br(BC_INJ, 10'd782);                                         // DSAGEN
      10'd780:  ins = h_trng(E_W0);                                                  // xi (masked)
      10'd781:  ins = u_br(BC_ALWAYS, 10'd784);
      10'd782:  ins = b2s(B_INJD, E_W0, AM_NONE);                                    // TEST: injected xi
      10'd783:  ins = sremask(E_W0);
      10'd784:  ins = h_dexp(E_W0);                                                  // (rho, rho', K) = H(xi || 4 || 4)
      10'd785:  ins = szero(E_DK);                                                   // K: signing only
      10'd786:  ins = szero(E_W1);                                                   // the blob's plaintext: xi || 32 zero bytes
      10'd787:  ins = h_trng(E_TMP);
      10'd788:  ins = s2bn(E_TMP, B_BLOB_NONCE, 4'd2);                               // nonce (2 lanes)
      10'd789:  ins = szero(E_TMP);
      10'd790:  ins = h_ks(E_W0, E_W1);                                              // encrypted in place
      10'd791:  ins = s2b(E_W0, B_BLOB_CT, AM_NONE);                                 // ciphertext is public
      10'd792:  ins = s2b(E_W1, B_BLOB_CT + 9'd4, AM_NONE);
      10'd793:  ins = h_dtag(SNK_SEED);
      10'd794:  ins = s2b(E_TAG, B_BLOB_TAG, AM_NONE);
      10'd795:  ins = szero(E_TAG);
      10'd796:  ins = szero(E_W0);
      10'd797:  ins = szero(E_W1);
      10'd798:  ins = szero(E_KEK);
      10'd799:  ins = s2b(E_DRHO, B_DPK, AM_NONE);                                   // pk = rho || t1
      10'd800:  ins = u_set(ST_KEYC);                                                // polynomials 0..10 are ML-KEM's slots: its key is gone
      10'd801:  ins = s2b(E_DRHO, B_DRHOS, AM_NONE);                                 // rho is public: where ExpandA reads it
      10'd802:  ins = szero(E_DRHO);
      10'd803:  ins = h_dexps(8'd0, DI_I, 4'd0);                                     // s1_i = ExpandS(rho', i) -> P0+i
      10'd804:  ins = d_ntt(dpi(4'd0));
      10'd805:  ins = u_loopn(1'b0, 10'd803, 4'd4);
      10'd806:  ins = d_zero(dpi(4'd11));
      10'd807:  ins = h_dxof(B_DRHOS, 4'd8);                                         // A^[i][j] -> P8
      10'd808:  ins = d_pwm(1'b1, dpi(4'd11), dp(4'd8), dpj(4'd0));                  // + A^[i][j] o s1^_j
      10'd809:  ins = u_loopn(1'b1, 10'd807, 4'd4);
      10'd810:  ins = d_intt(dpi(4'd11));
      10'd811:  ins = h_dexps(8'd4, DI_0, 4'd8);                                     // s2_i = ExpandS(rho', 4 + i) -> P8
      10'd812:  ins = d_add(dpi(4'd11), dp(4'd8));                                   // t_i -> P11+i
      10'd813:  ins = u_loopn(1'b0, 10'd806, 4'd4);
      10'd814:  ins = u_br5(BC_DSAS, 10'd828);
      10'd815:  ins = szero(E_DRHOP);                                                // DSAGEN: rho' no longer needed
      10'd816:  ins = szero(E_DRHOP + 4'd1);
      10'd817:  ins = d_enc(DM_T1, dpi(4'd11), B_DPK + 10'd4, LM_I40);               // t1_i -> pk
      10'd818:  ins = u_loopn(1'b0, 10'd817, 4'd4);
      10'd819:  ins = d_dec(DM_T1P, B_DPK + 10'd4, LM_0, dp(4'd12));                 // the loaded key (DSAVER), as DSAPK: t1 -> P12, 13
      10'd820:  ins = d_dec(DM_T1P, B_DPK + 10'd84, LM_0, dp(4'd13));
      10'd821:  ins = d_zero(dp(4'd11));                                             // (t_0, t_3)
      10'd822:  ins = d_zero(dp(4'd14));
      10'd823:  ins = d_dec(DM_R8, B_DRHOS, LM_0, dp(4'd11));                        // rho -> P11
      10'd824:  ins = u_set(ST_PKV);
      10'd825:  ins = d_zero(dpi(4'd0));                                             // polynomials 0..10
      10'd826:  ins = u_loopn(1'b0, 10'd825, 4'd11);
      10'd827:  ins = u_end(R_OK);
      10'd828:  ins = d_p2r(dpi(4'd11), 1'b0);                                       // t0_i ...
      10'd829:  ins = d_ntt(dpi(4'd11));                                             // ... t0^_i -> P11+i
      10'd830:  ins = u_loopn(1'b0, 10'd828, 4'd4);
      10'd831:  ins = u_set(ST_PKC);                                                 // P11..14 no longer hold a public key
      10'd832:  ins = u_set(ST_KAPZ);                                                // kappa := 0
      10'd833:  ins = h_dmask(1'b0);                                                 // attempt: y_i = ExpandMask(rho'', kappa + i) -> P0+i
      10'd834:  ins = d_ntt(dpi(4'd0));
      10'd835:  ins = u_loopn(1'b0, 10'd833, 4'd4);
      10'd836:  ins = d_zero(dpi(4'd4));
      10'd837:  ins = h_dxof(B_DRHOS, 4'd8);                                         // A^[i][j] -> P8
      10'd838:  ins = d_pwm(1'b1, dpi(4'd4), dp(4'd8), dpj(4'd0));                   // + A^[i][j] o y^_j
      10'd839:  ins = u_loopn(1'b1, 10'd837, 4'd4);
      10'd840:  ins = d_intt(dpi(4'd4));                                             // w_i -> P4+i
      10'd841:  ins = d_enc(DM_W1, dpi(4'd4), B_DW1, LM_I24);                        // w1_i -> scratch lanes
      10'd842:  ins = u_loopn(1'b0, 10'd836, 4'd4);
      10'd843:  ins = h_dch(8'd96, 8'd4);                                            // c~ = H(mu || w1Encode(w1)) -> E_DCT
      10'd844:  ins = d_zero(dp(4'd9));
      10'd845:  ins = h_dball(SRC_SEED, 8'd4, 4'd9);                                 // c = SampleInBall(c~) -> P9
      10'd846:  ins = d_ntt(dp(4'd9));
      10'd847:  ins = h_dexps(8'd0, DI_0, 4'd8);                                     // s1_i -> P8 (regenerated)
      10'd848:  ins = d_ntt(dp(4'd8));
      10'd849:  ins = d_pwm(1'b0, dp(4'd8), dp(4'd8), dp(4'd9));                     // c^ o s1^_i
      10'd850:  ins = d_add(dpi(4'd0), dp(4'd8));                                    // z^_i = y^_i + c^ o s1^_i
      10'd851:  ins = d_intt(dpi(4'd0));                                             // z_i -> P0+i
      10'd852:  ins = d_zchk(dpi(4'd0));                                             // BAD if |z_i| >= gamma1 - beta
      10'd853:  ins = u_loopn(1'b0, 10'd847, 4'd4);
      10'd854:  ins = u_br(BC_BAD, 10'd886);
      10'd855:  ins = h_dexps(8'd4, DI_0, 4'd8);                                     // s2_i -> P8
      10'd856:  ins = d_ntt(dp(4'd8));
      10'd857:  ins = d_pwm(1'b0, dp(4'd8), dp(4'd8), dp(4'd9));
      10'd858:  ins = d_intt(dp(4'd8));                                              // c s2_i
      10'd859:  ins = d_sub(dpi(4'd4), dp(4'd8));                                    // r_i = w_i - c s2_i -> P4+i
      10'd860:  ins = u_loopn(1'b0, 10'd855, 4'd4);
      10'd861:  ins = d_hcnt(B_DHS);                                                 // the hint byte stream, into scratch lanes
      10'd862:  ins = d_pwm(1'b0, dp(4'd10), dp(4'd9), dpi(4'd11));                  // c^ o t0^_i
      10'd863:  ins = d_intt(dp(4'd10));                                             // c t0_i -> P10
      10'd864:  ins = d_hint(dpi(4'd4), dp(4'd10));                                  // norm checks; the hints of polynomial i
      10'd865:  ins = u_loopn(1'b0, 10'd862, 4'd4);
      10'd866:  ins = u_br(BC_BAD, 10'd886);                                         // (before HEND: its time shows the hint count)
      10'd867:  ins = d_hend(1'b0);                                                  // accepted: zero bytes to omega, the 4 counts
      10'd868:  ins = b2s(B_DHS + 9'd0, E_W0, AM_NONE);                              // the hint bytes -> the signature
      10'd869:  ins = s2bn(E_W0, B_DHINT + 9'd0, 4'd0);
      10'd870:  ins = b2s(B_DHS + 9'd4, E_W0, AM_NONE);
      10'd871:  ins = s2bn(E_W0, B_DHINT + 9'd4, 4'd0);
      10'd872:  ins = b2s(B_DHS + 9'd8, E_W0, AM_NONE);
      10'd873:  ins = s2bn(E_W0, B_DHINT + 9'd8, 4'd3);
      10'd874:  ins = szero(E_W0);
      10'd875:  ins = s2b(E_DCT, B_DSIG, AM_NONE);                                   // c~
      10'd876:  ins = d_enc(DM_Z, dpi(4'd0), B_DSIG + 10'd4, LM_I72);                // z_i
      10'd877:  ins = u_loopn(1'b0, 10'd876, 4'd4);
      10'd878:  ins = szero(E_DRHOP);
      10'd879:  ins = szero(E_DRHOP + 4'd1);
      10'd880:  ins = szero(E_DRHO2);
      10'd881:  ins = szero(E_DRHO2 + 4'd1);
      10'd882:  ins = szero(E_DCT);
      10'd883:  ins = d_zero(dpi(4'd0));                                             // polynomials 0..14
      10'd884:  ins = u_loopn(1'b0, 10'd883, 4'd15);
      10'd885:  ins = u_end(R_OK);
      10'd886:  ins = u_set(ST_BADC);                                                // rejected: the next attempt
      10'd887:  ins = u_set(ST_KAPI);                                                // kappa += l
      10'd888:  ins = u_br(BC_ALWAYS, 10'd833);
`endif
`endif
`ifdef PQSE_STORE
`ifndef PQSE_AES
      10'd896:  ins = u_st(SO_SLOT, 1'b0);                                           // slot := header lane 2 (0..15)
      10'd897:  ins = u_br(BC_BAD, 10'd0);
      10'd898:  ins = u_st(SO_CNT, 1'b0);                                            // v := its version counter
      10'd899:  ins = u_br(BC_BAD, 10'd948);
      10'd900:  ins = u_br5(BC_STR, 10'd904);
      10'd901:  ins = u_st(SO_CHKF, 1'b0);                                           // STWRITE / STDEL: a version left?
      10'd902:  ins = u_br(BC_BAD, 10'd947);
      10'd903:  ins = u_br(BC_ALWAYS, 10'd910);
      10'd904:  ins = u_st(SO_CHKE, 1'b0);                                           // STREAD: ever written?
      10'd905:  ins = u_br(BC_BAD, 10'd946);
      10'd906:  ins = u_st(SO_RD, 1'b0);                                             // copy v mod 2 -> B_SM
      10'd907:  ins = u_br(BC_BAD, 10'd948);
      10'd908:  ins = u_st(SO_HCHK, 1'b0);                                           // its header: this slot, version v (an older copy fails here)
      10'd909:  ins = u_br(BC_BAD, 10'd945);
      10'd910:  ins = u_set(ST_RESEED);
      10'd911:  ins = u_br(BC_ALWAYS, 10'd48);                                       // PUF key -> KEK, back through L_PRET
      10'd912:  ins = u_br5(BC_STR, 10'd934);
      10'd913:  ins = u_br5(BC_STD, 10'd916);
      10'd914:  ins = u_st(SO_HDR, 1'b0);                                            // STWRITE: header lane 2 := {magic, v + 1, slot}, lane 3 := 0
      10'd915:  ins = u_br(BC_ALWAYS, 10'd921);
      10'd916:  ins = s2b(E_TMP, B_SM_MSG + 9'd0, AM_NONE);                          // STDEL: the data := 0 (E_TMP is 0 after the PUF routine)
      10'd917:  ins = s2b(E_TMP, B_SM_MSG + 9'd4, AM_NONE);
      10'd918:  ins = s2b(E_TMP, B_SM_MSG + 9'd8, AM_NONE);
      10'd919:  ins = s2b(E_TMP, B_SM_MSG + 9'd12, AM_NONE);
      10'd920:  ins = u_st(SO_HDR, 1'b1);                                            // ... the header marked deleted
      10'd921:  ins = h_trng(E_TMP);
      10'd922:  ins = s2bn(E_TMP, B_SM_HDR, 4'd2);                                   // nonce: header lanes 0, 1
      10'd923:  ins = szero(E_TMP);
      10'd924:  ins = h_rks(1'b0);                                                   // data xor KMACXOF256(KEK, header, 1024, "E1")
      10'd925:  ins = h_rtag(SNK_SEED);                                              // tag = KMAC256(KEK, header || data, 256, "T1")
      10'd926:  ins = s2b(E_TAG, B_SM_TAG, AM_NONE);
      10'd927:  ins = szero(E_TAG);
      10'd928:  ins = szero(E_KEK);
      10'd929:  ins = u_st(SO_WR, 1'b0);                                             // -> copy (v + 1) mod 2: erase, program, read back
      10'd930:  ins = u_br(BC_BAD, 10'd948);
      10'd931:  ins = u_st(SO_INC, 1'b0);                                            // the commit: counter := v + 1 (read back)
      10'd932:  ins = u_br(BC_BAD, 10'd948);
      10'd933:  ins = u_end(R_OK);
      10'd934:  ins = m_op(M_OKINI);                                                 // STREAD
      10'd935:  ins = h_rtag(SNK_MCMP);                                              // masked tag check
      10'd936:  ins = m_op(M_OKCHK);
      10'd937:  ins = m_op(M_OKOUT);
      10'd938:  ins = u_br(BC_BAD, 10'd944);
      10'd939:  ins = h_rks(1'b0);                                                   // the data in the clear
      10'd940:  ins = szero(E_KEK);
      10'd941:  ins = u_st(SO_DCHK, 1'b0);                                           // a deletion?
      10'd942:  ins = u_br(BC_BAD, 10'd946);                                         // (its data reads 0)
      10'd943:  ins = u_end(R_OK);
      10'd944:  ins = szero(E_KEK);                                                  // the tag did not check out
      10'd945:  ins = u_end(R_STBAD);                                                // not the slot's current record
      10'd946:  ins = u_end(R_STEMPTY);
      10'd947:  ins = u_end(R_STFULL);
      10'd948:  ins = u_end(R_STERR);
`endif
`endif
`ifdef PQSE_STORE
`ifdef PQSE_AES
      10'd896:  ins = u_st(SO_SLOT, 1'b0);                                           // slot := B_ST_SLOT (0..63)
      10'd897:  ins = u_br(BC_BAD, 10'd0);
      10'd898:  ins = u_st(SO_CNT, 1'b0);                                            // v := its version counter
      10'd899:  ins = u_br(BC_BAD, 10'd941);
      10'd900:  ins = u_br5(BC_STR, 10'd904);
      10'd901:  ins = u_st(SO_CHKF, 1'b0);                                           // STWRITE / STDEL: a version left?
      10'd902:  ins = u_br(BC_BAD, 10'd940);
      10'd903:  ins = u_br(BC_ALWAYS, 10'd910);
      10'd904:  ins = u_st(SO_CHKE, 1'b0);                                           // STREAD: ever written?
      10'd905:  ins = u_br(BC_BAD, 10'd939);
      10'd906:  ins = u_st(SO_RD, 1'b0);                                             // copy v mod 2 -> the GCM windows
      10'd907:  ins = u_br(BC_BAD, 10'd941);
      10'd908:  ins = u_st(SO_HCHK, 1'b0);                                           // its header (this slot, version v); GCM header {128, 16}
      10'd909:  ins = u_br(BC_BAD, 10'd938);
      10'd910:  ins = u_set(ST_RESEED);
      10'd911:  ins = u_br(BC_ALWAYS, 10'd48);                                       // PUF key -> KEK, back through L_PRET
      10'd912:  ins = u_br5(BC_STR, 10'd924);
      10'd913:  ins = u_br5(BC_STD, 10'd916);
      10'd914:  ins = u_st(SO_HDR, 1'b0);                                            // STWRITE: AAD lane 0 := {magic, v + 1, slot}, lane 1 := 0; GCM header
      10'd915:  ins = u_br(BC_ALWAYS, 10'd921);
      10'd916:  ins = s2b(E_TMP, B_GMSG + 9'd0, AM_NONE);                            // STDEL: the data := 0 (E_TMP is 0 after the PUF routine)
      10'd917:  ins = s2b(E_TMP, B_GMSG + 9'd4, AM_NONE);
      10'd918:  ins = s2b(E_TMP, B_GMSG + 9'd8, AM_NONE);
      10'd919:  ins = s2b(E_TMP, B_GMSG + 9'd12, AM_NONE);
      10'd920:  ins = u_st(SO_HDR, 1'b1);                                            // ... the header marked deleted
      10'd921:  ins = h_trng(E_TMP);
      10'd922:  ins = s2bn(E_TMP, B_GIV, 4'd2);                                      // the IV: a fresh nonce
      10'd923:  ins = szero(E_TMP);
      10'd924:  ins = h_kd(E_KEK, 2'd1, 16'h0052);                                   // K = SHA3-256(KEK || "R")
      10'd925:  ins = szero(E_KEK);
      10'd926:  ins = u_aes(AO_HDR);                                                 // P = 128, A = 16
      10'd927:  ins = u_br(BC_BAD, 10'd941);
      10'd928:  ins = u_br(BC_ALWAYS, 10'd975);                                      // STWRITE / STDEL: encrypt, tag; STREAD: check, decrypt
      10'd929:  ins = u_br5(BC_STR, 10'd935);                                        // (back from the GCM programs, tag good)
      10'd930:  ins = u_st(SO_WR, 1'b0);                                             // -> copy (v + 1) mod 2: erase, program, read back
      10'd931:  ins = u_br(BC_BAD, 10'd941);
      10'd932:  ins = u_st(SO_INC, 1'b0);                                            // the commit: counter := v + 1 (read back)
      10'd933:  ins = u_br(BC_BAD, 10'd941);
      10'd934:  ins = u_end(R_OK);
      10'd935:  ins = u_st(SO_DCHK, 1'b0);                                           // STREAD: a deletion?
      10'd936:  ins = u_br(BC_BAD, 10'd939);                                         // (its data reads 0)
      10'd937:  ins = u_end(R_OK);
      10'd938:  ins = u_end(R_STBAD);                                                // not the slot's current record (or its tag failed)
      10'd939:  ins = u_end(R_STEMPTY);
      10'd940:  ins = u_end(R_STFULL);
      10'd941:  ins = u_end(R_STERR);
`endif
`endif
`ifdef PQSE_AES
      10'd952:  ins = u_set(ST_RESEED);                                              // AESGEN
      10'd953:  ins = u_br(BC_ALWAYS, 10'd48);                                       // PUF key -> KEK, back through L_PRET
      10'd954:  ins = u_aes(AO_HDR);                                                 // GCMENC / GCMDEC: P, A, the key source
      10'd955:  ins = u_br(BC_BAD, 10'd0);
      10'd956:  ins = u_set(ST_RESEED);
      10'd957:  ins = u_aes(AO_KSRC);
      10'd958:  ins = u_br(BC_BAD, 10'd962);                                         // the PUF-wrapped key?
      10'd959:  ins = u_br(BC_NOSK, 10'd5);
      10'd960:  ins = h_ak(1'b0);                                                    // K = SHA3-256(session key || "A") -> E_W0
      10'd961:  ins = u_br(BC_ALWAYS, 10'd975);
      10'd962:  ins = u_set(ST_BADC);
      10'd963:  ins = u_br(BC_ALWAYS, 10'd48);                                       // PUF key -> KEK, back through L_PRET
      10'd964:  ins = u_br5(BC_AESG, 10'd1003);
      10'd965:  ins = m_op(M_OKINI);                                                 // GCM with the blob's key: unwrap it
      10'd966:  ins = h_atag(SNK_MCMP);                                              // masked tag check (suffix A || 32)
      10'd967:  ins = m_op(M_OKCHK);
      10'd968:  ins = m_op(M_OKOUT);
      10'd969:  ins = u_br(BC_BAD, 10'd1001);
      10'd970:  ins = b2s(B_BLOB_CT, E_W0, AM_NONE);
      10'd971:  ins = b2s(B_BLOB_CT + 9'd4, E_W1, AM_NONE);
      10'd972:  ins = h_ks(E_W0, E_W1);                                              // K now masked plaintext
      10'd973:  ins = szero(E_KEK);
      10'd974:  ins = szero(E_W1);
      10'd975:  ins = u_aes(AO_KEXP);                                                // the 15 round keys, masked
      10'd976:  ins = szero(E_W0);
      10'd977:  ins = u_aes(AO_H);                                                   // H = E(K, 0)
      10'd978:  ins = u_aes(AO_J0);                                                  // E(K, IV || 1)
      10'd979:  ins = u_br5(BC_GDEC, 10'd989);
      10'd980:  ins = u_aes(AO_CTR);                                                 // GCMENC: encrypt in place
      10'd981:  ins = u_aes(AO_GH);                                                  // GHASH(A, C)
      10'd982:  ins = u_aes(AO_TAG);                                                 // T = E(K, J0) ^ GHASH -> E_W0 lanes 0, 1 (masked)
      10'd983:  ins = s2bn(E_W0, B_GTAG, 4'd2);                                      // the tag (public)
      10'd984:  ins = u_aes(AO_WIPE);                                                // round keys, H, E(K, J0), T; the engine
      10'd985:  ins = u_br(BC_BAD, 10'd891);
      10'd986:  ins = u_br5(BC_ST, 10'd929);                                         // the record store: back to its program
      10'd987:  ins = u_br5(BC_OPEN, 10'd889);
      10'd988:  ins = u_end(R_OK);                                                   // GCMENC, GCMDEC, SEAL
      10'd989:  ins = u_aes(AO_GH);                                                  // GCMDEC: GHASH(A, C) of the ciphertext first
      10'd990:  ins = u_aes(AO_TAG);
      10'd991:  ins = h_gtr(1'b0);                                                   // SHA3-256(the received tag) -> E_TAG ...
      10'd992:  ins = s2b(E_TAG, B_SM_TAG, AM_NONE);                                 // ... where the masked compare reads it
      10'd993:  ins = szero(E_TAG);
      10'd994:  ins = m_op(M_OKINI);
      10'd995:  ins = h_gtc(1'b0);                                                   // SHA3-256(T), masked, compared
      10'd996:  ins = m_op(M_OKCHK);
      10'd997:  ins = m_op(M_OKOUT);
      10'd998:  ins = u_br(BC_BAD, 10'd984);                                         // a wrong tag: nothing decrypted (result 9)
      10'd999:  ins = u_aes(AO_CTR);                                                 // decrypt in place
      10'd1000: ins = u_br(BC_ALWAYS, 10'd984);
      10'd1001: ins = szero(E_KEK);                                                  // the blob's tag did not check out
      10'd1002: ins = u_br(BC_ALWAYS, 10'd2);
      10'd1003: ins = u_br(BC_INJ, 10'd1006);                                        // AESGEN
      10'd1004: ins = h_trng(E_W0);                                                  // K (masked)
      10'd1005: ins = u_br(BC_ALWAYS, 10'd1008);
      10'd1006: ins = b2s(B_INJD, E_W0, AM_NONE);                                    // TEST: injected K
      10'd1007: ins = sremask(E_W0);
      10'd1008: ins = szero(E_W1);                                                   // the blob's plaintext: K || 32 zero bytes
      10'd1009: ins = h_trng(E_TMP);
      10'd1010: ins = s2bn(E_TMP, B_BLOB_NONCE, 4'd2);                               // nonce (2 lanes)
      10'd1011: ins = szero(E_TMP);
      10'd1012: ins = h_ks(E_W0, E_W1);                                              // encrypted in place
      10'd1013: ins = s2b(E_W0, B_BLOB_CT, AM_NONE);                                 // ciphertext is public
      10'd1014: ins = s2b(E_W1, B_BLOB_CT + 9'd4, AM_NONE);
      10'd1015: ins = h_atag(SNK_SEED);
      10'd1016: ins = s2b(E_TAG, B_BLOB_TAG, AM_NONE);
      10'd1017: ins = szero(E_TAG);
      10'd1018: ins = szero(E_W0);
      10'd1019: ins = szero(E_W1);
      10'd1020: ins = szero(E_KEK);
      10'd1021: ins = u_end(R_OK);
      10'd889:  ins = u_set(ST_RXACC);                                               // OPEN: authentic, mark the counter
      10'd890:  ins = u_end(R_OK);
      10'd891:  ins = u_br5(BC_ST, 10'd938);                                         // a record whose tag failed: result 17
      10'd892:  ins = u_end(R_BADTAG);
`endif
      // ---- generated by scripts/pqse_ucode_v15_gen.py: end ----
      default: ins = u_end(R_UNKNOWN);
    endcase
  end
endmodule
